In [1]:
!lscpu

Architecture:                x86_64
  CPU op-mode(s):            32-bit, 64-bit
  Address sizes:             46 bits physical, 48 bits virtual
  Byte Order:                Little Endian
CPU(s):                      12
  On-line CPU(s) list:       0-11
Vendor ID:                   GenuineIntel
  Model name:                Intel(R) Xeon(R) CPU @ 2.20GHz
    CPU family:              6
    Model:                   85
    Thread(s) per core:      2
    Core(s) per socket:      6
    Socket(s):               1
    Stepping:                7
    BogoMIPS:                4400.30
    Flags:                   fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pg
                             e mca cmov pat pse36 clflush mmx fxsr sse sse2 ss h
                             t syscall nx pdpe1gb rdtscp lm constant_tsc rep_goo
                             d nopl xtopology nonstop_tsc cpuid tsc_known_freq p
                             ni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2ap
                             ic movbe popcnt aes xsave avx f16c rdrand hyperviso
                             r lahf_lm abm 3dnowprefetch ssbd ibrs ibpb stibp ib
                             rs_enhanced fsgsbase tsc_adjust bmi1 hle avx2 smep
                             bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed a
                             dx smap clflushopt clwb avx512cd avx512bw avx512vl
                             xsaveopt xsavec xgetbv1 xsaves arat avx512_vnni md_
                             clear arch_capabilities
Virtualization features:
  Hypervisor vendor:         KVM
  Virtualization type:       full
Caches (sum of all):
  L1d:                       192 KiB (6 instances)
  L1i:                       192 KiB (6 instances)
  L2:                        6 MiB (6 instances)
  L3:                        38.5 MiB (1 instance)
NUMA:
  NUMA node(s):              1
  NUMA node0 CPU(s):         0-11
Vulnerabilities:
  Gather data sampling:      Not affected
  Indirect target selection: Vulnerable
  Itlb multihit:             Not affected
  L1tf:                      Not affected
  Mds:                       Not affected
  Meltdown:                  Not affected
  Mmio stale data:           Vulnerable
  Reg file data sampling:    Not affected
  Retbleed:                  Vulnerable
  Spec rstack overflow:      Not affected
  Spec store bypass:         Vulnerable
  Spectre v1:                Vulnerable: __user pointer sanitization and usercop
                             y barriers only; no swapgs barriers
  Spectre v2:                Vulnerable; IBPB: disabled; STIBP: disabled; PBRSB-
                             eIBRS: Vulnerable; BHI: Vulnerable
  Srbds:                     Not affected
  Tsa:                       Not affected
  Tsx async abort:           Vulnerable
  Vmscape:                   Not affected

In [2]:
!nvidia-smi

Sun Apr 26 15:24:32 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA L4                      Off |   00000000:00:03.0 Off |                    0 |
| N/A   39C    P8             12W /   72W |       0MiB /  23034MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [3]:
import torch
print(f"PyTorch: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")
print(f"cuDNN version: {torch.backends.cudnn.version()}")

PyTorch: 2.10.0+cu128
CUDA available: True
cuDNN version: 91002

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
import os
from pathlib import Path

PROJECT_DIR = Path(os.environ.get(
    "AUV_PROJECT_DIR",
    "/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7",
))
assert PROJECT_DIR.exists(), f"Project directory not found: {PROJECT_DIR}"
%cd $PROJECT_DIR

/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7

In [7]:
%pip install -q torchdiffeq

# Phase-1A OC v4-lite formal workflow

**定位**：当前 Phase-1A 的正式 Colab 执行入口。

**目标**：干净执行 OC-only 三模型五 seed protocol-sensitivity check，判断 trajectory-consistent `v4_lite` noisy IC 是否改变当前 `iid_noisy_ic` 下的 PHNODE / structured dynamics 结论。

**边界**：

- 只跑 `oc + known-current surrogate`。
- 不复用旧 checkpoint / suite / proxy。
- 不生成旧 `phase1_*` 兼容产物。
- 不默认运行 Phase-1B 模型，也不默认运行 `degraded_eval` / `heading_biased_eval`。
- 每个长任务 cell 直接调用 `scripts/run_phase1a_oc_v4lite.sh`，保留实时 stdout/stderr。

## 0. Shared configuration

默认输出：

- training suites: `checkpoints/sweep_oc_phase1a_{smoke1,smoke3,decision}_{clean,iid,v4lite}_${RUN_TAG}`
- local proxy suites: `/content/_proxy_suites/sweep_oc_phase1a_{smoke1,smoke3,decision}_proxy_${RUN_TAG}`
- exported decision artifacts: `checkpoints/sweep_oc_phase1a_decision_proxy_${RUN_TAG}/phase1a_*`
- execution logs: `checkpoints/phase1a_logs/${RUN_TAG}/`
- run metadata: `checkpoints/phase1a_metadata_${RUN_TAG}/phase1a_{run_config,environment}.json`

如果需要重跑同一文档，先换 `RUN_TAG`。`preflight` 会拒绝覆盖已存在的目标目录。

In [8]:
import os

# Runtime
os.environ["PYTHON_BIN"] = "python"
os.environ["DEVICE"] = "cuda"
os.environ["LOCAL_PROXY_ROOT"] = "/content/_proxy_suites"

# Phase-1A identity
os.environ["RUN_TAG"] = "phase1a_oc_v4lite_cleanrun_v1"
os.environ["DATASET"] = "data/auv_oc_traj1000_blk150_s23_d0be9434.pkl"
os.environ["NOISE_REFERENCE"] = "remus100_dr"
os.environ["PHASE1A_LOG_DIR"] = str(PROJECT_DIR / "checkpoints" / "phase1a_logs" / os.environ["RUN_TAG"])
os.environ["PHASE1A_METADATA_DIR"] = str(PROJECT_DIR / "checkpoints" / f"phase1a_metadata_{os.environ['RUN_TAG']}")

# Phase-1A matrix
os.environ["PHASE1A_MODELS"] = "phnode_full ablate_no_mass_prior ablate_no_lift"
os.environ["SMOKE1_MODELS"] = "phnode_full"
os.environ["SMOKE_SEEDS"] = "42 44 46"
os.environ["DECISION_SEEDS"] = "42 43 44 45 46"

# Evaluation contract
os.environ["SMOKE_EVAL_NUM_TRAJ_PER_SCENARIO"] = "6"
os.environ["DECISION_EVAL_NUM_TRAJ_PER_SCENARIO"] = "30"
os.environ["EVAL_TIMES"] = "10 30 60"
os.environ["EVAL_SCENARIOS"] = "PRBS CHIRP OU"
os.environ["EVAL_BASE_SEED"] = "42"
os.environ["EVAL_NOISE_SEED"] = "2024"
os.environ["EVAL_PROGRESS_EVERY"] = "5"
os.environ["EVAL_NUM_DIAGNOSTIC_PLOTS"] = "6"
os.environ["IID_EVAL_PROFILES"] = "clean nominal_eval"
os.environ["V4_EVAL_PROFILES"] = "nominal_eval"

# Audit gate
os.environ["STRICT_ZERO_NOISE_AUDIT"] = "1"
os.environ["SOFT_MIN_EPOCH_SCALE"] = "0.05"

print("RUN_TAG=", os.environ["RUN_TAG"])
print("PHASE1A_MODELS=", os.environ["PHASE1A_MODELS"])
print("DECISION_SEEDS=", os.environ["DECISION_SEEDS"])
print("PHASE1A_LOG_DIR=", os.environ["PHASE1A_LOG_DIR"])
print("PHASE1A_METADATA_DIR=", os.environ["PHASE1A_METADATA_DIR"])

RUN_TAG= phase1a_oc_v4lite_cleanrun_v1
PHASE1A_MODELS= phnode_full ablate_no_mass_prior ablate_no_lift
DECISION_SEEDS= 42 43 44 45 46
PHASE1A_LOG_DIR= /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/phase1a_logs/phase1a_oc_v4lite_cleanrun_v1
PHASE1A_METADATA_DIR= /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/phase1a_metadata_phase1a_oc_v4lite_cleanrun_v1

## 1. Preflight

确认本次 clean run 的所有目标 suite / proxy 目录都不存在，并保存本次 run config / environment metadata。若这里失败，换 `RUN_TAG` 或手动清理目标目录。

In [ ]:
os.environ["MODE"] = "preflight"
!bash scripts/run_phase1a_oc_v4lite.sh

[phase1a]
MODE=preflight
RUN_TAG=phase1a_oc_v4lite_cleanrun_v1
DATASET=/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/data/auv_oc_traj1000_blk150_s23_d0be9434.pkl
DEVICE=cuda
PHASE1A_MODELS=phnode_full ablate_no_mass_prior ablate_no_lift
SMOKE1_MODELS=phnode_full
SMOKE_SEEDS=42 44 46
DECISION_SEEDS=42 43 44 45 46
NOISE_REFERENCE=remus100_dr
PHASE1A_LOG_DIR=/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/phase1a_logs/phase1a_oc_v4lite_cleanrun_v1
PHASE1A_METADATA_DIR=/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/phase1a_metadata_phase1a_oc_v4lite_cleanrun_v1
Preflight passed: all Phase-1A target suite/proxy directories are absent.
[metadata] /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/phase1a_metadata_phase1a_oc_v4lite_cleanrun_v1

## 2. Smoke-1 train + protocol validation

最小单模型 gate：`phnode_full × seeds 42/44/46 × clean/iid/v4lite`。

本 cell 完成训练、训练审计和 mandatory `v4_lite` protocol validation。

In [ ]:
# v4_lite 训练时间过长，进行暂停
os.environ["MODE"] = "smoke1_train"
!bash scripts/run_phase1a_oc_v4lite.sh

[phase1a]
MODE=smoke1_train
RUN_TAG=phase1a_oc_v4lite_cleanrun_v1
DATASET=/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/data/auv_oc_traj1000_blk150_s23_d0be9434.pkl
DEVICE=cuda
PHASE1A_MODELS=phnode_full ablate_no_mass_prior ablate_no_lift
SMOKE1_MODELS=phnode_full
SMOKE_SEEDS=42 44 46
DECISION_SEEDS=42 43 44 45 46
NOISE_REFERENCE=remus100_dr
PHASE1A_LOG_DIR=/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/phase1a_logs/phase1a_oc_v4lite_cleanrun_v1
PHASE1A_METADATA_DIR=/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/phase1a_metadata_phase1a_oc_v4lite_cleanrun_v1
[train] suite=sweep_oc_phase1a_smoke1_clean_phase1a_oc_v4lite_cleanrun_v1 models=phnode_full seeds=42 44 46 protocol=auto
Training all models with profile-based noisy IC.
Dataset: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/data/auv_oc_traj1000_blk150_s23_d0be9434.pkl
Group: all
Explicit models: phnode_full
Seeds: 42 44 46
Noise config: protocol=auto, profile=clean, scale=1.0, warmup=20, ramp=80, mix_ratio=0.5
Auto-eval profiles: block=[clean nominal_eval heading_biased_eval] heldout=[clean nominal_eval degraded_eval heading_biased_eval]
Suite directory: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke1_clean_phase1a_oc_v4lite_cleanrun_v1
Dataset: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/data/auv_oc_traj1000_blk150_s23_d0be9434.pkl
Models (1): phnode_full
Seeds: 42 44 46
[train] main_phnode_full_seed42
Loading dataset...
Loaded: 83850 train, 21000 test, t_eval=[0.   0.05 0.1  0.15 0.2 ]
Dataset split: trajectory | train trajectories: 559 | test trajectories: 140
Dataset ID: d0be9434
Dataset path: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_5/data/auv_oc_traj1000_blk150_s23_d0be9434.pkl | velocity convention: body_total | state dim: 27
Position std: [0.1508, 0.1400, 0.0370]
Velocity std: u=0.4722, v=0.0898, w=0.0718, p=0.0248, q=0.0906, r=0.0526
Actuator std: a0=0.1543, a1=0.1555, a2=299.0037
Training noise budget: protocol=clean | profile=clean | ref=remus100_dr | epoch_scale=0.000 | mix_ratio=0.500 | nu_r_lin_floor[u=0.0000, v=0.0000, w=0.0000] | nu_r_lin_ratio[u=0.0000, v=0.0000, w=0.0000] | nu_r_ang[p=0.0000, q=0.0000, r=0.0000] | rot[roll=0.0000, pitch=0.0000, yaw=0.0000]
Model: pH NODE Full [main/core] | canonical type: phnode_full
Model parameters: 62,803
Training dataset: id=d0be9434 | path=/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_5/data/auv_oc_traj1000_blk150_s23_d0be9434.pkl
Mass matrix initialized from physics
Training: epochs<=300, target_steps=5000, warmup_steps=400, lr=6.00e-03 -> 1.00e-04, solver=rk4, so3_reg=1.00e-03
Train samples: 83850, Test samples: 21000
Epoch    1 | Step    20/ 5000 | Train 4.3508e+00 | Test 5.0458e+00 | SO3(train/test) 1.26e-07/1.27e-07 | Fail(train/test) 0/0 | LR 4.10e-04 | 8.2s
Epoch    2 | Step    40/ 5000 | Train 3.5849e+00 | Test 4.3046e+00 | SO3(train/test) 1.19e-07/1.20e-07 | Fail(train/test) 0/0 | LR 7.05e-04 | 6.1s
Epoch    3 | Step    60/ 5000 | Train 2.9504e+00 | Test 3.2210e+00 | SO3(train/test) 1.16e-07/1.16e-07 | Fail(train/test) 0/0 | LR 1.00e-03 | 6.0s
Epoch    4 | Step    80/ 5000 | Train 1.7819e+00 | Test 1.0436e+00 | SO3(train/test) 1.20e-07/1.49e-07 | Fail(train/test) 0/0 | LR 1.29e-03 | 6.1s
Epoch    5 | Step   100/ 5000 | Train 7.7154e-01 | Test 6.1857e-01 | SO3(train/test) 1.29e-07/1.15e-07 | Fail(train/test) 0/0 | LR 1.59e-03 | 5.9s
Epoch    6 | Step   120/ 5000 | Train 7.3271e-01 | Test 7.2985e-01 | SO3(train/test) 1.15e-07/1.16e-07 | Fail(train/test) 0/0 | LR 1.88e-03 | 6.1s
Epoch    7 | Step   140/ 5000 | Train 7.3189e-01 | Test 7.0204e-01 | SO3(train/test) 1.19e-07/1.23e-07 | Fail(train/test) 0/0 | LR 2.18e-03 | 6.0s
Epoch    8 | Step   160/ 5000 | Train 9.1646e-01 | Test 1.3657e+00 | SO3(train/test) 1.88e-07/4.19e-07 | Fail(train/test) 0/0 | LR 2.47e-03 | 6.0s
Epoch    9 | Step   180/ 5000 | Train 6.4671e-01 | Test 4.2992e-01 | SO3(train/test) 2.93e-07/1.80e-07 | Fail(train/test) 0/0 | LR 2.77e-03 | 5.9s
Epoch   10 | Step   200/ 5000 | Train 4.0102e-01 | Test 3.2272e-01 | SO3(train/test) 1.32e-07/1.17e-07 | Fail(train/test) 0/0 | LR 3.06e-03 | 6.1s
Epoch   11 | Step   220/ 5000 | Train 5.4610e-01 | Test 7.6371e-01 | SO3(train/test) 1.17e-07/1.29e-07 | Fail(train/test) 0/0 | LR 3.36e-03 | 6.1s
Epoch   12 | Step   240/ 5000 | Train 6.8852e-01 | Test 1.3301e+00 | SO3(train/test) 1.22e-07/1.23e-07 | Fail(train/test) 0/0 | LR 3.65e-03 | 6.0s
Epoch   13 | Step   260/ 5000 | Train 9.8837e-01 | Test 1.7049e+00 | SO3(train/test) 1.39e-07/1.64e-07 | Fail(train/test) 0/0 | LR 3.95e-03 | 5.9s
Epoch   14 | Step   280/ 5000 | Train 1.2011e+00 | Test 1.1263e+00 | SO3(train/test) 6.34e-07/9.02e-07 | Fail(train/test) 0/0 | LR 4.24e-03 | 6.0s
Epoch   15 | Step   300/ 5000 | Train 7.0657e-01 | Test 4.1899e-01 | SO3(train/test) 2.46e-07/2.21e-07 | Fail(train/test) 0/0 | LR 4.54e-03 | 6.0s
Epoch   16 | Step   320/ 5000 | Train 3.6999e-01 | Test 4.1457e-01 | SO3(train/test) 1.52e-07/1.28e-07 | Fail(train/test) 0/0 | LR 4.83e-03 | 6.2s
Epoch   17 | Step   340/ 5000 | Train 8.2631e-01 | Test 1.2798e+02 | SO3(train/test) 4.09e-07/2.30e-04 | Fail(train/test) 0/0 | LR 5.13e-03 | 6.0s
Epoch   18 | Step   360/ 5000 | Train 9.8227e+00 | Test 1.6472e+00 | SO3(train/test) 1.36e-05/1.22e-07 | Fail(train/test) 0/0 | LR 5.42e-03 | 6.0s
Epoch   19 | Step   380/ 5000 | Train 9.0113e-01 | Test 1.5542e+00 | SO3(train/test) 1.21e-07/1.32e-07 | Fail(train/test) 0/0 | LR 5.72e-03 | 5.9s
Epoch   20 | Step   400/ 5000 | Train 6.4581e-01 | Test 4.2124e-01 | SO3(train/test) 1.17e-07/1.13e-07 | Fail(train/test) 0/0 | LR 6.00e-03 | 6.0s
Epoch   21 | Step   420/ 5000 | Train 4.9859e-01 | Test 2.5856e-01 | SO3(train/test) 1.14e-07/1.14e-07 | Fail(train/test) 0/0 | LR 6.00e-03 | 6.0s
Epoch   22 | Step   440/ 5000 | Train 1.1076e+00 | Test 3.2183e+00 | SO3(train/test) 1.18e-07/1.27e-07 | Fail(train/test) 0/0 | LR 6.00e-03 | 5.9s
Epoch   23 | Step   460/ 5000 | Train 1.0052e+00 | Test 8.8541e-01 | SO3(train/test) 1.37e-07/1.89e-07 | Fail(train/test) 0/0 | LR 6.00e-03 | 6.0s
Epoch   24 | Step   480/ 5000 | Train 5.1725e-01 | Test 4.3019e-01 | SO3(train/test) 1.27e-07/1.14e-07 | Fail(train/test) 0/0 | LR 6.00e-03 | 6.0s
Epoch   25 | Step   500/ 5000 | Train 4.2138e-01 | Test 7.0924e-01 | SO3(train/test) 1.14e-07/1.13e-07 | Fail(train/test) 0/0 | LR 5.99e-03 | 6.0s
Epoch   26 | Step   520/ 5000 | Train 7.3917e-01 | Test 6.1279e-01 | SO3(train/test) 1.17e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.99e-03 | 6.0s
Epoch   27 | Step   540/ 5000 | Train 5.5732e-01 | Test 4.9149e-01 | SO3(train/test) 1.14e-07/1.13e-07 | Fail(train/test) 0/0 | LR 5.99e-03 | 5.9s
Epoch   28 | Step   560/ 5000 | Train 4.0944e-01 | Test 2.9991e-01 | SO3(train/test) 1.13e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.98e-03 | 5.9s
Epoch   29 | Step   580/ 5000 | Train 3.3119e-01 | Test 3.8784e-01 | SO3(train/test) 1.14e-07/1.13e-07 | Fail(train/test) 0/0 | LR 5.98e-03 | 5.9s
Epoch   30 | Step   600/ 5000 | Train 2.9614e-01 | Test 3.7977e-01 | SO3(train/test) 1.13e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.97e-03 | 5.9s
Epoch   31 | Step   620/ 5000 | Train 2.6610e-01 | Test 1.7794e-01 | SO3(train/test) 1.14e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.97e-03 | 6.2s
Epoch   32 | Step   640/ 5000 | Train 3.4427e-01 | Test 4.2377e-01 | SO3(train/test) 1.14e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.96e-03 | 6.0s
Epoch   33 | Step   660/ 5000 | Train 2.9494e-01 | Test 3.0951e-01 | SO3(train/test) 1.14e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.95e-03 | 5.9s
Epoch   34 | Step   680/ 5000 | Train 3.0940e-01 | Test 2.4717e-01 | SO3(train/test) 1.13e-07/1.13e-07 | Fail(train/test) 0/0 | LR 5.95e-03 | 6.0s
Epoch   35 | Step   700/ 5000 | Train 2.4540e-01 | Test 2.1880e-01 | SO3(train/test) 1.14e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.94e-03 | 6.0s
Epoch   36 | Step   720/ 5000 | Train 2.5469e-01 | Test 3.5887e-01 | SO3(train/test) 1.14e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.93e-03 | 6.0s
Epoch   37 | Step   740/ 5000 | Train 1.8363e-01 | Test 1.2469e-01 | SO3(train/test) 1.14e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.92e-03 | 6.0s
Epoch   38 | Step   760/ 5000 | Train 2.0243e-01 | Test 2.5875e-01 | SO3(train/test) 1.14e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.91e-03 | 6.0s
Epoch   39 | Step   780/ 5000 | Train 1.9395e-01 | Test 2.3579e-01 | SO3(train/test) 1.14e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.90e-03 | 6.1s
Epoch   40 | Step   800/ 5000 | Train 2.7430e-01 | Test 2.6487e-01 | SO3(train/test) 1.14e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.89e-03 | 5.9s
Epoch   41 | Step   820/ 5000 | Train 2.0269e-01 | Test 2.5005e-01 | SO3(train/test) 1.14e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.88e-03 | 6.0s
Epoch   42 | Step   840/ 5000 | Train 3.7915e-01 | Test 4.9165e-01 | SO3(train/test) 1.15e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.87e-03 | 5.9s
Epoch   43 | Step   860/ 5000 | Train 2.0918e-01 | Test 1.2922e-01 | SO3(train/test) 1.14e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.86e-03 | 6.0s
Epoch   44 | Step   880/ 5000 | Train 3.1596e-01 | Test 4.9138e-01 | SO3(train/test) 1.14e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.84e-03 | 5.9s
Epoch   45 | Step   900/ 5000 | Train 3.7134e-01 | Test 2.8780e-01 | SO3(train/test) 1.14e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.83e-03 | 6.0s
Epoch   46 | Step   920/ 5000 | Train 3.8193e-01 | Test 4.0802e-01 | SO3(train/test) 1.14e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.82e-03 | 6.0s
Epoch   47 | Step   940/ 5000 | Train 2.0748e-01 | Test 1.2967e-01 | SO3(train/test) 1.14e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.80e-03 | 5.9s
Epoch   48 | Step   960/ 5000 | Train 2.7099e-01 | Test 3.0930e-01 | SO3(train/test) 1.15e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.79e-03 | 6.0s
Epoch   49 | Step   980/ 5000 | Train 1.7944e-01 | Test 1.3753e-01 | SO3(train/test) 1.14e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.77e-03 | 6.0s
Epoch   50 | Step  1000/ 5000 | Train 1.1704e-01 | Test 9.1627e-02 | SO3(train/test) 1.15e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.76e-03 | 6.0s
Epoch   51 | Step  1020/ 5000 | Train 2.3458e-01 | Test 1.9837e-01 | SO3(train/test) 1.15e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.74e-03 | 6.1s
Epoch   52 | Step  1040/ 5000 | Train 1.7602e-01 | Test 2.2454e-01 | SO3(train/test) 1.15e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.72e-03 | 6.0s
Epoch   53 | Step  1060/ 5000 | Train 1.1398e-01 | Test 1.0144e-01 | SO3(train/test) 1.14e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.71e-03 | 6.0s
Epoch   54 | Step  1080/ 5000 | Train 1.4875e-01 | Test 1.7859e-01 | SO3(train/test) 1.15e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.69e-03 | 6.0s
Epoch   55 | Step  1100/ 5000 | Train 1.5380e-01 | Test 1.1351e-01 | SO3(train/test) 1.14e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.67e-03 | 5.9s
Epoch   56 | Step  1120/ 5000 | Train 1.0199e-01 | Test 1.2991e-01 | SO3(train/test) 1.15e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.65e-03 | 6.1s
Epoch   57 | Step  1140/ 5000 | Train 1.1197e-01 | Test 1.2931e-01 | SO3(train/test) 1.15e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.63e-03 | 5.9s
Epoch   58 | Step  1160/ 5000 | Train 8.4732e-02 | Test 8.0641e-02 | SO3(train/test) 1.16e-07/1.17e-07 | Fail(train/test) 0/0 | LR 5.61e-03 | 6.0s
Epoch   59 | Step  1180/ 5000 | Train 8.6915e-02 | Test 1.3275e-01 | SO3(train/test) 1.17e-07/1.17e-07 | Fail(train/test) 0/0 | LR 5.59e-03 | 6.0s
Epoch   60 | Step  1200/ 5000 | Train 2.1926e-01 | Test 1.5293e-01 | SO3(train/test) 1.16e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.57e-03 | 6.0s
Epoch   61 | Step  1220/ 5000 | Train 1.6092e-01 | Test 1.0480e-01 | SO3(train/test) 1.15e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.55e-03 | 6.1s
Epoch   62 | Step  1240/ 5000 | Train 9.0895e-02 | Test 9.5688e-02 | SO3(train/test) 1.16e-07/1.17e-07 | Fail(train/test) 0/0 | LR 5.53e-03 | 6.0s
Epoch   63 | Step  1260/ 5000 | Train 7.5114e-02 | Test 8.9048e-02 | SO3(train/test) 1.17e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.51e-03 | 5.9s
Epoch   64 | Step  1280/ 5000 | Train 7.0856e-02 | Test 6.5896e-02 | SO3(train/test) 1.17e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.48e-03 | 6.0s
Epoch   65 | Step  1300/ 5000 | Train 6.8714e-02 | Test 7.0324e-02 | SO3(train/test) 1.16e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.46e-03 | 5.9s
Epoch   66 | Step  1320/ 5000 | Train 5.8493e-02 | Test 1.0690e-01 | SO3(train/test) 1.16e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.44e-03 | 6.1s
Epoch   67 | Step  1340/ 5000 | Train 7.5651e-02 | Test 8.7984e-02 | SO3(train/test) 1.16e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.41e-03 | 6.0s
Epoch   68 | Step  1360/ 5000 | Train 8.7879e-02 | Test 8.0786e-02 | SO3(train/test) 1.16e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.39e-03 | 6.0s
Epoch   69 | Step  1380/ 5000 | Train 6.5190e-02 | Test 6.8278e-02 | SO3(train/test) 1.16e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.36e-03 | 6.0s
Epoch   70 | Step  1400/ 5000 | Train 7.1615e-02 | Test 1.0761e-01 | SO3(train/test) 1.16e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.34e-03 | 6.0s
Epoch   71 | Step  1420/ 5000 | Train 6.6949e-02 | Test 6.2039e-02 | SO3(train/test) 1.15e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.31e-03 | 6.1s
Epoch   72 | Step  1440/ 5000 | Train 6.9502e-02 | Test 5.8650e-02 | SO3(train/test) 1.16e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.29e-03 | 6.0s
Epoch   73 | Step  1460/ 5000 | Train 7.7124e-02 | Test 6.3036e-02 | SO3(train/test) 1.16e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.26e-03 | 6.0s
Epoch   74 | Step  1480/ 5000 | Train 6.1404e-02 | Test 5.9311e-02 | SO3(train/test) 1.15e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.23e-03 | 6.0s
Epoch   75 | Step  1500/ 5000 | Train 5.6825e-02 | Test 8.3078e-02 | SO3(train/test) 1.15e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.21e-03 | 6.0s
Epoch   76 | Step  1520/ 5000 | Train 8.8365e-02 | Test 6.7274e-02 | SO3(train/test) 1.16e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.18e-03 | 6.1s
Epoch   77 | Step  1540/ 5000 | Train 5.9874e-02 | Test 4.7619e-02 | SO3(train/test) 1.15e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.15e-03 | 6.0s
Epoch   78 | Step  1560/ 5000 | Train 4.6362e-02 | Test 4.4534e-02 | SO3(train/test) 1.16e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.12e-03 | 5.9s
Epoch   79 | Step  1580/ 5000 | Train 7.1124e-02 | Test 4.5532e-02 | SO3(train/test) 1.16e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.09e-03 | 6.0s
Epoch   80 | Step  1600/ 5000 | Train 4.4796e-02 | Test 5.4336e-02 | SO3(train/test) 1.16e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.06e-03 | 6.1s
Epoch   81 | Step  1620/ 5000 | Train 6.5072e-02 | Test 5.5401e-02 | SO3(train/test) 1.16e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.03e-03 | 6.1s
Epoch   82 | Step  1640/ 5000 | Train 4.2136e-02 | Test 3.9637e-02 | SO3(train/test) 1.16e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.00e-03 | 6.0s
Epoch   83 | Step  1660/ 5000 | Train 3.6180e-02 | Test 3.6724e-02 | SO3(train/test) 1.15e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.97e-03 | 6.0s
Epoch   84 | Step  1680/ 5000 | Train 3.5026e-02 | Test 4.2196e-02 | SO3(train/test) 1.16e-07/1.15e-07 | Fail(train/test) 0/0 | LR 4.94e-03 | 6.0s
Epoch   85 | Step  1700/ 5000 | Train 3.1617e-02 | Test 3.0568e-02 | SO3(train/test) 1.15e-07/1.15e-07 | Fail(train/test) 0/0 | LR 4.91e-03 | 6.0s
Epoch   86 | Step  1720/ 5000 | Train 3.6397e-02 | Test 3.2962e-02 | SO3(train/test) 1.16e-07/1.15e-07 | Fail(train/test) 0/0 | LR 4.88e-03 | 6.1s
Epoch   87 | Step  1740/ 5000 | Train 2.9300e-02 | Test 2.5068e-02 | SO3(train/test) 1.16e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.85e-03 | 6.0s
Epoch   88 | Step  1760/ 5000 | Train 2.7222e-02 | Test 2.6289e-02 | SO3(train/test) 1.16e-07/1.15e-07 | Fail(train/test) 0/0 | LR 4.82e-03 | 6.0s
Epoch   89 | Step  1780/ 5000 | Train 2.3673e-02 | Test 1.6500e-02 | SO3(train/test) 1.16e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.78e-03 | 6.0s
Epoch   90 | Step  1800/ 5000 | Train 2.1020e-02 | Test 2.4197e-02 | SO3(train/test) 1.16e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.75e-03 | 5.9s
Epoch   91 | Step  1820/ 5000 | Train 1.6720e-02 | Test 1.3625e-02 | SO3(train/test) 1.16e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.72e-03 | 6.2s
Epoch   92 | Step  1840/ 5000 | Train 1.1516e-02 | Test 1.1032e-02 | SO3(train/test) 1.16e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.68e-03 | 5.9s
Epoch   93 | Step  1860/ 5000 | Train 1.1379e-02 | Test 1.3947e-02 | SO3(train/test) 1.17e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.65e-03 | 6.1s
Epoch   94 | Step  1880/ 5000 | Train 1.9458e-02 | Test 1.6386e-02 | SO3(train/test) 1.16e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.62e-03 | 5.9s
Epoch   95 | Step  1900/ 5000 | Train 1.6805e-02 | Test 1.1705e-02 | SO3(train/test) 1.16e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.58e-03 | 6.0s
Epoch   96 | Step  1920/ 5000 | Train 1.7272e-02 | Test 1.0341e-02 | SO3(train/test) 1.17e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.55e-03 | 6.0s
Epoch   97 | Step  1940/ 5000 | Train 1.5317e-02 | Test 9.4265e-03 | SO3(train/test) 1.16e-07/1.17e-07 | Fail(train/test) 0/0 | LR 4.51e-03 | 6.0s
Epoch   98 | Step  1960/ 5000 | Train 2.6895e-02 | Test 2.6610e-02 | SO3(train/test) 1.17e-07/1.17e-07 | Fail(train/test) 0/0 | LR 4.48e-03 | 5.9s
Epoch   99 | Step  1980/ 5000 | Train 1.5651e-02 | Test 1.3285e-02 | SO3(train/test) 1.16e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.44e-03 | 6.0s
Epoch  100 | Step  2000/ 5000 | Train 1.1298e-02 | Test 1.5591e-02 | SO3(train/test) 1.17e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.41e-03 | 6.0s
Epoch  101 | Step  2020/ 5000 | Train 1.3338e-02 | Test 1.7737e-02 | SO3(train/test) 1.17e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.37e-03 | 6.1s
Epoch  102 | Step  2040/ 5000 | Train 1.3850e-02 | Test 1.5130e-02 | SO3(train/test) 1.17e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.33e-03 | 6.0s
Epoch  103 | Step  2060/ 5000 | Train 1.3803e-02 | Test 1.5082e-02 | SO3(train/test) 1.17e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.30e-03 | 6.0s
Epoch  104 | Step  2080/ 5000 | Train 1.3570e-02 | Test 1.7037e-02 | SO3(train/test) 1.16e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.26e-03 | 6.0s
Epoch  105 | Step  2100/ 5000 | Train 1.2729e-02 | Test 1.1249e-02 | SO3(train/test) 1.17e-07/1.17e-07 | Fail(train/test) 0/0 | LR 4.22e-03 | 6.0s
Epoch  106 | Step  2120/ 5000 | Train 1.2498e-02 | Test 1.7916e-02 | SO3(train/test) 1.16e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.19e-03 | 6.1s
Epoch  107 | Step  2140/ 5000 | Train 1.2070e-02 | Test 1.1470e-02 | SO3(train/test) 1.17e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.15e-03 | 5.9s
Epoch  108 | Step  2160/ 5000 | Train 1.1073e-02 | Test 1.1382e-02 | SO3(train/test) 1.17e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.11e-03 | 5.9s
Epoch  109 | Step  2180/ 5000 | Train 1.0554e-02 | Test 9.9167e-03 | SO3(train/test) 1.17e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.08e-03 | 5.9s
Epoch  110 | Step  2200/ 5000 | Train 1.0220e-02 | Test 9.7358e-03 | SO3(train/test) 1.17e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.04e-03 | 6.0s
Epoch  111 | Step  2220/ 5000 | Train 9.5013e-03 | Test 8.8022e-03 | SO3(train/test) 1.17e-07/1.17e-07 | Fail(train/test) 0/0 | LR 4.00e-03 | 6.1s
Epoch  112 | Step  2240/ 5000 | Train 9.5715e-03 | Test 1.0344e-02 | SO3(train/test) 1.17e-07/1.17e-07 | Fail(train/test) 0/0 | LR 3.96e-03 | 5.9s
Epoch  113 | Step  2260/ 5000 | Train 8.4847e-03 | Test 8.7496e-03 | SO3(train/test) 1.17e-07/1.16e-07 | Fail(train/test) 0/0 | LR 3.92e-03 | 6.0s
Epoch  114 | Step  2280/ 5000 | Train 6.5405e-03 | Test 5.7298e-03 | SO3(train/test) 1.17e-07/1.16e-07 | Fail(train/test) 0/0 | LR 3.88e-03 | 6.0s
Epoch  115 | Step  2300/ 5000 | Train 5.6093e-03 | Test 5.4338e-03 | SO3(train/test) 1.17e-07/1.17e-07 | Fail(train/test) 0/0 | LR 3.85e-03 | 5.9s
Epoch  116 | Step  2320/ 5000 | Train 7.7676e-03 | Test 3.9060e-02 | SO3(train/test) 1.17e-07/1.17e-07 | Fail(train/test) 0/0 | LR 3.81e-03 | 6.2s
Epoch  117 | Step  2340/ 5000 | Train 3.0149e-02 | Test 2.1199e-02 | SO3(train/test) 1.17e-07/1.17e-07 | Fail(train/test) 0/0 | LR 3.77e-03 | 5.9s

In [ ]:
# 第一次修改 140s -> 14s
os.environ["MODE"] = "smoke1_train_v4lite_resume"
!bash scripts/run_phase1a_oc_v4lite.sh

[phase1a]
MODE=smoke1_train_v4lite_resume
RUN_TAG=phase1a_oc_v4lite_cleanrun_v1
DATASET=/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/data/auv_oc_traj1000_blk150_s23_d0be9434.pkl
DEVICE=cuda
PHASE1A_MODELS=phnode_full ablate_no_mass_prior ablate_no_lift
SMOKE1_MODELS=phnode_full
SMOKE_SEEDS=42 44 46
DECISION_SEEDS=42 43 44 45 46
NOISE_REFERENCE=remus100_dr
PHASE1A_LOG_DIR=/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/phase1a_logs/phase1a_oc_v4lite_cleanrun_v1
PHASE1A_METADATA_DIR=/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/phase1a_metadata_phase1a_oc_v4lite_cleanrun_v1
[resume-train] suite=sweep_oc_phase1a_smoke1_v4lite_phase1a_oc_v4lite_cleanrun_v1 models=phnode_full seeds=42 44 46 protocol=v4_lite
Training all models with profile-based noisy IC.
Dataset: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/data/auv_oc_traj1000_blk150_s23_d0be9434.pkl
Group: all
Explicit models: phnode_full
Seeds: 42 44 46
Noise config: protocol=v4_lite, profile=nominal_train, scale=1.0, warmup=20, ramp=80, mix_ratio=0.5
Auto-eval profiles: block=[clean nominal_eval heading_biased_eval] heldout=[clean nominal_eval degraded_eval heading_biased_eval]
Suite directory: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke1_v4lite_phase1a_oc_v4lite_cleanrun_v1
Dataset: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/data/auv_oc_traj1000_blk150_s23_d0be9434.pkl
Models (1): phnode_full
Seeds: 42 44 46
[train] main_phnode_full_seed42
Loading dataset...
Loaded: 83850 train, 21000 test, t_eval=[0.   0.05 0.1  0.15 0.2 ]
Dataset split: trajectory | train trajectories: 559 | test trajectories: 140
Dataset ID: d0be9434
Dataset path: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_5/data/auv_oc_traj1000_blk150_s23_d0be9434.pkl | velocity convention: body_total | state dim: 27
Position std: [0.1508, 0.1400, 0.0370]
Velocity std: u=0.4722, v=0.0898, w=0.0718, p=0.0248, q=0.0906, r=0.0526
Actuator std: a0=0.1543, a1=0.1555, a2=299.0037
Training noise budget: protocol=v4_lite | profile=nominal_train | ref=remus100_dr | traj_corr=0.850 | epoch_scale=1.000 | mix_ratio=0.500 | nu_r_lin_floor[u=0.0020, v=0.0020, w=0.0030] | nu_r_lin_ratio[u=0.0020, v=0.0020, w=0.0020] | nu_r_ang[p=0.0006, q=0.0006, r=0.0010] | rot[roll=0.0015, pitch=0.0015, yaw=0.0060]
Model: pH NODE Full [main/core] | canonical type: phnode_full
Model parameters: 62,803
Training dataset: id=d0be9434 | path=/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_5/data/auv_oc_traj1000_blk150_s23_d0be9434.pkl
Mass matrix initialized from physics
Training: epochs<=300, target_steps=5000, warmup_steps=400, lr=6.00e-03 -> 1.00e-04, solver=rk4, so3_reg=1.00e-03
Train samples: 83850, Test samples: 21000
Epoch    1 | Step    20/ 5000 | Train 4.3508e+00 | Test 5.0458e+00 | SO3(train/test) 1.26e-07/1.27e-07 | Fail(train/test) 0/0 | LR 4.10e-04 | 8.1s
Epoch    2 | Step    40/ 5000 | Train 3.5849e+00 | Test 4.3046e+00 | SO3(train/test) 1.19e-07/1.20e-07 | Fail(train/test) 0/0 | LR 7.05e-04 | 6.0s
Epoch    3 | Step    60/ 5000 | Train 2.9504e+00 | Test 3.2210e+00 | SO3(train/test) 1.16e-07/1.16e-07 | Fail(train/test) 0/0 | LR 1.00e-03 | 5.9s
Epoch    4 | Step    80/ 5000 | Train 1.7819e+00 | Test 1.0436e+00 | SO3(train/test) 1.20e-07/1.49e-07 | Fail(train/test) 0/0 | LR 1.29e-03 | 5.8s
Epoch    5 | Step   100/ 5000 | Train 7.7154e-01 | Test 6.1857e-01 | SO3(train/test) 1.29e-07/1.15e-07 | Fail(train/test) 0/0 | LR 1.59e-03 | 5.9s
Epoch    6 | Step   120/ 5000 | Train 7.3271e-01 | Test 7.2985e-01 | SO3(train/test) 1.15e-07/1.16e-07 | Fail(train/test) 0/0 | LR 1.88e-03 | 5.9s
Epoch    7 | Step   140/ 5000 | Train 7.3189e-01 | Test 7.0204e-01 | SO3(train/test) 1.19e-07/1.23e-07 | Fail(train/test) 0/0 | LR 2.18e-03 | 5.9s
Epoch    8 | Step   160/ 5000 | Train 9.1646e-01 | Test 1.3657e+00 | SO3(train/test) 1.88e-07/4.19e-07 | Fail(train/test) 0/0 | LR 2.47e-03 | 5.9s
Epoch    9 | Step   180/ 5000 | Train 6.4671e-01 | Test 4.2992e-01 | SO3(train/test) 2.93e-07/1.80e-07 | Fail(train/test) 0/0 | LR 2.77e-03 | 5.8s
Epoch   10 | Step   200/ 5000 | Train 4.0102e-01 | Test 3.2272e-01 | SO3(train/test) 1.32e-07/1.17e-07 | Fail(train/test) 0/0 | LR 3.06e-03 | 5.9s
Epoch   11 | Step   220/ 5000 | Train 5.4610e-01 | Test 7.6371e-01 | SO3(train/test) 1.17e-07/1.29e-07 | Fail(train/test) 0/0 | LR 3.36e-03 | 6.0s
Epoch   12 | Step   240/ 5000 | Train 6.8852e-01 | Test 1.3301e+00 | SO3(train/test) 1.22e-07/1.23e-07 | Fail(train/test) 0/0 | LR 3.65e-03 | 5.8s
Epoch   13 | Step   260/ 5000 | Train 9.8837e-01 | Test 1.7049e+00 | SO3(train/test) 1.39e-07/1.64e-07 | Fail(train/test) 0/0 | LR 3.95e-03 | 5.8s
Epoch   14 | Step   280/ 5000 | Train 1.2011e+00 | Test 1.1263e+00 | SO3(train/test) 6.34e-07/9.02e-07 | Fail(train/test) 0/0 | LR 4.24e-03 | 5.8s
Epoch   15 | Step   300/ 5000 | Train 7.0657e-01 | Test 4.1899e-01 | SO3(train/test) 2.46e-07/2.21e-07 | Fail(train/test) 0/0 | LR 4.54e-03 | 5.8s
Epoch   16 | Step   320/ 5000 | Train 3.6999e-01 | Test 4.1457e-01 | SO3(train/test) 1.52e-07/1.28e-07 | Fail(train/test) 0/0 | LR 4.83e-03 | 6.1s
Epoch   17 | Step   340/ 5000 | Train 8.2631e-01 | Test 1.2798e+02 | SO3(train/test) 4.09e-07/2.30e-04 | Fail(train/test) 0/0 | LR 5.13e-03 | 5.7s
Epoch   18 | Step   360/ 5000 | Train 9.8227e+00 | Test 1.6472e+00 | SO3(train/test) 1.36e-05/1.22e-07 | Fail(train/test) 0/0 | LR 5.42e-03 | 5.8s
Epoch   19 | Step   380/ 5000 | Train 9.0113e-01 | Test 1.5542e+00 | SO3(train/test) 1.21e-07/1.32e-07 | Fail(train/test) 0/0 | LR 5.72e-03 | 5.8s
Epoch   20 | Step   400/ 5000 | Train 6.4581e-01 | Test 4.2124e-01 | SO3(train/test) 1.17e-07/1.13e-07 | Fail(train/test) 0/0 | LR 6.00e-03 | 5.8s
Epoch   21 | Step   420/ 5000 | Train 5.6739e-01 | Test 2.9053e-01 | SO3(train/test) 3.62e-07/1.14e-07 | Fail(train/test) 0/0 | LR 6.00e-03 | 14.5s
Epoch   22 | Step   440/ 5000 | Train 8.7183e-01 | Test 1.3127e+00 | SO3(train/test) 3.61e-07/1.15e-07 | Fail(train/test) 0/0 | LR 6.00e-03 | 14.1s
Epoch   23 | Step   460/ 5000 | Train 1.0885e+00 | Test 4.9966e-01 | SO3(train/test) 3.59e-07/1.15e-07 | Fail(train/test) 0/0 | LR 6.00e-03 | 14.3s
Epoch   24 | Step   480/ 5000 | Train 6.0009e-01 | Test 5.2679e-01 | SO3(train/test) 3.59e-07/1.16e-07 | Fail(train/test) 0/0 | LR 6.00e-03 | 14.3s
Epoch   25 | Step   500/ 5000 | Train 4.6272e-01 | Test 3.5227e-01 | SO3(train/test) 3.63e-07/1.13e-07 | Fail(train/test) 0/0 | LR 5.99e-03 | 14.4s
Epoch   26 | Step   520/ 5000 | Train 3.6958e-01 | Test 3.9838e-01 | SO3(train/test) 3.62e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.99e-03 | 14.4s
Epoch   27 | Step   540/ 5000 | Train 3.3972e-01 | Test 3.1377e-01 | SO3(train/test) 3.63e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.99e-03 | 14.3s
Epoch   28 | Step   560/ 5000 | Train 6.6435e-01 | Test 4.4928e-01 | SO3(train/test) 3.63e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.98e-03 | 14.2s
Epoch   29 | Step   580/ 5000 | Train 3.6840e-01 | Test 2.8955e-01 | SO3(train/test) 3.64e-07/1.13e-07 | Fail(train/test) 0/0 | LR 5.98e-03 | 14.1s
Epoch   30 | Step   600/ 5000 | Train 2.1683e-01 | Test 1.6905e-01 | SO3(train/test) 3.63e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.97e-03 | 14.2s
Epoch   31 | Step   620/ 5000 | Train 3.5577e-01 | Test 5.7210e-01 | SO3(train/test) 3.61e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.97e-03 | 14.2s
Epoch   32 | Step   640/ 5000 | Train 3.3903e-01 | Test 8.4338e-01 | SO3(train/test) 3.62e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.96e-03 | 14.1s
Epoch   33 | Step   660/ 5000 | Train 4.2909e-01 | Test 2.7734e-01 | SO3(train/test) 3.65e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.95e-03 | 14.2s
Epoch   34 | Step   680/ 5000 | Train 2.5479e-01 | Test 2.0641e-01 | SO3(train/test) 3.62e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.95e-03 | 14.2s
Epoch   35 | Step   700/ 5000 | Train 2.4322e-01 | Test 2.4076e-01 | SO3(train/test) 3.65e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.94e-03 | 14.2s
Epoch   36 | Step   720/ 5000 | Train 2.4040e-01 | Test 1.1666e-01 | SO3(train/test) 3.61e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.93e-03 | 14.2s
Epoch   37 | Step   740/ 5000 | Train 1.3266e-01 | Test 1.8637e-01 | SO3(train/test) 3.63e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.92e-03 | 14.1s
Epoch   38 | Step   760/ 5000 | Train 2.5964e-01 | Test 1.3202e-01 | SO3(train/test) 3.61e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.91e-03 | 14.2s
Epoch   39 | Step   780/ 5000 | Train 2.2780e-01 | Test 1.6660e-01 | SO3(train/test) 3.65e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.90e-03 | 14.1s
Epoch   40 | Step   800/ 5000 | Train 2.0378e-01 | Test 2.8349e-01 | SO3(train/test) 3.64e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.89e-03 | 14.2s
Epoch   41 | Step   820/ 5000 | Train 2.6578e-01 | Test 2.3285e-01 | SO3(train/test) 3.67e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.88e-03 | 14.2s
Epoch   42 | Step   840/ 5000 | Train 2.7115e-01 | Test 6.8240e-01 | SO3(train/test) 3.66e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.87e-03 | 14.1s
Epoch   43 | Step   860/ 5000 | Train 7.0946e-01 | Test 3.8102e-01 | SO3(train/test) 3.64e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.86e-03 | 14.2s
Epoch   44 | Step   880/ 5000 | Train 3.3360e-01 | Test 2.6257e-01 | SO3(train/test) 3.67e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.84e-03 | 14.1s
Epoch   45 | Step   900/ 5000 | Train 3.7273e-01 | Test 2.2288e-01 | SO3(train/test) 3.66e-07/1.13e-07 | Fail(train/test) 0/0 | LR 5.83e-03 | 14.0s
Epoch   46 | Step   920/ 5000 | Train 2.8752e-01 | Test 3.0119e-01 | SO3(train/test) 3.66e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.82e-03 | 14.2s
Epoch   47 | Step   940/ 5000 | Train 3.7066e-01 | Test 3.2902e-01 | SO3(train/test) 3.67e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.80e-03 | 14.2s
Epoch   48 | Step   960/ 5000 | Train 2.2820e-01 | Test 1.7467e-01 | SO3(train/test) 3.66e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.79e-03 | 14.2s
Epoch   49 | Step   980/ 5000 | Train 2.7854e-01 | Test 2.5863e-01 | SO3(train/test) 3.64e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.77e-03 | 14.3s
Epoch   50 | Step  1000/ 5000 | Train 2.2430e-01 | Test 1.5661e-01 | SO3(train/test) 3.63e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.76e-03 | 14.2s
Epoch   51 | Step  1020/ 5000 | Train 1.6823e-01 | Test 1.2687e-01 | SO3(train/test) 3.64e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.74e-03 | 14.2s
Epoch   52 | Step  1040/ 5000 | Train 2.7860e-01 | Test 2.0906e-01 | SO3(train/test) 3.62e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.72e-03 | 14.1s
Epoch   53 | Step  1060/ 5000 | Train 2.0708e-01 | Test 1.5070e-01 | SO3(train/test) 3.67e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.71e-03 | 14.1s
Epoch   54 | Step  1080/ 5000 | Train 1.7358e-01 | Test 1.9489e-01 | SO3(train/test) 3.67e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.69e-03 | 14.1s
Epoch   55 | Step  1100/ 5000 | Train 1.3078e-01 | Test 9.4321e-02 | SO3(train/test) 3.64e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.67e-03 | 14.1s
Epoch   56 | Step  1120/ 5000 | Train 1.2749e-01 | Test 9.5283e-02 | SO3(train/test) 3.66e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.65e-03 | 14.3s
Epoch   57 | Step  1140/ 5000 | Train 1.4505e-01 | Test 1.2017e-01 | SO3(train/test) 3.66e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.63e-03 | 14.3s
Epoch   58 | Step  1160/ 5000 | Train 1.0688e-01 | Test 1.0442e-01 | SO3(train/test) 3.66e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.61e-03 | 14.2s
Epoch   59 | Step  1180/ 5000 | Train 9.5785e-02 | Test 1.0420e-01 | SO3(train/test) 3.65e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.59e-03 | 14.2s
Epoch   60 | Step  1200/ 5000 | Train 8.5484e-02 | Test 8.2414e-02 | SO3(train/test) 3.70e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.57e-03 | 14.3s
Epoch   61 | Step  1220/ 5000 | Train 7.0754e-02 | Test 5.9769e-02 | SO3(train/test) 3.66e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.55e-03 | 14.2s
Epoch   62 | Step  1240/ 5000 | Train 6.7892e-02 | Test 6.9212e-02 | SO3(train/test) 3.67e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.53e-03 | 14.2s
Epoch   63 | Step  1260/ 5000 | Train 8.6133e-02 | Test 1.5300e-01 | SO3(train/test) 3.67e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.51e-03 | 14.2s
Epoch   64 | Step  1280/ 5000 | Train 1.1518e-01 | Test 1.1257e-01 | SO3(train/test) 3.66e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.48e-03 | 14.3s
Epoch   65 | Step  1300/ 5000 | Train 7.6691e-02 | Test 6.8544e-02 | SO3(train/test) 3.67e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.46e-03 | 14.2s
Epoch   66 | Step  1320/ 5000 | Train 8.4622e-02 | Test 6.6485e-02 | SO3(train/test) 3.67e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.44e-03 | 14.2s
Epoch   67 | Step  1340/ 5000 | Train 7.3191e-02 | Test 6.1358e-02 | SO3(train/test) 3.66e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.41e-03 | 14.1s
Epoch   68 | Step  1360/ 5000 | Train 7.2021e-02 | Test 5.2429e-02 | SO3(train/test) 3.68e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.39e-03 | 14.0s
Epoch   69 | Step  1380/ 5000 | Train 6.6738e-02 | Test 6.7856e-02 | SO3(train/test) 3.66e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.36e-03 | 14.2s
Epoch   70 | Step  1400/ 5000 | Train 5.9291e-02 | Test 4.8856e-02 | SO3(train/test) 3.66e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.34e-03 | 14.2s
Epoch   71 | Step  1420/ 5000 | Train 5.7705e-02 | Test 4.4316e-02 | SO3(train/test) 3.67e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.31e-03 | 14.3s
Epoch   72 | Step  1440/ 5000 | Train 7.1612e-02 | Test 8.2551e-02 | SO3(train/test) 3.68e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.29e-03 | 14.1s
Epoch   73 | Step  1460/ 5000 | Train 6.6735e-02 | Test 4.1043e-02 | SO3(train/test) 3.65e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.26e-03 | 14.1s
Epoch   74 | Step  1480/ 5000 | Train 4.3561e-02 | Test 3.1447e-02 | SO3(train/test) 3.67e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.23e-03 | 14.1s
Epoch   75 | Step  1500/ 5000 | Train 7.4055e-02 | Test 4.0186e-02 | SO3(train/test) 3.67e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.21e-03 | 14.2s
Epoch   76 | Step  1520/ 5000 | Train 5.0969e-02 | Test 3.0055e-02 | SO3(train/test) 3.65e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.18e-03 | 14.2s
Epoch   77 | Step  1540/ 5000 | Train 4.0303e-02 | Test 2.7554e-02 | SO3(train/test) 3.70e-07/1.17e-07 | Fail(train/test) 0/0 | LR 5.15e-03 | 14.2s
Epoch   78 | Step  1560/ 5000 | Train 3.7547e-02 | Test 4.5730e-02 | SO3(train/test) 3.66e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.12e-03 | 14.2s
Epoch   79 | Step  1580/ 5000 | Train 4.0984e-02 | Test 4.9618e-02 | SO3(train/test) 3.66e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.09e-03 | 14.2s
Epoch   80 | Step  1600/ 5000 | Train 3.9942e-02 | Test 4.8007e-02 | SO3(train/test) 3.67e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.06e-03 | 14.2s
Epoch   81 | Step  1620/ 5000 | Train 6.3358e-02 | Test 4.4859e-02 | SO3(train/test) 3.67e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.03e-03 | 14.3s
Epoch   82 | Step  1640/ 5000 | Train 3.5845e-02 | Test 1.9642e-02 | SO3(train/test) 3.68e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.00e-03 | 14.2s
Epoch   83 | Step  1660/ 5000 | Train 3.7867e-02 | Test 5.3971e-02 | SO3(train/test) 3.67e-07/1.17e-07 | Fail(train/test) 0/0 | LR 4.97e-03 | 14.2s
Epoch   84 | Step  1680/ 5000 | Train 4.0914e-02 | Test 2.1073e-02 | SO3(train/test) 3.66e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.94e-03 | 14.2s
Epoch   85 | Step  1700/ 5000 | Train 2.7875e-02 | Test 1.9776e-02 | SO3(train/test) 3.67e-07/1.17e-07 | Fail(train/test) 0/0 | LR 4.91e-03 | 14.3s
Epoch   86 | Step  1720/ 5000 | Train 2.6285e-02 | Test 3.0577e-02 | SO3(train/test) 3.66e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.88e-03 | 14.3s
Epoch   87 | Step  1740/ 5000 | Train 3.2868e-02 | Test 2.2699e-02 | SO3(train/test) 3.67e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.85e-03 | 14.1s
Epoch   88 | Step  1760/ 5000 | Train 2.9602e-02 | Test 1.6997e-02 | SO3(train/test) 3.67e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.82e-03 | 14.2s
Epoch   89 | Step  1780/ 5000 | Train 3.4229e-02 | Test 3.1391e-02 | SO3(train/test) 3.67e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.78e-03 | 14.1s
Epoch   90 | Step  1800/ 5000 | Train 3.3147e-02 | Test 1.7785e-02 | SO3(train/test) 3.67e-07/1.17e-07 | Fail(train/test) 0/0 | LR 4.75e-03 | 14.2s
Epoch   91 | Step  1820/ 5000 | Train 2.8292e-02 | Test 1.7534e-02 | SO3(train/test) 3.66e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.72e-03 | 14.3s
Epoch   92 | Step  1840/ 5000 | Train 3.0569e-02 | Test 1.1235e-02 | SO3(train/test) 3.67e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.68e-03 | 14.1s

In [ ]:
# 第二次修改 14s -> 6s
os.environ["MODE"] = "smoke1_train_v4lite_resume"
!bash scripts/run_phase1a_oc_v4lite.sh

[phase1a]
MODE=smoke1_train_v4lite_resume
RUN_TAG=phase1a_oc_v4lite_cleanrun_v1
DATASET=/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/data/auv_oc_traj1000_blk150_s23_d0be9434.pkl
DEVICE=cuda
PHASE1A_MODELS=phnode_full ablate_no_mass_prior ablate_no_lift
SMOKE1_MODELS=phnode_full
SMOKE_SEEDS=42 44 46
DECISION_SEEDS=42 43 44 45 46
NOISE_REFERENCE=remus100_dr
PHASE1A_LOG_DIR=/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/phase1a_logs/phase1a_oc_v4lite_cleanrun_v1
PHASE1A_METADATA_DIR=/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/phase1a_metadata_phase1a_oc_v4lite_cleanrun_v1
[resume-train] suite=sweep_oc_phase1a_smoke1_v4lite_phase1a_oc_v4lite_cleanrun_v1 models=phnode_full seeds=42 44 46 protocol=v4_lite
Training all models with profile-based noisy IC.
Dataset: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/data/auv_oc_traj1000_blk150_s23_d0be9434.pkl
Group: all
Explicit models: phnode_full
Seeds: 42 44 46
Noise config: protocol=v4_lite, profile=nominal_train, scale=1.0, warmup=20, ramp=80, mix_ratio=0.5
Auto-eval profiles: block=[clean nominal_eval heading_biased_eval] heldout=[clean nominal_eval degraded_eval heading_biased_eval]
Suite directory: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke1_v4lite_phase1a_oc_v4lite_cleanrun_v1
Dataset: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/data/auv_oc_traj1000_blk150_s23_d0be9434.pkl
Models (1): phnode_full
Seeds: 42 44 46
[train] main_phnode_full_seed42
Loading dataset...
Loaded: 83850 train, 21000 test, t_eval=[0.   0.05 0.1  0.15 0.2 ]
Dataset split: trajectory | train trajectories: 559 | test trajectories: 140
Dataset ID: d0be9434
Dataset path: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_5/data/auv_oc_traj1000_blk150_s23_d0be9434.pkl | velocity convention: body_total | state dim: 27
Position std: [0.1508, 0.1400, 0.0370]
Velocity std: u=0.4722, v=0.0898, w=0.0718, p=0.0248, q=0.0906, r=0.0526
Actuator std: a0=0.1543, a1=0.1555, a2=299.0037
Training noise budget: protocol=v4_lite | profile=nominal_train | ref=remus100_dr | traj_corr=0.850 | epoch_scale=1.000 | mix_ratio=0.500 | nu_r_lin_floor[u=0.0020, v=0.0020, w=0.0030] | nu_r_lin_ratio[u=0.0020, v=0.0020, w=0.0020] | nu_r_ang[p=0.0006, q=0.0006, r=0.0010] | rot[roll=0.0015, pitch=0.0015, yaw=0.0060]
Model: pH NODE Full [main/core] | canonical type: phnode_full
Model parameters: 62,803
Training dataset: id=d0be9434 | path=/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_5/data/auv_oc_traj1000_blk150_s23_d0be9434.pkl
Mass matrix initialized from physics
Training: epochs<=300, target_steps=5000, warmup_steps=400, lr=6.00e-03 -> 1.00e-04, solver=rk4, so3_reg=1.00e-03
Train samples: 83850, Test samples: 21000
Epoch    1 | Step    20/ 5000 | Train 4.3508e+00 | Test 5.0458e+00 | SO3(train/test) 1.26e-07/1.27e-07 | Fail(train/test) 0/0 | LR 4.10e-04 | 8.4s
Epoch    2 | Step    40/ 5000 | Train 3.5849e+00 | Test 4.3046e+00 | SO3(train/test) 1.19e-07/1.20e-07 | Fail(train/test) 0/0 | LR 7.05e-04 | 6.1s
Epoch    3 | Step    60/ 5000 | Train 2.9504e+00 | Test 3.2210e+00 | SO3(train/test) 1.16e-07/1.16e-07 | Fail(train/test) 0/0 | LR 1.00e-03 | 6.0s
Epoch    4 | Step    80/ 5000 | Train 1.7819e+00 | Test 1.0436e+00 | SO3(train/test) 1.20e-07/1.49e-07 | Fail(train/test) 0/0 | LR 1.29e-03 | 6.0s
Epoch    5 | Step   100/ 5000 | Train 7.7154e-01 | Test 6.1857e-01 | SO3(train/test) 1.29e-07/1.15e-07 | Fail(train/test) 0/0 | LR 1.59e-03 | 5.9s
Epoch    6 | Step   120/ 5000 | Train 7.3271e-01 | Test 7.2985e-01 | SO3(train/test) 1.15e-07/1.16e-07 | Fail(train/test) 0/0 | LR 1.88e-03 | 6.1s
Epoch    7 | Step   140/ 5000 | Train 7.3189e-01 | Test 7.0204e-01 | SO3(train/test) 1.19e-07/1.23e-07 | Fail(train/test) 0/0 | LR 2.18e-03 | 6.0s
Epoch    8 | Step   160/ 5000 | Train 9.1646e-01 | Test 1.3657e+00 | SO3(train/test) 1.88e-07/4.19e-07 | Fail(train/test) 0/0 | LR 2.47e-03 | 6.1s
Epoch    9 | Step   180/ 5000 | Train 6.4671e-01 | Test 4.2992e-01 | SO3(train/test) 2.93e-07/1.80e-07 | Fail(train/test) 0/0 | LR 2.77e-03 | 5.9s
Epoch   10 | Step   200/ 5000 | Train 4.0102e-01 | Test 3.2272e-01 | SO3(train/test) 1.32e-07/1.17e-07 | Fail(train/test) 0/0 | LR 3.06e-03 | 6.1s
Epoch   11 | Step   220/ 5000 | Train 5.4610e-01 | Test 7.6371e-01 | SO3(train/test) 1.17e-07/1.29e-07 | Fail(train/test) 0/0 | LR 3.36e-03 | 6.0s
Epoch   12 | Step   240/ 5000 | Train 6.8852e-01 | Test 1.3301e+00 | SO3(train/test) 1.22e-07/1.23e-07 | Fail(train/test) 0/0 | LR 3.65e-03 | 5.9s
Epoch   13 | Step   260/ 5000 | Train 9.8837e-01 | Test 1.7049e+00 | SO3(train/test) 1.39e-07/1.64e-07 | Fail(train/test) 0/0 | LR 3.95e-03 | 5.9s
Epoch   14 | Step   280/ 5000 | Train 1.2011e+00 | Test 1.1263e+00 | SO3(train/test) 6.34e-07/9.02e-07 | Fail(train/test) 0/0 | LR 4.24e-03 | 5.9s
Epoch   15 | Step   300/ 5000 | Train 7.0657e-01 | Test 4.1899e-01 | SO3(train/test) 2.46e-07/2.21e-07 | Fail(train/test) 0/0 | LR 4.54e-03 | 5.9s
Epoch   16 | Step   320/ 5000 | Train 3.6999e-01 | Test 4.1457e-01 | SO3(train/test) 1.52e-07/1.28e-07 | Fail(train/test) 0/0 | LR 4.83e-03 | 6.1s
Epoch   17 | Step   340/ 5000 | Train 8.2631e-01 | Test 1.2798e+02 | SO3(train/test) 4.09e-07/2.30e-04 | Fail(train/test) 0/0 | LR 5.13e-03 | 5.9s
Epoch   18 | Step   360/ 5000 | Train 9.8227e+00 | Test 1.6472e+00 | SO3(train/test) 1.36e-05/1.22e-07 | Fail(train/test) 0/0 | LR 5.42e-03 | 5.9s
Epoch   19 | Step   380/ 5000 | Train 9.0113e-01 | Test 1.5542e+00 | SO3(train/test) 1.21e-07/1.32e-07 | Fail(train/test) 0/0 | LR 5.72e-03 | 6.0s
Epoch   20 | Step   400/ 5000 | Train 6.4581e-01 | Test 4.2124e-01 | SO3(train/test) 1.17e-07/1.13e-07 | Fail(train/test) 0/0 | LR 6.00e-03 | 6.0s
Epoch   21 | Step   420/ 5000 | Train 5.4998e-01 | Test 2.3077e-01 | SO3(train/test) 3.60e-07/1.13e-07 | Fail(train/test) 0/0 | LR 6.00e-03 | 6.5s
Epoch   22 | Step   440/ 5000 | Train 8.2871e-01 | Test 2.7328e-01 | SO3(train/test) 3.64e-07/1.17e-07 | Fail(train/test) 0/0 | LR 6.00e-03 | 6.1s
Epoch   23 | Step   460/ 5000 | Train 4.5338e-01 | Test 3.4917e-01 | SO3(train/test) 3.61e-07/1.14e-07 | Fail(train/test) 0/0 | LR 6.00e-03 | 6.1s
Epoch   24 | Step   480/ 5000 | Train 4.0651e-01 | Test 4.1397e-01 | SO3(train/test) 3.61e-07/1.15e-07 | Fail(train/test) 0/0 | LR 6.00e-03 | 6.1s
Epoch   25 | Step   500/ 5000 | Train 4.3632e-01 | Test 7.8484e-01 | SO3(train/test) 3.63e-07/1.19e-07 | Fail(train/test) 0/0 | LR 5.99e-03 | 6.2s
Epoch   26 | Step   520/ 5000 | Train 7.7869e-01 | Test 1.7955e+00 | SO3(train/test) 3.66e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.99e-03 | 6.2s
Epoch   27 | Step   540/ 5000 | Train 1.2849e+00 | Test 1.0552e+00 | SO3(train/test) 3.69e-07/1.42e-07 | Fail(train/test) 0/0 | LR 5.99e-03 | 6.1s
Epoch   28 | Step   560/ 5000 | Train 6.5556e-01 | Test 8.1655e-01 | SO3(train/test) 3.72e-07/1.20e-07 | Fail(train/test) 0/0 | LR 5.98e-03 | 6.0s
Epoch   29 | Step   580/ 5000 | Train 5.0356e-01 | Test 2.9720e-01 | SO3(train/test) 3.66e-07/1.13e-07 | Fail(train/test) 0/0 | LR 5.98e-03 | 6.2s
Epoch   30 | Step   600/ 5000 | Train 5.6350e-01 | Test 6.3345e-01 | SO3(train/test) 3.63e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.97e-03 | 6.1s
Epoch   31 | Step   620/ 5000 | Train 4.5132e-01 | Test 5.2722e-01 | SO3(train/test) 3.61e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.97e-03 | 6.2s
Epoch   32 | Step   640/ 5000 | Train 4.0925e-01 | Test 3.4316e-01 | SO3(train/test) 3.63e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.96e-03 | 6.1s
Epoch   33 | Step   660/ 5000 | Train 4.7154e-01 | Test 5.1739e-01 | SO3(train/test) 3.64e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.95e-03 | 6.0s
Epoch   34 | Step   680/ 5000 | Train 4.7104e-01 | Test 7.4365e-01 | SO3(train/test) 3.63e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.95e-03 | 6.0s
Epoch   35 | Step   700/ 5000 | Train 6.5806e-01 | Test 4.9778e-01 | SO3(train/test) 3.69e-07/1.43e-07 | Fail(train/test) 0/0 | LR 5.94e-03 | 6.1s
Epoch   36 | Step   720/ 5000 | Train 5.0248e-01 | Test 2.8191e-01 | SO3(train/test) 3.66e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.93e-03 | 6.2s
Epoch   37 | Step   740/ 5000 | Train 3.6621e-01 | Test 2.9994e-01 | SO3(train/test) 3.63e-07/1.13e-07 | Fail(train/test) 0/0 | LR 5.92e-03 | 6.1s
Epoch   38 | Step   760/ 5000 | Train 2.5579e-01 | Test 2.5104e-01 | SO3(train/test) 3.62e-07/1.13e-07 | Fail(train/test) 0/0 | LR 5.91e-03 | 6.0s
Epoch   39 | Step   780/ 5000 | Train 1.9982e-01 | Test 1.8614e-01 | SO3(train/test) 3.62e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.90e-03 | 6.1s
Epoch   40 | Step   800/ 5000 | Train 1.7382e-01 | Test 1.7619e-01 | SO3(train/test) 3.65e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.89e-03 | 6.1s
Epoch   41 | Step   820/ 5000 | Train 2.5920e-01 | Test 1.9710e-01 | SO3(train/test) 3.65e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.88e-03 | 6.2s
Epoch   42 | Step   840/ 5000 | Train 2.2278e-01 | Test 1.6260e-01 | SO3(train/test) 3.63e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.87e-03 | 6.1s
Epoch   43 | Step   860/ 5000 | Train 1.7692e-01 | Test 1.2393e-01 | SO3(train/test) 3.63e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.86e-03 | 6.0s
Epoch   44 | Step   880/ 5000 | Train 2.4520e-01 | Test 2.0983e-01 | SO3(train/test) 3.66e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.84e-03 | 6.1s
Epoch   45 | Step   900/ 5000 | Train 1.6078e-01 | Test 2.1507e-01 | SO3(train/test) 3.65e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.83e-03 | 6.1s
Epoch   46 | Step   920/ 5000 | Train 1.8602e-01 | Test 1.2231e-01 | SO3(train/test) 3.66e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.82e-03 | 6.2s
Epoch   47 | Step   940/ 5000 | Train 3.8912e-01 | Test 2.7950e-01 | SO3(train/test) 3.68e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.80e-03 | 6.0s
Epoch   48 | Step   960/ 5000 | Train 2.4122e-01 | Test 2.1240e-01 | SO3(train/test) 3.67e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.79e-03 | 6.1s
Epoch   49 | Step   980/ 5000 | Train 1.6161e-01 | Test 1.2058e-01 | SO3(train/test) 3.64e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.77e-03 | 6.1s
Epoch   50 | Step  1000/ 5000 | Train 3.2958e-01 | Test 2.2353e-01 | SO3(train/test) 3.65e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.76e-03 | 6.1s
Epoch   51 | Step  1020/ 5000 | Train 1.5441e-01 | Test 1.0190e-01 | SO3(train/test) 3.66e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.74e-03 | 6.1s
Epoch   52 | Step  1040/ 5000 | Train 1.0963e-01 | Test 1.0785e-01 | SO3(train/test) 3.64e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.72e-03 | 6.0s
Epoch   53 | Step  1060/ 5000 | Train 2.2096e-01 | Test 3.7104e-01 | SO3(train/test) 3.68e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.71e-03 | 6.1s
Epoch   54 | Step  1080/ 5000 | Train 2.2093e-01 | Test 1.3305e-01 | SO3(train/test) 3.66e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.69e-03 | 6.0s
Epoch   55 | Step  1100/ 5000 | Train 1.5369e-01 | Test 1.2403e-01 | SO3(train/test) 3.65e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.67e-03 | 6.1s
Epoch   56 | Step  1120/ 5000 | Train 1.7175e-01 | Test 2.4580e-01 | SO3(train/test) 3.65e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.65e-03 | 6.2s
Epoch   57 | Step  1140/ 5000 | Train 1.6227e-01 | Test 9.6511e-02 | SO3(train/test) 3.66e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.63e-03 | 6.1s
Epoch   58 | Step  1160/ 5000 | Train 1.7257e-01 | Test 1.2665e-01 | SO3(train/test) 3.65e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.61e-03 | 6.1s
Epoch   59 | Step  1180/ 5000 | Train 1.3019e-01 | Test 1.4640e-01 | SO3(train/test) 3.66e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.59e-03 | 6.0s
Epoch   60 | Step  1200/ 5000 | Train 1.6311e-01 | Test 1.2595e-01 | SO3(train/test) 3.68e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.57e-03 | 6.0s
Epoch   61 | Step  1220/ 5000 | Train 1.1038e-01 | Test 8.1425e-02 | SO3(train/test) 3.65e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.55e-03 | 6.1s
Epoch   62 | Step  1240/ 5000 | Train 7.9397e-02 | Test 6.3714e-02 | SO3(train/test) 3.67e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.53e-03 | 6.1s
Epoch   63 | Step  1260/ 5000 | Train 8.3515e-02 | Test 7.2987e-02 | SO3(train/test) 3.67e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.51e-03 | 6.1s
Epoch   64 | Step  1280/ 5000 | Train 1.0836e-01 | Test 1.0189e-01 | SO3(train/test) 3.65e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.48e-03 | 6.1s
Epoch   65 | Step  1300/ 5000 | Train 1.0934e-01 | Test 6.7517e-02 | SO3(train/test) 3.66e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.46e-03 | 6.0s
Epoch   66 | Step  1320/ 5000 | Train 7.4161e-02 | Test 7.7306e-02 | SO3(train/test) 3.67e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.44e-03 | 6.2s
Epoch   67 | Step  1340/ 5000 | Train 8.0209e-02 | Test 6.3925e-02 | SO3(train/test) 3.66e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.41e-03 | 6.1s
Epoch   68 | Step  1360/ 5000 | Train 6.8955e-02 | Test 5.7937e-02 | SO3(train/test) 3.68e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.39e-03 | 6.1s
Epoch   69 | Step  1380/ 5000 | Train 6.1091e-02 | Test 5.5698e-02 | SO3(train/test) 3.69e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.36e-03 | 6.2s
Epoch   70 | Step  1400/ 5000 | Train 6.2309e-02 | Test 5.1138e-02 | SO3(train/test) 3.64e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.34e-03 | 6.1s
Epoch   71 | Step  1420/ 5000 | Train 6.1412e-02 | Test 4.9734e-02 | SO3(train/test) 3.68e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.31e-03 | 6.2s
Epoch   72 | Step  1440/ 5000 | Train 6.7393e-02 | Test 6.5683e-02 | SO3(train/test) 3.65e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.29e-03 | 6.1s
Epoch   73 | Step  1460/ 5000 | Train 6.8600e-02 | Test 6.7712e-02 | SO3(train/test) 3.64e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.26e-03 | 6.0s
Epoch   74 | Step  1480/ 5000 | Train 6.9848e-02 | Test 6.4141e-02 | SO3(train/test) 3.68e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.23e-03 | 6.1s
Epoch   75 | Step  1500/ 5000 | Train 6.4146e-02 | Test 6.1411e-02 | SO3(train/test) 3.67e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.21e-03 | 6.1s
Epoch   76 | Step  1520/ 5000 | Train 5.5662e-02 | Test 5.8395e-02 | SO3(train/test) 3.66e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.18e-03 | 6.2s
Epoch   77 | Step  1540/ 5000 | Train 6.2822e-02 | Test 4.8755e-02 | SO3(train/test) 3.68e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.15e-03 | 6.1s
Epoch   78 | Step  1560/ 5000 | Train 5.7612e-02 | Test 4.0283e-02 | SO3(train/test) 3.65e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.12e-03 | 6.1s
Epoch   79 | Step  1580/ 5000 | Train 5.0116e-02 | Test 3.5000e-02 | SO3(train/test) 3.65e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.09e-03 | 6.1s
Epoch   80 | Step  1600/ 5000 | Train 4.2641e-02 | Test 3.3641e-02 | SO3(train/test) 3.68e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.06e-03 | 6.2s
Epoch   81 | Step  1620/ 5000 | Train 4.1371e-02 | Test 4.0465e-02 | SO3(train/test) 3.65e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.03e-03 | 6.2s
Epoch   82 | Step  1640/ 5000 | Train 3.7730e-02 | Test 2.5034e-02 | SO3(train/test) 3.68e-07/1.17e-07 | Fail(train/test) 0/0 | LR 5.00e-03 | 6.0s
Epoch   83 | Step  1660/ 5000 | Train 3.7482e-02 | Test 3.2633e-02 | SO3(train/test) 3.69e-07/1.17e-07 | Fail(train/test) 0/0 | LR 4.97e-03 | 6.0s
Epoch   84 | Step  1680/ 5000 | Train 5.0225e-02 | Test 5.1099e-02 | SO3(train/test) 3.65e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.94e-03 | 6.1s
Epoch   85 | Step  1700/ 5000 | Train 5.4171e-02 | Test 4.8086e-02 | SO3(train/test) 3.66e-07/1.17e-07 | Fail(train/test) 0/0 | LR 4.91e-03 | 6.1s
Epoch   86 | Step  1720/ 5000 | Train 4.0691e-02 | Test 2.1460e-02 | SO3(train/test) 3.70e-07/1.17e-07 | Fail(train/test) 0/0 | LR 4.88e-03 | 6.2s
Epoch   87 | Step  1740/ 5000 | Train 3.6061e-02 | Test 5.9068e-02 | SO3(train/test) 3.68e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.85e-03 | 6.1s
Epoch   88 | Step  1760/ 5000 | Train 3.8396e-02 | Test 1.0335e-01 | SO3(train/test) 3.68e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.82e-03 | 6.1s
Epoch   89 | Step  1780/ 5000 | Train 6.8605e-02 | Test 5.8698e-02 | SO3(train/test) 3.67e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.78e-03 | 6.1s
Epoch   90 | Step  1800/ 5000 | Train 4.7217e-02 | Test 3.2852e-02 | SO3(train/test) 3.66e-07/1.17e-07 | Fail(train/test) 0/0 | LR 4.75e-03 | 6.1s
Epoch   91 | Step  1820/ 5000 | Train 6.0844e-02 | Test 5.6515e-02 | SO3(train/test) 3.65e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.72e-03 | 6.3s
Epoch   92 | Step  1840/ 5000 | Train 3.8857e-02 | Test 2.2842e-02 | SO3(train/test) 3.67e-07/1.17e-07 | Fail(train/test) 0/0 | LR 4.68e-03 | 6.1s
Epoch   93 | Step  1860/ 5000 | Train 3.3102e-02 | Test 3.1666e-02 | SO3(train/test) 3.67e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.65e-03 | 6.1s
Epoch   94 | Step  1880/ 5000 | Train 3.8514e-02 | Test 2.1312e-02 | SO3(train/test) 3.66e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.62e-03 | 6.1s
Epoch   95 | Step  1900/ 5000 | Train 3.6244e-02 | Test 3.4896e-02 | SO3(train/test) 3.69e-07/1.17e-07 | Fail(train/test) 0/0 | LR 4.58e-03 | 6.1s
Epoch   96 | Step  1920/ 5000 | Train 3.7236e-02 | Test 2.4416e-02 | SO3(train/test) 3.64e-07/1.17e-07 | Fail(train/test) 0/0 | LR 4.55e-03 | 6.2s
Epoch   97 | Step  1940/ 5000 | Train 3.3331e-02 | Test 2.2420e-02 | SO3(train/test) 3.69e-07/1.17e-07 | Fail(train/test) 0/0 | LR 4.51e-03 | 6.1s
Epoch   98 | Step  1960/ 5000 | Train 4.9974e-02 | Test 2.0668e-02 | SO3(train/test) 3.67e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.48e-03 | 6.1s
Epoch   99 | Step  1980/ 5000 | Train 3.4382e-02 | Test 1.6104e-02 | SO3(train/test) 3.68e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.44e-03 | 6.1s
Epoch  100 | Step  2000/ 5000 | Train 3.1282e-02 | Test 2.0142e-02 | SO3(train/test) 3.66e-07/1.17e-07 | Fail(train/test) 0/0 | LR 4.41e-03 | 6.1s
Epoch  101 | Step  2020/ 5000 | Train 3.0292e-02 | Test 1.5747e-02 | SO3(train/test) 3.68e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.37e-03 | 6.3s
Epoch  102 | Step  2040/ 5000 | Train 3.3426e-02 | Test 3.9984e-02 | SO3(train/test) 3.67e-07/1.17e-07 | Fail(train/test) 0/0 | LR 4.33e-03 | 6.1s
Epoch  103 | Step  2060/ 5000 | Train 3.4929e-02 | Test 1.5439e-02 | SO3(train/test) 3.70e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.30e-03 | 6.1s
Epoch  104 | Step  2080/ 5000 | Train 2.8925e-02 | Test 3.3167e-02 | SO3(train/test) 3.70e-07/1.17e-07 | Fail(train/test) 0/0 | LR 4.26e-03 | 6.1s
Epoch  105 | Step  2100/ 5000 | Train 3.1063e-02 | Test 1.1918e-02 | SO3(train/test) 3.69e-07/1.17e-07 | Fail(train/test) 0/0 | LR 4.22e-03 | 6.1s
Epoch  106 | Step  2120/ 5000 | Train 2.9285e-02 | Test 1.4373e-02 | SO3(train/test) 3.67e-07/1.17e-07 | Fail(train/test) 0/0 | LR 4.19e-03 | 6.3s
Epoch  107 | Step  2140/ 5000 | Train 3.5073e-02 | Test 1.6621e-02 | SO3(train/test) 3.67e-07/1.17e-07 | Fail(train/test) 0/0 | LR 4.15e-03 | 6.1s
Epoch  108 | Step  2160/ 5000 | Train 3.0662e-02 | Test 2.6630e-02 | SO3(train/test) 3.68e-07/1.17e-07 | Fail(train/test) 0/0 | LR 4.11e-03 | 6.1s
Epoch  109 | Step  2180/ 5000 | Train 3.1310e-02 | Test 2.0798e-02 | SO3(train/test) 3.67e-07/1.17e-07 | Fail(train/test) 0/0 | LR 4.08e-03 | 6.1s
Epoch  110 | Step  2200/ 5000 | Train 2.7668e-02 | Test 1.3247e-02 | SO3(train/test) 3.66e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.04e-03 | 6.1s
Epoch  111 | Step  2220/ 5000 | Train 2.8560e-02 | Test 2.1069e-02 | SO3(train/test) 3.68e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.00e-03 | 6.4s
Epoch  112 | Step  2240/ 5000 | Train 2.8622e-02 | Test 1.3171e-02 | SO3(train/test) 3.67e-07/1.16e-07 | Fail(train/test) 0/0 | LR 3.96e-03 | 6.2s
Epoch  113 | Step  2260/ 5000 | Train 2.7320e-02 | Test 1.3839e-02 | SO3(train/test) 3.69e-07/1.16e-07 | Fail(train/test) 0/0 | LR 3.92e-03 | 6.2s
Epoch  114 | Step  2280/ 5000 | Train 2.5918e-02 | Test 1.1061e-02 | SO3(train/test) 3.68e-07/1.16e-07 | Fail(train/test) 0/0 | LR 3.88e-03 | 6.1s
Epoch  115 | Step  2300/ 5000 | Train 3.0988e-02 | Test 1.4019e-02 | SO3(train/test) 3.68e-07/1.17e-07 | Fail(train/test) 0/0 | LR 3.85e-03 | 6.1s
Epoch  116 | Step  2320/ 5000 | Train 2.6604e-02 | Test 1.2225e-02 | SO3(train/test) 3.69e-07/1.17e-07 | Fail(train/test) 0/0 | LR 3.81e-03 | 6.3s
Epoch  117 | Step  2340/ 5000 | Train 2.7528e-02 | Test 1.4849e-02 | SO3(train/test) 3.67e-07/1.17e-07 | Fail(train/test) 0/0 | LR 3.77e-03 | 6.1s

## 3. Smoke-1 rollout eval + local proxy

使用小 rollout 数检查 eval、summary 和 report 路径。Smoke 只验证流程，不写研究结论。

In [ ]:
os.environ["MODE"] = "smoke1_eval"
!bash scripts/run_phase1a_oc_v4lite.sh

[phase1a]
MODE=smoke1_eval
RUN_TAG=phase1a_oc_v4lite_cleanrun_v1
DATASET=/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/data/auv_oc_traj1000_blk150_s23_d0be9434.pkl
DEVICE=cuda
PHASE1A_MODELS=phnode_full ablate_no_mass_prior ablate_no_lift
SMOKE1_MODELS=phnode_full
SMOKE_SEEDS=42 44 46
DECISION_SEEDS=42 43 44 45 46
NOISE_REFERENCE=remus100_dr
PHASE1A_LOG_DIR=/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/phase1a_logs/phase1a_oc_v4lite_cleanrun_v1
PHASE1A_METADATA_DIR=/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/phase1a_metadata_phase1a_oc_v4lite_cleanrun_v1
[eval] suite=sweep_oc_phase1a_smoke1_clean_phase1a_oc_v4lite_cleanrun_v1 eval_protocol=iid_noisy_ic profiles=clean nominal_eval
Suite directory: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke1_clean_phase1a_oc_v4lite_cleanrun_v1
Manifest: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke1_clean_phase1a_oc_v4lite_cleanrun_v1/runs.tsv
Mode: resampled
[eval] main_phnode_full_seed42
Starting rollout benchmark | checkpoint=/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke1_clean_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed42/best_model.pt | device=cuda | mode=resampled | noise_profile=clean | noise_protocol=clean | noise_budget=protocol=clean | profile=clean | ref=remus100_dr | epoch_scale=0.000 | mix_ratio=0.000 | nu_r_lin_floor[u=0.0000, v=0.0000, w=0.0000] | nu_r_lin_ratio[u=0.0000, v=0.0000, w=0.0000] | nu_r_ang[p=0.0000, q=0.0000, r=0.0000] | rot[roll=0.0000, pitch=0.0000, yaw=0.0000] | scenarios=PRBS,CHIRP,OU | trajectories=18 | max_horizon=60.0s | output_dir=/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke1_clean_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed42/rollout_benchmark/phase1a_iideval_traj6_seed42_20260425_024815/clean
[scenario 1/3] PRBS | 6 trajectories
[1/18] PRBS seed=42 done | reason=completed | sim_time=60.00s | eta=16m46.0s
[5/18] PRBS seed=46 done | reason=completed | sim_time=60.00s | eta=2m33.9s
[6/18] PRBS seed=47 done | reason=completed | sim_time=60.00s | eta=1m58.4s
[scenario done] PRBS | completed=6/6 | gt_div=0 | model_fail=0 | H=60.0s cond_n=6/6 | pos_med=0.5238 m | pos_p95=1.6701 m | rot_med=0.0134 rad | completion=1.000 | elapsed=59.2s
[scenario 2/3] CHIRP | 6 trajectories
[7/18] CHIRP seed=100042 done | reason=completed | sim_time=60.00s | eta=3m05.4s
[11/18] CHIRP seed=100046 done | reason=completed | sim_time=60.00s | eta=1m15.1s
[12/18] CHIRP seed=100047 done | reason=completed | sim_time=60.00s | eta=59.0s
[scenario done] CHIRP | completed=6/6 | gt_div=0 | model_fail=0 | H=60.0s cond_n=6/6 | pos_med=0.8136 m | pos_p95=1.2820 m | rot_med=0.0165 rad | completion=1.000 | elapsed=1m58.0s
[scenario 3/3] OU | 6 trajectories
[13/18] OU seed=200042 done | reason=completed | sim_time=60.00s | eta=1m08.1s
[17/18] OU seed=200046 done | reason=completed | sim_time=60.00s | eta=10.4s
[18/18] OU seed=200047 done | reason=completed | sim_time=60.00s | eta=0.0s
[scenario done] OU | completed=6/6 | gt_div=0 | model_fail=0 | H=60.0s cond_n=6/6 | pos_med=0.5628 m | pos_p95=0.6721 m | rot_med=0.0189 rad | completion=1.000 | elapsed=2m57.0s
Benchmark finished in 3m10.5s
Results written to /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke1_clean_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed42/rollout_benchmark/phase1a_iideval_traj6_seed42_20260425_024815/clean
Rollout Benchmark Summary
================================================================================
Checkpoint: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke1_clean_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed42/best_model.pt
Dataset: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_5/data/auv_oc_traj1000_blk150_s23_d0be9434.pkl
Model: pH NODE Full [main/core]
Canonical model type: phnode_full
Energy semantics: mechanical_energy
Device: cuda
Mode: resampled
Generation config source: checkpoint
Scenarios: PRBS, CHIRP, OU
Trajectories per scenario: 6
Horizons: 10.0, 30.0, 60.0

Overall
--------------------------------------------------------------------------------
Conditional error statistics use only trajectories that completed to the horizon.
Primary KPIs are observable-space fields: position, depth, rotation, and total velocity.
Model-space diagnostics use relative velocity; internal diagnostics cover energy and raw SO(3) quality.
Per-column field grouping is exported in metric_contract.csv.
H=10.0s | pos median=0.0729 m | pos p95=0.1630 m | rot median=0.0059 rad | total vel median=0.0084 m/s | rel vel median=0.0082 m/s | cond_n=18/18 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
H=30.0s | pos median=0.2309 m | pos p95=0.5462 m | rot median=0.0081 rad | total vel median=0.0128 m/s | rel vel median=0.0131 m/s | cond_n=18/18 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
H=60.0s | pos median=0.6208 m | pos p95=1.4648 m | rot median=0.0162 rad | total vel median=0.0122 m/s | rel vel median=0.0125 m/s | cond_n=18/18 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000

Rollout Outcomes To Max Horizon
--------------------------------------------------------------------------------
n=18 | completed=18 (1.000) | gt_divergence=0 (0.000) | pred_divergence=0 (0.000) | solver_failure=0 (0.000) | nan_or_inf=0 (0.000)

By Scenario
--------------------------------------------------------------------------------
PRBS
  n=6 | completed=6 (1.000) | gt_divergence=0 (0.000) | pred_divergence=0 (0.000) | solver_failure=0 (0.000) | nan_or_inf=0 (0.000)
  H=10.0s | pos median=0.0855 m | pos p95=0.1921 m | rot median=0.0058 rad | total vel median=0.0106 m/s | rel vel median=0.0117 m/s | cond_n=6/6 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
  H=30.0s | pos median=0.2614 m | pos p95=0.5563 m | rot median=0.0073 rad | total vel median=0.0226 m/s | rel vel median=0.0225 m/s | cond_n=6/6 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
  H=60.0s | pos median=0.5238 m | pos p95=1.6701 m | rot median=0.0134 rad | total vel median=0.0196 m/s | rel vel median=0.0217 m/s | cond_n=6/6 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000

CHIRP
  n=6 | completed=6 (1.000) | gt_divergence=0 (0.000) | pred_divergence=0 (0.000) | solver_failure=0 (0.000) | nan_or_inf=0 (0.000)
  H=10.0s | pos median=0.0599 m | pos p95=0.0736 m | rot median=0.0062 rad | total vel median=0.0046 m/s | rel vel median=0.0045 m/s | cond_n=6/6 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
  H=30.0s | pos median=0.1304 m | pos p95=0.4148 m | rot median=0.0083 rad | total vel median=0.0031 m/s | rel vel median=0.0035 m/s | cond_n=6/6 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
  H=60.0s | pos median=0.8136 m | pos p95=1.2820 m | rot median=0.0165 rad | total vel median=0.0058 m/s | rel vel median=0.0110 m/s | cond_n=6/6 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000

OU
  n=6 | completed=6 (1.000) | gt_divergence=0 (0.000) | pred_divergence=0 (0.000) | solver_failure=0 (0.000) | nan_or_inf=0 (0.000)
  H=10.0s | pos median=0.1159 m | pos p95=0.1496 m | rot median=0.0088 rad | total vel median=0.0137 m/s | rel vel median=0.0129 m/s | cond_n=6/6 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
  H=30.0s | pos median=0.2839 m | pos p95=0.5181 m | rot median=0.0082 rad | total vel median=0.0161 m/s | rel vel median=0.0173 m/s | cond_n=6/6 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
  H=60.0s | pos median=0.5628 m | pos p95=0.6721 m | rot median=0.0189 rad | total vel median=0.0218 m/s | rel vel median=0.0190 m/s | cond_n=6/6 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000

Diagnostic Cases To Max Horizon
--------------------------------------------------------------------------------
Largest completed terminal errors
  PRBS seed=42 | reason=completed | sim_time=60.00s | pos=1.8331 m | rot=0.0165 rad | total_vel_violation=0
  CHIRP seed=100044 | reason=completed | sim_time=60.00s | pos=1.3998 m | rot=0.0258 rad | total_vel_violation=0
  PRBS seed=46 | reason=completed | sim_time=60.00s | pos=1.1811 m | rot=0.0173 rad | total_vel_violation=0
  CHIRP seed=100045 | reason=completed | sim_time=60.00s | pos=0.9285 m | rot=0.0152 rad | total_vel_violation=0
  CHIRP seed=100047 | reason=completed | sim_time=60.00s | pos=0.8849 m | rot=0.0221 rad | total_vel_violation=0

Diagnostic Plot Files
--------------------------------------------------------------------------------
PRBS seed=42 | label=high_terminal_error | /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke1_clean_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed42/rollout_benchmark/phase1a_iideval_traj6_seed42_20260425_024815/clean/diagnostic_plots/high_terminal_error_PRBS_seed42.png
CHIRP seed=100044 | label=high_terminal_error | /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke1_clean_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed42/rollout_benchmark/phase1a_iideval_traj6_seed42_20260425_024815/clean/diagnostic_plots/high_terminal_error_CHIRP_seed100044.png
Starting rollout benchmark | checkpoint=/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke1_clean_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed42/best_model.pt | device=cuda | mode=resampled | noise_profile=nominal_eval | noise_protocol=iid_noisy_ic | noise_budget=protocol=iid_noisy_ic | profile=nominal_eval | ref=remus100_dr | epoch_scale=1.000 | mix_ratio=0.500 | nu_r_lin_floor[u=0.0030, v=0.0030, w=0.0040] | nu_r_lin_ratio[u=0.0030, v=0.0030, w=0.0030] | nu_r_ang[p=0.0008, q=0.0008, r=0.0015] | rot[roll=0.0020, pitch=0.0020, yaw=0.0100] | scenarios=PRBS,CHIRP,OU | trajectories=18 | max_horizon=60.0s | output_dir=/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke1_clean_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed42/rollout_benchmark/phase1a_iideval_traj6_seed42_20260425_024815/nominal_eval
[scenario 1/3] PRBS | 6 trajectories
[1/18] PRBS seed=42 done | reason=completed | sim_time=60.00s | eta=5m47.4s
[5/18] PRBS seed=46 done | reason=completed | sim_time=60.00s | eta=53.2s
[6/18] PRBS seed=47 done | reason=completed | sim_time=60.00s | eta=40.9s
[scenario done] PRBS | completed=6/6 | gt_div=0 | model_fail=0 | H=60.0s cond_n=6/6 | pos_med=0.6290 m | pos_p95=3.9468 m | rot_med=0.0138 rad | completion=1.000 | elapsed=20.5s
[scenario 2/3] CHIRP | 6 trajectories
[7/18] CHIRP seed=100042 done | reason=completed | sim_time=60.00s | eta=1m02.3s
[11/18] CHIRP seed=100046 done | reason=completed | sim_time=60.00s | eta=25.2s
[12/18] CHIRP seed=100047 done | reason=completed | sim_time=60.00s | eta=19.8s
[scenario done] CHIRP | completed=6/6 | gt_div=0 | model_fail=0 | H=60.0s cond_n=6/6 | pos_med=0.7370 m | pos_p95=1.3727 m | rot_med=0.0169 rad | completion=1.000 | elapsed=39.7s
[scenario 3/3] OU | 6 trajectories
[13/18] OU seed=200042 done | reason=completed | sim_time=60.00s | eta=22.7s
[17/18] OU seed=200046 done | reason=completed | sim_time=60.00s | eta=3.5s
[18/18] OU seed=200047 done | reason=completed | sim_time=60.00s | eta=0.0s
[scenario done] OU | completed=6/6 | gt_div=0 | model_fail=0 | H=60.0s cond_n=6/6 | pos_med=0.7716 m | pos_p95=1.1453 m | rot_med=0.0217 rad | completion=1.000 | elapsed=59.0s
Benchmark finished in 1m11.7s
Results written to /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke1_clean_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed42/rollout_benchmark/phase1a_iideval_traj6_seed42_20260425_024815/nominal_eval
Rollout Benchmark Summary
================================================================================
Checkpoint: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke1_clean_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed42/best_model.pt
Dataset: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_5/data/auv_oc_traj1000_blk150_s23_d0be9434.pkl
Model: pH NODE Full [main/core]
Canonical model type: phnode_full
Energy semantics: mechanical_energy
Device: cuda
Mode: resampled
Generation config source: checkpoint
Scenarios: PRBS, CHIRP, OU
Trajectories per scenario: 6
Horizons: 10.0, 30.0, 60.0

Overall
--------------------------------------------------------------------------------
Conditional error statistics use only trajectories that completed to the horizon.
Primary KPIs are observable-space fields: position, depth, rotation, and total velocity.
Model-space diagnostics use relative velocity; internal diagnostics cover energy and raw SO(3) quality.
Per-column field grouping is exported in metric_contract.csv.
H=10.0s | pos median=0.1121 m | pos p95=0.3333 m | rot median=0.0084 rad | total vel median=0.0092 m/s | rel vel median=0.0082 m/s | cond_n=18/18 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
H=30.0s | pos median=0.3495 m | pos p95=1.0263 m | rot median=0.0082 rad | total vel median=0.0126 m/s | rel vel median=0.0132 m/s | cond_n=18/18 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
H=60.0s | pos median=0.7288 m | pos p95=2.8438 m | rot median=0.0169 rad | total vel median=0.0111 m/s | rel vel median=0.0125 m/s | cond_n=18/18 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000

Rollout Outcomes To Max Horizon
--------------------------------------------------------------------------------
n=18 | completed=18 (1.000) | gt_divergence=0 (0.000) | pred_divergence=0 (0.000) | solver_failure=0 (0.000) | nan_or_inf=0 (0.000)

By Scenario
--------------------------------------------------------------------------------
PRBS
  n=6 | completed=6 (1.000) | gt_divergence=0 (0.000) | pred_divergence=0 (0.000) | solver_failure=0 (0.000) | nan_or_inf=0 (0.000)
  H=10.0s | pos median=0.2078 m | pos p95=0.4940 m | rot median=0.0086 rad | total vel median=0.0126 m/s | rel vel median=0.0116 m/s | cond_n=6/6 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
  H=30.0s | pos median=0.4633 m | pos p95=1.6671 m | rot median=0.0066 rad | total vel median=0.0227 m/s | rel vel median=0.0225 m/s | cond_n=6/6 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
  H=60.0s | pos median=0.6290 m | pos p95=3.9468 m | rot median=0.0138 rad | total vel median=0.0167 m/s | rel vel median=0.0217 m/s | cond_n=6/6 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000

CHIRP
  n=6 | completed=6 (1.000) | gt_divergence=0 (0.000) | pred_divergence=0 (0.000) | solver_failure=0 (0.000) | nan_or_inf=0 (0.000)
  H=10.0s | pos median=0.0705 m | pos p95=0.1172 m | rot median=0.0074 rad | total vel median=0.0045 m/s | rel vel median=0.0044 m/s | cond_n=6/6 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
  H=30.0s | pos median=0.1983 m | pos p95=0.4100 m | rot median=0.0084 rad | total vel median=0.0041 m/s | rel vel median=0.0035 m/s | cond_n=6/6 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
  H=60.0s | pos median=0.7370 m | pos p95=1.3727 m | rot median=0.0169 rad | total vel median=0.0063 m/s | rel vel median=0.0110 m/s | cond_n=6/6 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000

OU
  n=6 | completed=6 (1.000) | gt_divergence=0 (0.000) | pred_divergence=0 (0.000) | solver_failure=0 (0.000) | nan_or_inf=0 (0.000)
  H=10.0s | pos median=0.1404 m | pos p95=0.2110 m | rot median=0.0142 rad | total vel median=0.0146 m/s | rel vel median=0.0129 m/s | cond_n=6/6 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
  H=30.0s | pos median=0.4335 m | pos p95=0.5413 m | rot median=0.0081 rad | total vel median=0.0168 m/s | rel vel median=0.0172 m/s | cond_n=6/6 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
  H=60.0s | pos median=0.7716 m | pos p95=1.1453 m | rot median=0.0217 rad | total vel median=0.0221 m/s | rel vel median=0.0189 m/s | cond_n=6/6 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000

Diagnostic Cases To Max Horizon
--------------------------------------------------------------------------------
Largest completed terminal errors
  PRBS seed=42 | reason=completed | sim_time=60.00s | pos=4.4063 m | rot=0.0360 rad | total_vel_violation=0
  PRBS seed=46 | reason=completed | sim_time=60.00s | pos=2.5681 m | rot=0.0300 rad | total_vel_violation=0
  CHIRP seed=100045 | reason=completed | sim_time=60.00s | pos=1.4001 m | rot=0.0205 rad | total_vel_violation=0
  CHIRP seed=100044 | reason=completed | sim_time=60.00s | pos=1.2903 m | rot=0.0246 rad | total_vel_violation=0
  OU seed=200042 | reason=completed | sim_time=60.00s | pos=1.1843 m | rot=0.0216 rad | total_vel_violation=0

Diagnostic Plot Files
--------------------------------------------------------------------------------
PRBS seed=42 | label=high_terminal_error | /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke1_clean_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed42/rollout_benchmark/phase1a_iideval_traj6_seed42_20260425_024815/nominal_eval/diagnostic_plots/high_terminal_error_PRBS_seed42.png
PRBS seed=46 | label=high_terminal_error | /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke1_clean_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed42/rollout_benchmark/phase1a_iideval_traj6_seed42_20260425_024815/nominal_eval/diagnostic_plots/high_terminal_error_PRBS_seed46.png
[eval] main_phnode_full_seed44
Starting rollout benchmark | checkpoint=/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke1_clean_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed44/best_model.pt | device=cuda | mode=resampled | noise_profile=clean | noise_protocol=clean | noise_budget=protocol=clean | profile=clean | ref=remus100_dr | epoch_scale=0.000 | mix_ratio=0.000 | nu_r_lin_floor[u=0.0000, v=0.0000, w=0.0000] | nu_r_lin_ratio[u=0.0000, v=0.0000, w=0.0000] | nu_r_ang[p=0.0000, q=0.0000, r=0.0000] | rot[roll=0.0000, pitch=0.0000, yaw=0.0000] | scenarios=PRBS,CHIRP,OU | trajectories=18 | max_horizon=60.0s | output_dir=/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke1_clean_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed44/rollout_benchmark/phase1a_iideval_traj6_seed42_20260425_025251/clean
[scenario 1/3] PRBS | 6 trajectories
[1/18] PRBS seed=42 done | reason=completed | sim_time=60.00s | eta=16m32.6s
[5/18] PRBS seed=46 done | reason=completed | sim_time=60.00s | eta=2m31.8s
[6/18] PRBS seed=47 done | reason=completed | sim_time=60.00s | eta=1m56.8s
[scenario done] PRBS | completed=6/6 | gt_div=0 | model_fail=0 | H=60.0s cond_n=6/6 | pos_med=1.6240 m | pos_p95=2.2888 m | rot_med=0.0368 rad | completion=1.000 | elapsed=58.4s
[scenario 2/3] CHIRP | 6 trajectories
[7/18] CHIRP seed=100042 done | reason=completed | sim_time=60.00s | eta=3m03.9s
[11/18] CHIRP seed=100046 done | reason=completed | sim_time=60.00s | eta=1m14.5s
[12/18] CHIRP seed=100047 done | reason=completed | sim_time=60.00s | eta=58.5s
[scenario done] CHIRP | completed=6/6 | gt_div=0 | model_fail=0 | H=60.0s cond_n=6/6 | pos_med=0.7312 m | pos_p95=1.2762 m | rot_med=0.0098 rad | completion=1.000 | elapsed=1m57.1s
[scenario 3/3] OU | 6 trajectories
[13/18] OU seed=200042 done | reason=completed | sim_time=60.00s | eta=1m07.5s
[17/18] OU seed=200046 done | reason=completed | sim_time=60.00s | eta=10.3s
[18/18] OU seed=200047 done | reason=completed | sim_time=60.00s | eta=0.0s
[scenario done] OU | completed=6/6 | gt_div=0 | model_fail=0 | H=60.0s cond_n=6/6 | pos_med=0.7067 m | pos_p95=2.3921 m | rot_med=0.0353 rad | completion=1.000 | elapsed=2m55.5s
Benchmark finished in 3m08.9s

## 4. Smoke-3 train + protocol validation

三模型 smoke：`phnode_full / ablate_no_mass_prior / ablate_no_lift × seeds 42/44/46`。

In [ ]:
os.environ["MODE"] = "smoke3_train"
!bash scripts/run_phase1a_oc_v4lite.sh

Streaming output truncated to the last 5000 lines.
==================================================
[nominal_eval]
position_rmse: ratio=10.266  degradation=+926.6%
rotation_geodesic: ratio=17.602  degradation=+1660.2%
velocity_rmse: ratio=3.404  degradation=+240.4%
angular_rmse: ratio=2.750  degradation=+175.0%
success_rate: ratio=1.000  degradation=+0.0%
trajectory_failure_rate: ratio=1.000  degradation=+0.0%
[degraded_eval]
position_rmse: ratio=24.171  degradation=+2317.1%
rotation_geodesic: ratio=43.027  degradation=+4202.7%
velocity_rmse: ratio=6.730  degradation=+573.0%
angular_rmse: ratio=5.116  degradation=+411.6%
success_rate: ratio=1.000  degradation=+0.0%
trajectory_failure_rate: ratio=1.000  degradation=+0.0%
[heading_biased_eval]
position_rmse: ratio=37.091  degradation=+3609.1%
rotation_geodesic: ratio=71.601  degradation=+7060.1%
velocity_rmse: ratio=5.445  degradation=+444.5%
angular_rmse: ratio=2.750  degradation=+175.0%
success_rate: ratio=1.000  degradation=+0.0%
trajectory_failure_rate: ratio=1.000  degradation=+0.0%

Training finished. Results: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_iid_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_mass_prior_seed46
[train] ablation_ablate_no_lift_seed42
Loading dataset...
Loaded: 83850 train, 21000 test, t_eval=[0.   0.05 0.1  0.15 0.2 ]
Dataset split: trajectory | train trajectories: 559 | test trajectories: 140
Dataset ID: d0be9434
Dataset path: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_5/data/auv_oc_traj1000_blk150_s23_d0be9434.pkl | velocity convention: body_total | state dim: 27
Position std: [0.1508, 0.1400, 0.0370]
Velocity std: u=0.4722, v=0.0898, w=0.0718, p=0.0248, q=0.0906, r=0.0526
Actuator std: a0=0.1543, a1=0.1555, a2=299.0037
Training noise budget: protocol=iid_noisy_ic | profile=nominal_train | ref=remus100_dr | epoch_scale=1.000 | mix_ratio=0.500 | nu_r_lin_floor[u=0.0020, v=0.0020, w=0.0030] | nu_r_lin_ratio[u=0.0020, v=0.0020, w=0.0020] | nu_r_ang[p=0.0006, q=0.0006, r=0.0010] | rot[roll=0.0015, pitch=0.0015, yaw=0.0060]
Model: Ablation: No Lift [ablation/ablation] | canonical type: ablate_no_lift
Model parameters: 43,076
Training dataset: id=d0be9434 | path=/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_5/data/auv_oc_traj1000_blk150_s23_d0be9434.pkl
Mass matrix initialized from physics
Training: epochs<=300, target_steps=5000, warmup_steps=400, lr=6.00e-03 -> 1.00e-04, solver=rk4, so3_reg=1.00e-03
Train samples: 83850, Test samples: 21000
Epoch    1 | Step    20/ 5000 | Train 4.3725e+00 | Test 5.0511e+00 | SO3(train/test) 1.26e-07/1.27e-07 | Fail(train/test) 0/0 | LR 4.10e-04 | 6.4s
Epoch    2 | Step    40/ 5000 | Train 3.5665e+00 | Test 4.2659e+00 | SO3(train/test) 1.19e-07/1.19e-07 | Fail(train/test) 0/0 | LR 7.05e-04 | 5.7s
Epoch    3 | Step    60/ 5000 | Train 3.0009e+00 | Test 3.4297e+00 | SO3(train/test) 1.16e-07/1.17e-07 | Fail(train/test) 0/0 | LR 1.00e-03 | 5.7s
Epoch    4 | Step    80/ 5000 | Train 2.1773e+00 | Test 1.9350e+00 | SO3(train/test) 1.15e-07/1.18e-07 | Fail(train/test) 0/0 | LR 1.29e-03 | 5.7s
Epoch    5 | Step   100/ 5000 | Train 1.2815e+00 | Test 1.3508e+00 | SO3(train/test) 1.39e-07/1.41e-07 | Fail(train/test) 0/0 | LR 1.59e-03 | 5.7s
Epoch    6 | Step   120/ 5000 | Train 1.0003e+00 | Test 9.8119e-01 | SO3(train/test) 1.30e-07/1.20e-07 | Fail(train/test) 0/0 | LR 1.88e-03 | 5.7s
Epoch    7 | Step   140/ 5000 | Train 9.9994e-01 | Test 1.0374e+00 | SO3(train/test) 1.19e-07/1.21e-07 | Fail(train/test) 0/0 | LR 2.18e-03 | 5.7s
Epoch    8 | Step   160/ 5000 | Train 6.1371e-01 | Test 5.6466e-01 | SO3(train/test) 1.15e-07/1.14e-07 | Fail(train/test) 0/0 | LR 2.47e-03 | 5.7s
Epoch    9 | Step   180/ 5000 | Train 1.0216e+00 | Test 7.7977e-01 | SO3(train/test) 1.16e-07/1.16e-07 | Fail(train/test) 0/0 | LR 2.77e-03 | 5.7s
Epoch   10 | Step   200/ 5000 | Train 7.4990e-01 | Test 5.3794e-01 | SO3(train/test) 1.17e-07/1.16e-07 | Fail(train/test) 0/0 | LR 3.06e-03 | 5.8s
Epoch   11 | Step   220/ 5000 | Train 5.6690e-01 | Test 1.0940e+00 | SO3(train/test) 1.15e-07/1.19e-07 | Fail(train/test) 0/0 | LR 3.36e-03 | 5.7s
Epoch   12 | Step   240/ 5000 | Train 7.0238e-01 | Test 4.3604e-01 | SO3(train/test) 1.18e-07/1.18e-07 | Fail(train/test) 0/0 | LR 3.65e-03 | 5.8s
Epoch   13 | Step   260/ 5000 | Train 6.4547e-01 | Test 7.0087e-01 | SO3(train/test) 1.18e-07/1.21e-07 | Fail(train/test) 0/0 | LR 3.95e-03 | 5.9s
Epoch   14 | Step   280/ 5000 | Train 8.8912e-01 | Test 6.3906e-01 | SO3(train/test) 1.52e-07/1.87e-07 | Fail(train/test) 0/0 | LR 4.24e-03 | 5.9s
Epoch   15 | Step   300/ 5000 | Train 6.4173e-01 | Test 1.5198e+00 | SO3(train/test) 1.40e-07/1.32e-07 | Fail(train/test) 0/0 | LR 4.54e-03 | 5.9s
Epoch   16 | Step   320/ 5000 | Train 9.3862e-01 | Test 1.0979e+00 | SO3(train/test) 1.52e-07/1.19e-06 | Fail(train/test) 0/0 | LR 4.83e-03 | 6.0s
Epoch   17 | Step   340/ 5000 | Train 4.0826e+00 | Test 3.4112e+00 | SO3(train/test) 4.99e-06/2.27e-07 | Fail(train/test) 0/0 | LR 5.13e-03 | 5.8s
Epoch   18 | Step   360/ 5000 | Train 1.2686e+00 | Test 8.6893e-01 | SO3(train/test) 1.67e-07/5.10e-07 | Fail(train/test) 0/0 | LR 5.42e-03 | 5.9s
Epoch   19 | Step   380/ 5000 | Train 5.2786e-01 | Test 8.4807e-01 | SO3(train/test) 1.65e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.72e-03 | 5.8s
Epoch   20 | Step   400/ 5000 | Train 4.8380e-01 | Test 6.0588e-01 | SO3(train/test) 1.15e-07/1.15e-07 | Fail(train/test) 0/0 | LR 6.00e-03 | 5.9s
Epoch   21 | Step   420/ 5000 | Train 4.4917e-01 | Test 3.9683e-01 | SO3(train/test) 3.59e-07/1.15e-07 | Fail(train/test) 0/0 | LR 6.00e-03 | 5.9s
Epoch   22 | Step   440/ 5000 | Train 3.8610e-01 | Test 5.0888e-01 | SO3(train/test) 3.63e-07/1.15e-07 | Fail(train/test) 0/0 | LR 6.00e-03 | 6.0s
Epoch   23 | Step   460/ 5000 | Train 3.8663e-01 | Test 3.2774e-01 | SO3(train/test) 3.60e-07/1.14e-07 | Fail(train/test) 0/0 | LR 6.00e-03 | 5.9s
Epoch   24 | Step   480/ 5000 | Train 3.9649e-01 | Test 2.0661e-01 | SO3(train/test) 3.59e-07/1.14e-07 | Fail(train/test) 0/0 | LR 6.00e-03 | 5.9s
Epoch   25 | Step   500/ 5000 | Train 2.5375e-01 | Test 3.6115e-01 | SO3(train/test) 3.62e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.99e-03 | 5.9s
Epoch   26 | Step   520/ 5000 | Train 8.6439e-01 | Test 9.8961e-01 | SO3(train/test) 3.84e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.99e-03 | 5.9s
Epoch   27 | Step   540/ 5000 | Train 5.5109e-01 | Test 3.9905e-01 | SO3(train/test) 3.64e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.99e-03 | 6.0s
Epoch   28 | Step   560/ 5000 | Train 4.7217e-01 | Test 5.4594e-01 | SO3(train/test) 3.64e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.98e-03 | 5.9s
Epoch   29 | Step   580/ 5000 | Train 4.5221e-01 | Test 3.4818e-01 | SO3(train/test) 3.63e-07/1.13e-07 | Fail(train/test) 0/0 | LR 5.98e-03 | 5.9s
Epoch   30 | Step   600/ 5000 | Train 4.3519e-01 | Test 4.5247e-01 | SO3(train/test) 3.64e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.97e-03 | 5.9s
Epoch   31 | Step   620/ 5000 | Train 3.0805e-01 | Test 2.3072e-01 | SO3(train/test) 3.63e-07/1.13e-07 | Fail(train/test) 0/0 | LR 5.97e-03 | 5.8s
Epoch   32 | Step   640/ 5000 | Train 3.4303e-01 | Test 3.4228e-01 | SO3(train/test) 3.62e-07/1.13e-07 | Fail(train/test) 0/0 | LR 5.96e-03 | 5.8s
Epoch   33 | Step   660/ 5000 | Train 3.1188e-01 | Test 2.4987e-01 | SO3(train/test) 3.64e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.95e-03 | 5.9s
Epoch   34 | Step   680/ 5000 | Train 2.8202e-01 | Test 2.5981e-01 | SO3(train/test) 3.63e-07/1.13e-07 | Fail(train/test) 0/0 | LR 5.95e-03 | 5.7s
Epoch   35 | Step   700/ 5000 | Train 2.5576e-01 | Test 2.3383e-01 | SO3(train/test) 3.65e-07/1.13e-07 | Fail(train/test) 0/0 | LR 5.94e-03 | 5.9s
Epoch   36 | Step   720/ 5000 | Train 3.0864e-01 | Test 3.9113e-01 | SO3(train/test) 3.64e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.93e-03 | 5.7s
Epoch   37 | Step   740/ 5000 | Train 3.2942e-01 | Test 2.7094e-01 | SO3(train/test) 3.61e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.92e-03 | 5.8s
Epoch   38 | Step   760/ 5000 | Train 2.6276e-01 | Test 2.5809e-01 | SO3(train/test) 3.62e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.91e-03 | 5.7s
Epoch   39 | Step   780/ 5000 | Train 2.5708e-01 | Test 1.6509e-01 | SO3(train/test) 3.65e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.90e-03 | 5.7s
Epoch   40 | Step   800/ 5000 | Train 4.2536e-01 | Test 4.8577e-01 | SO3(train/test) 3.63e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.89e-03 | 5.7s
Epoch   41 | Step   820/ 5000 | Train 3.0658e-01 | Test 2.1319e-01 | SO3(train/test) 3.65e-07/1.13e-07 | Fail(train/test) 0/0 | LR 5.88e-03 | 5.9s
Epoch   42 | Step   840/ 5000 | Train 1.9578e-01 | Test 2.2264e-01 | SO3(train/test) 3.63e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.87e-03 | 5.8s
Epoch   43 | Step   860/ 5000 | Train 1.6340e-01 | Test 1.2308e-01 | SO3(train/test) 3.63e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.86e-03 | 5.7s
Epoch   44 | Step   880/ 5000 | Train 1.4390e-01 | Test 1.7709e-01 | SO3(train/test) 3.64e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.84e-03 | 5.8s
Epoch   45 | Step   900/ 5000 | Train 2.8528e-01 | Test 2.5716e-01 | SO3(train/test) 3.64e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.83e-03 | 5.9s
Epoch   46 | Step   920/ 5000 | Train 2.3523e-01 | Test 1.8751e-01 | SO3(train/test) 3.64e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.82e-03 | 5.8s
Epoch   47 | Step   940/ 5000 | Train 2.4042e-01 | Test 2.2063e-01 | SO3(train/test) 3.65e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.80e-03 | 5.9s
Epoch   48 | Step   960/ 5000 | Train 1.7879e-01 | Test 1.2707e-01 | SO3(train/test) 3.66e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.79e-03 | 5.9s
Epoch   49 | Step   980/ 5000 | Train 1.1879e-01 | Test 1.2481e-01 | SO3(train/test) 3.66e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.77e-03 | 5.7s
Epoch   50 | Step  1000/ 5000 | Train 1.8036e-01 | Test 1.6683e-01 | SO3(train/test) 3.65e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.76e-03 | 5.9s
Epoch   51 | Step  1020/ 5000 | Train 2.0194e-01 | Test 1.3556e-01 | SO3(train/test) 3.64e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.74e-03 | 5.6s
Epoch   52 | Step  1040/ 5000 | Train 1.3310e-01 | Test 1.9956e-01 | SO3(train/test) 3.64e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.72e-03 | 5.8s
Epoch   53 | Step  1060/ 5000 | Train 1.5976e-01 | Test 1.1890e-01 | SO3(train/test) 3.68e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.71e-03 | 5.7s
Epoch   54 | Step  1080/ 5000 | Train 1.3899e-01 | Test 1.1774e-01 | SO3(train/test) 3.63e-07/1.14e-07 | Fail(train/test) 0/0 | LR 5.69e-03 | 5.7s
Epoch   55 | Step  1100/ 5000 | Train 1.5125e-01 | Test 1.3069e-01 | SO3(train/test) 3.66e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.67e-03 | 5.7s
Epoch   56 | Step  1120/ 5000 | Train 1.0684e-01 | Test 1.7678e-01 | SO3(train/test) 3.67e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.65e-03 | 5.8s
Epoch   57 | Step  1140/ 5000 | Train 1.0606e-01 | Test 1.0720e-01 | SO3(train/test) 3.68e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.63e-03 | 5.7s
Epoch   58 | Step  1160/ 5000 | Train 8.9283e-02 | Test 6.8900e-02 | SO3(train/test) 3.66e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.61e-03 | 5.7s
Epoch   59 | Step  1180/ 5000 | Train 8.3461e-02 | Test 7.8825e-02 | SO3(train/test) 3.66e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.59e-03 | 5.7s
Epoch   60 | Step  1200/ 5000 | Train 8.9051e-02 | Test 9.6686e-02 | SO3(train/test) 3.67e-07/1.17e-07 | Fail(train/test) 0/0 | LR 5.57e-03 | 5.8s
Epoch   61 | Step  1220/ 5000 | Train 7.5059e-02 | Test 1.1060e-01 | SO3(train/test) 3.67e-07/1.17e-07 | Fail(train/test) 0/0 | LR 5.55e-03 | 5.8s
Epoch   62 | Step  1240/ 5000 | Train 9.3509e-02 | Test 6.3282e-02 | SO3(train/test) 3.65e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.53e-03 | 5.8s
Epoch   63 | Step  1260/ 5000 | Train 7.6307e-02 | Test 8.8325e-02 | SO3(train/test) 3.67e-07/1.17e-07 | Fail(train/test) 0/0 | LR 5.51e-03 | 5.7s
Epoch   64 | Step  1280/ 5000 | Train 1.1383e-01 | Test 7.7231e-02 | SO3(train/test) 3.66e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.48e-03 | 5.7s
Epoch   65 | Step  1300/ 5000 | Train 7.2165e-02 | Test 6.4429e-02 | SO3(train/test) 3.66e-07/1.17e-07 | Fail(train/test) 0/0 | LR 5.46e-03 | 5.9s
Epoch   66 | Step  1320/ 5000 | Train 5.6831e-02 | Test 6.6481e-02 | SO3(train/test) 3.64e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.44e-03 | 5.7s
Epoch   67 | Step  1340/ 5000 | Train 5.3595e-02 | Test 4.6088e-02 | SO3(train/test) 3.64e-07/1.17e-07 | Fail(train/test) 0/0 | LR 5.41e-03 | 5.7s
Epoch   68 | Step  1360/ 5000 | Train 6.1693e-02 | Test 7.7445e-02 | SO3(train/test) 3.68e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.39e-03 | 5.8s
Epoch   69 | Step  1380/ 5000 | Train 5.8694e-02 | Test 5.0925e-02 | SO3(train/test) 3.64e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.36e-03 | 5.7s
Epoch   70 | Step  1400/ 5000 | Train 7.8631e-02 | Test 4.3505e-02 | SO3(train/test) 3.67e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.34e-03 | 5.9s
Epoch   71 | Step  1420/ 5000 | Train 6.1127e-02 | Test 5.4585e-02 | SO3(train/test) 3.67e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.31e-03 | 5.7s
Epoch   72 | Step  1440/ 5000 | Train 6.0552e-02 | Test 1.0856e-01 | SO3(train/test) 3.64e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.29e-03 | 5.8s
Epoch   73 | Step  1460/ 5000 | Train 9.0814e-02 | Test 1.3995e-01 | SO3(train/test) 3.64e-07/1.15e-07 | Fail(train/test) 0/0 | LR 5.26e-03 | 5.7s
Epoch   74 | Step  1480/ 5000 | Train 7.2302e-02 | Test 4.7902e-02 | SO3(train/test) 3.67e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.23e-03 | 5.9s
Epoch   75 | Step  1500/ 5000 | Train 4.5352e-02 | Test 3.0314e-02 | SO3(train/test) 3.67e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.21e-03 | 5.9s
Epoch   76 | Step  1520/ 5000 | Train 5.2032e-02 | Test 4.7837e-02 | SO3(train/test) 3.67e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.18e-03 | 5.7s
Epoch   77 | Step  1540/ 5000 | Train 4.3910e-02 | Test 2.7067e-02 | SO3(train/test) 3.67e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.15e-03 | 5.8s
Epoch   78 | Step  1560/ 5000 | Train 3.7665e-02 | Test 3.4402e-02 | SO3(train/test) 3.68e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.12e-03 | 5.7s
Epoch   79 | Step  1580/ 5000 | Train 3.5938e-02 | Test 2.7024e-02 | SO3(train/test) 3.68e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.09e-03 | 5.7s
Epoch   80 | Step  1600/ 5000 | Train 4.8798e-02 | Test 3.4943e-02 | SO3(train/test) 3.67e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.06e-03 | 5.8s
Epoch   81 | Step  1620/ 5000 | Train 5.0465e-02 | Test 2.8504e-02 | SO3(train/test) 3.66e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.03e-03 | 5.9s
Epoch   82 | Step  1640/ 5000 | Train 4.7702e-02 | Test 2.9350e-02 | SO3(train/test) 3.68e-07/1.16e-07 | Fail(train/test) 0/0 | LR 5.00e-03 | 5.8s
Epoch   83 | Step  1660/ 5000 | Train 4.0661e-02 | Test 1.9609e-02 | SO3(train/test) 3.69e-07/1.15e-07 | Fail(train/test) 0/0 | LR 4.97e-03 | 5.8s
Epoch   84 | Step  1680/ 5000 | Train 4.4732e-02 | Test 2.5009e-02 | SO3(train/test) 3.68e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.94e-03 | 5.8s
Epoch   85 | Step  1700/ 5000 | Train 4.8660e-02 | Test 3.5543e-02 | SO3(train/test) 3.69e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.91e-03 | 6.0s
Epoch   86 | Step  1720/ 5000 | Train 3.3839e-02 | Test 2.1958e-02 | SO3(train/test) 3.66e-07/1.17e-07 | Fail(train/test) 0/0 | LR 4.88e-03 | 5.8s
Epoch   87 | Step  1740/ 5000 | Train 3.7059e-02 | Test 2.8932e-02 | SO3(train/test) 3.70e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.85e-03 | 5.9s
Epoch   88 | Step  1760/ 5000 | Train 3.4843e-02 | Test 3.7635e-02 | SO3(train/test) 3.68e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.82e-03 | 5.8s
Epoch   89 | Step  1780/ 5000 | Train 3.7614e-02 | Test 1.9288e-02 | SO3(train/test) 3.68e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.78e-03 | 5.8s
Epoch   90 | Step  1800/ 5000 | Train 4.2399e-02 | Test 3.9223e-02 | SO3(train/test) 3.68e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.75e-03 | 5.7s
Epoch   91 | Step  1820/ 5000 | Train 3.4092e-02 | Test 2.5033e-02 | SO3(train/test) 3.68e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.72e-03 | 5.9s
Epoch   92 | Step  1840/ 5000 | Train 3.5752e-02 | Test 6.2837e-02 | SO3(train/test) 3.68e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.68e-03 | 5.8s
Epoch   93 | Step  1860/ 5000 | Train 4.0422e-02 | Test 2.2193e-02 | SO3(train/test) 3.70e-07/1.17e-07 | Fail(train/test) 0/0 | LR 4.65e-03 | 5.8s
Epoch   94 | Step  1880/ 5000 | Train 3.0952e-02 | Test 2.3531e-02 | SO3(train/test) 3.69e-07/1.17e-07 | Fail(train/test) 0/0 | LR 4.62e-03 | 5.9s
Epoch   95 | Step  1900/ 5000 | Train 3.2384e-02 | Test 1.4524e-02 | SO3(train/test) 3.69e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.58e-03 | 6.0s
Epoch   96 | Step  1920/ 5000 | Train 3.3103e-02 | Test 1.7006e-02 | SO3(train/test) 3.66e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.55e-03 | 5.8s
Epoch   97 | Step  1940/ 5000 | Train 3.0910e-02 | Test 3.1578e-02 | SO3(train/test) 3.68e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.51e-03 | 5.9s
Epoch   98 | Step  1960/ 5000 | Train 2.7987e-02 | Test 1.1606e-02 | SO3(train/test) 3.68e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.48e-03 | 5.9s
Epoch   99 | Step  1980/ 5000 | Train 2.9475e-02 | Test 2.4026e-02 | SO3(train/test) 3.68e-07/1.17e-07 | Fail(train/test) 0/0 | LR 4.44e-03 | 5.8s
Epoch  100 | Step  2000/ 5000 | Train 2.9051e-02 | Test 1.6520e-02 | SO3(train/test) 3.68e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.41e-03 | 5.9s
Epoch  101 | Step  2020/ 5000 | Train 2.9346e-02 | Test 1.1200e-02 | SO3(train/test) 3.67e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.37e-03 | 5.9s
Epoch  102 | Step  2040/ 5000 | Train 2.6022e-02 | Test 1.2814e-02 | SO3(train/test) 3.69e-07/1.17e-07 | Fail(train/test) 0/0 | LR 4.33e-03 | 5.8s
Epoch  103 | Step  2060/ 5000 | Train 2.6844e-02 | Test 1.0769e-02 | SO3(train/test) 3.69e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.30e-03 | 5.7s
Epoch  104 | Step  2080/ 5000 | Train 2.9440e-02 | Test 1.1724e-02 | SO3(train/test) 3.66e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.26e-03 | 5.9s
Epoch  105 | Step  2100/ 5000 | Train 2.5924e-02 | Test 1.3877e-02 | SO3(train/test) 3.67e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.22e-03 | 5.9s
Epoch  106 | Step  2120/ 5000 | Train 5.6924e-02 | Test 2.5727e-02 | SO3(train/test) 3.67e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.19e-03 | 5.9s
Epoch  107 | Step  2140/ 5000 | Train 4.1247e-02 | Test 1.3287e-02 | SO3(train/test) 3.67e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.15e-03 | 5.7s
Epoch  108 | Step  2160/ 5000 | Train 2.9428e-02 | Test 3.0332e-02 | SO3(train/test) 3.68e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.11e-03 | 5.8s
Epoch  109 | Step  2180/ 5000 | Train 3.3913e-02 | Test 1.6797e-02 | SO3(train/test) 3.69e-07/1.16e-07 | Fail(train/test) 0/0 | LR 4.08e-03 | 5.7s
Epoch  110 | Step  2200/ 5000 | Train 2.7697e-02 | Test 1.2814e-02 | SO3(train/test) 3.69e-07/1.17e-07 | Fail(train/test) 0/0 | LR 4.04e-03 | 5.9s
Epoch  111 | Step  2220/ 5000 | Train 2.7874e-02 | Test 1.1858e-02 | SO3(train/test) 3.66e-07/1.17e-07 | Fail(train/test) 0/0 | LR 4.00e-03 | 5.7s
Epoch  112 | Step  2240/ 5000 | Train 2.6183e-02 | Test 2.1093e-02 | SO3(train/test) 3.69e-07/1.17e-07 | Fail(train/test) 0/0 | LR 3.96e-03 | 5.7s
Epoch  113 | Step  2260/ 5000 | Train 2.8734e-02 | Test 1.5537e-02 | SO3(train/test) 3.67e-07/1.16e-07 | Fail(train/test) 0/0 | LR 3.92e-03 | 5.8s
Epoch  114 | Step  2280/ 5000 | Train 2.8860e-02 | Test 1.8731e-02 | SO3(train/test) 3.69e-07/1.17e-07 | Fail(train/test) 0/0 | LR 3.88e-03 | 5.7s
Epoch  115 | Step  2300/ 5000 | Train 2.8753e-02 | Test 1.9811e-02 | SO3(train/test) 3.65e-07/1.16e-07 | Fail(train/test) 0/0 | LR 3.85e-03 | 5.9s
Epoch  116 | Step  2320/ 5000 | Train 2.6985e-02 | Test 9.5075e-03 | SO3(train/test) 3.66e-07/1.17e-07 | Fail(train/test) 0/0 | LR 3.81e-03 | 5.7s
Epoch  117 | Step  2340/ 5000 | Train 2.8539e-02 | Test 1.3922e-02 | SO3(train/test) 3.67e-07/1.16e-07 | Fail(train/test) 0/0 | LR 3.77e-03 | 5.8s
Epoch  118 | Step  2360/ 5000 | Train 3.0479e-02 | Test 1.4615e-02 | SO3(train/test) 3.69e-07/1.17e-07 | Fail(train/test) 0/0 | LR 3.73e-03 | 5.7s

## 5. Smoke-3 rollout eval + local proxy

通过后再进入五 seed decision run。

In [ ]:
os.environ["MODE"] = "smoke3_eval"
!bash scripts/run_phase1a_oc_v4lite.sh

Streaming output truncated to the last 5000 lines.

Diagnostic Cases To Max Horizon
--------------------------------------------------------------------------------
Largest completed terminal errors
  PRBS seed=46 | reason=completed | sim_time=60.00s | pos=3.3922 m | rot=0.0506 rad | total_vel_violation=0
  OU seed=200042 | reason=completed | sim_time=60.00s | pos=2.6853 m | rot=0.0661 rad | total_vel_violation=0
  OU seed=200043 | reason=completed | sim_time=60.00s | pos=2.0107 m | rot=0.0698 rad | total_vel_violation=0
  PRBS seed=42 | reason=completed | sim_time=60.00s | pos=1.8868 m | rot=0.0253 rad | total_vel_violation=0
  CHIRP seed=100047 | reason=completed | sim_time=60.00s | pos=1.6587 m | rot=0.0337 rad | total_vel_violation=0

Diagnostic Plot Files
--------------------------------------------------------------------------------
PRBS seed=46 | label=high_terminal_error | /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_iid_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed42/rollout_benchmark/phase1a_iideval_traj6_seed42_20260425_155334/clean/diagnostic_plots/high_terminal_error_PRBS_seed46.png
OU seed=200042 | label=high_terminal_error | /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_iid_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed42/rollout_benchmark/phase1a_iideval_traj6_seed42_20260425_155334/clean/diagnostic_plots/high_terminal_error_OU_seed200042.png
Starting rollout benchmark | checkpoint=/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_iid_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed42/best_model.pt | device=cuda | mode=resampled | noise_profile=nominal_eval | noise_protocol=iid_noisy_ic | noise_budget=protocol=iid_noisy_ic | profile=nominal_eval | ref=remus100_dr | epoch_scale=1.000 | mix_ratio=0.500 | nu_r_lin_floor[u=0.0030, v=0.0030, w=0.0040] | nu_r_lin_ratio[u=0.0030, v=0.0030, w=0.0030] | nu_r_ang[p=0.0008, q=0.0008, r=0.0015] | rot[roll=0.0020, pitch=0.0020, yaw=0.0100] | scenarios=PRBS,CHIRP,OU | trajectories=18 | max_horizon=60.0s | output_dir=/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_iid_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed42/rollout_benchmark/phase1a_iideval_traj6_seed42_20260425_155334/nominal_eval
[scenario 1/3] PRBS | 6 trajectories
[1/18] PRBS seed=42 done | reason=completed | sim_time=60.00s | eta=5m22.1s
[5/18] PRBS seed=46 done | reason=completed | sim_time=60.00s | eta=49.3s
[6/18] PRBS seed=47 done | reason=completed | sim_time=60.00s | eta=37.9s
[scenario done] PRBS | completed=6/6 | gt_div=0 | model_fail=0 | H=60.0s cond_n=6/6 | pos_med=1.8920 m | pos_p95=4.6872 m | rot_med=0.0373 rad | completion=1.000 | elapsed=19.0s
[scenario 2/3] CHIRP | 6 trajectories
[7/18] CHIRP seed=100042 done | reason=completed | sim_time=60.00s | eta=59.1s
[11/18] CHIRP seed=100046 done | reason=completed | sim_time=60.00s | eta=24.0s
[12/18] CHIRP seed=100047 done | reason=completed | sim_time=60.00s | eta=18.8s
[scenario done] CHIRP | completed=6/6 | gt_div=0 | model_fail=0 | H=60.0s cond_n=6/6 | pos_med=1.1555 m | pos_p95=1.8675 m | rot_med=0.0239 rad | completion=1.000 | elapsed=37.7s
[scenario 3/3] OU | 6 trajectories
[13/18] OU seed=200042 done | reason=completed | sim_time=60.00s | eta=21.7s
[17/18] OU seed=200046 done | reason=completed | sim_time=60.00s | eta=3.3s
[18/18] OU seed=200047 done | reason=completed | sim_time=60.00s | eta=0.0s
[scenario done] OU | completed=6/6 | gt_div=0 | model_fail=0 | H=60.0s cond_n=6/6 | pos_med=1.1058 m | pos_p95=3.2510 m | rot_med=0.0227 rad | completion=1.000 | elapsed=56.4s
Benchmark finished in 1m09.2s
Results written to /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_iid_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed42/rollout_benchmark/phase1a_iideval_traj6_seed42_20260425_155334/nominal_eval
Rollout Benchmark Summary
================================================================================
Checkpoint: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_iid_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed42/best_model.pt
Dataset: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_5/data/auv_oc_traj1000_blk150_s23_d0be9434.pkl
Model: pH NODE Full [main/core]
Canonical model type: phnode_full
Energy semantics: mechanical_energy
Device: cuda
Mode: resampled
Generation config source: checkpoint
Scenarios: PRBS, CHIRP, OU
Trajectories per scenario: 6
Horizons: 10.0, 30.0, 60.0

Overall
--------------------------------------------------------------------------------
Conditional error statistics use only trajectories that completed to the horizon.
Primary KPIs are observable-space fields: position, depth, rotation, and total velocity.
Model-space diagnostics use relative velocity; internal diagnostics cover energy and raw SO(3) quality.
Per-column field grouping is exported in metric_contract.csv.
H=10.0s | pos median=0.1535 m | pos p95=0.4306 m | rot median=0.0087 rad | total vel median=0.0080 m/s | rel vel median=0.0062 m/s | cond_n=18/18 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
H=30.0s | pos median=0.4480 m | pos p95=1.4808 m | rot median=0.0165 rad | total vel median=0.0138 m/s | rel vel median=0.0083 m/s | cond_n=18/18 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
H=60.0s | pos median=1.2902 m | pos p95=4.5145 m | rot median=0.0250 rad | total vel median=0.0168 m/s | rel vel median=0.0148 m/s | cond_n=18/18 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000

Rollout Outcomes To Max Horizon
--------------------------------------------------------------------------------
n=18 | completed=18 (1.000) | gt_divergence=0 (0.000) | pred_divergence=0 (0.000) | solver_failure=0 (0.000) | nan_or_inf=0 (0.000)

By Scenario
--------------------------------------------------------------------------------
PRBS
  n=6 | completed=6 (1.000) | gt_divergence=0 (0.000) | pred_divergence=0 (0.000) | solver_failure=0 (0.000) | nan_or_inf=0 (0.000)
  H=10.0s | pos median=0.2952 m | pos p95=0.5392 m | rot median=0.0153 rad | total vel median=0.0118 m/s | rel vel median=0.0072 m/s | cond_n=6/6 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
  H=30.0s | pos median=1.0068 m | pos p95=1.7770 m | rot median=0.0256 rad | total vel median=0.0227 m/s | rel vel median=0.0083 m/s | cond_n=6/6 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
  H=60.0s | pos median=1.8920 m | pos p95=4.6872 m | rot median=0.0373 rad | total vel median=0.0197 m/s | rel vel median=0.0192 m/s | cond_n=6/6 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000

CHIRP
  n=6 | completed=6 (1.000) | gt_divergence=0 (0.000) | pred_divergence=0 (0.000) | solver_failure=0 (0.000) | nan_or_inf=0 (0.000)
  H=10.0s | pos median=0.0956 m | pos p95=0.1478 m | rot median=0.0053 rad | total vel median=0.0064 m/s | rel vel median=0.0065 m/s | cond_n=6/6 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
  H=30.0s | pos median=0.2330 m | pos p95=0.4801 m | rot median=0.0130 rad | total vel median=0.0057 m/s | rel vel median=0.0054 m/s | cond_n=6/6 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
  H=60.0s | pos median=1.1555 m | pos p95=1.8675 m | rot median=0.0239 rad | total vel median=0.0062 m/s | rel vel median=0.0114 m/s | cond_n=6/6 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000

OU
  n=6 | completed=6 (1.000) | gt_divergence=0 (0.000) | pred_divergence=0 (0.000) | solver_failure=0 (0.000) | nan_or_inf=0 (0.000)
  H=10.0s | pos median=0.1855 m | pos p95=0.3459 m | rot median=0.0167 rad | total vel median=0.0055 m/s | rel vel median=0.0046 m/s | cond_n=6/6 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
  H=30.0s | pos median=0.4618 m | pos p95=1.0644 m | rot median=0.0107 rad | total vel median=0.0236 m/s | rel vel median=0.0210 m/s | cond_n=6/6 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
  H=60.0s | pos median=1.1058 m | pos p95=3.2510 m | rot median=0.0227 rad | total vel median=0.0272 m/s | rel vel median=0.0242 m/s | cond_n=6/6 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000

Diagnostic Cases To Max Horizon
--------------------------------------------------------------------------------
Largest completed terminal errors
  PRBS seed=46 | reason=completed | sim_time=60.00s | pos=4.7592 m | rot=0.0631 rad | total_vel_violation=0
  PRBS seed=42 | reason=completed | sim_time=60.00s | pos=4.4713 m | rot=0.0447 rad | total_vel_violation=0
  OU seed=200042 | reason=completed | sim_time=60.00s | pos=3.5418 m | rot=0.0787 rad | total_vel_violation=0
  OU seed=200043 | reason=completed | sim_time=60.00s | pos=2.3786 m | rot=0.0746 rad | total_vel_violation=0
  PRBS seed=45 | reason=completed | sim_time=60.00s | pos=2.2523 m | rot=0.0503 rad | total_vel_violation=0

Diagnostic Plot Files
--------------------------------------------------------------------------------
PRBS seed=46 | label=high_terminal_error | /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_iid_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed42/rollout_benchmark/phase1a_iideval_traj6_seed42_20260425_155334/nominal_eval/diagnostic_plots/high_terminal_error_PRBS_seed46.png
PRBS seed=42 | label=high_terminal_error | /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_iid_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed42/rollout_benchmark/phase1a_iideval_traj6_seed42_20260425_155334/nominal_eval/diagnostic_plots/high_terminal_error_PRBS_seed42.png
[eval] main_phnode_full_seed44
Starting rollout benchmark | checkpoint=/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_iid_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed44/best_model.pt | device=cuda | mode=resampled | noise_profile=clean | noise_protocol=clean | noise_budget=protocol=clean | profile=clean | ref=remus100_dr | epoch_scale=0.000 | mix_ratio=0.000 | nu_r_lin_floor[u=0.0000, v=0.0000, w=0.0000] | nu_r_lin_ratio[u=0.0000, v=0.0000, w=0.0000] | nu_r_ang[p=0.0000, q=0.0000, r=0.0000] | rot[roll=0.0000, pitch=0.0000, yaw=0.0000] | scenarios=PRBS,CHIRP,OU | trajectories=18 | max_horizon=60.0s | output_dir=/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_iid_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed44/rollout_benchmark/phase1a_iideval_traj6_seed42_20260425_155756/clean
[scenario 1/3] PRBS | 6 trajectories
[1/18] PRBS seed=42 done | reason=completed | sim_time=60.00s | eta=16m37.0s
[5/18] PRBS seed=46 done | reason=completed | sim_time=60.00s | eta=2m32.5s
[6/18] PRBS seed=47 done | reason=completed | sim_time=60.00s | eta=1m57.3s
[scenario done] PRBS | completed=6/6 | gt_div=0 | model_fail=0 | H=60.0s cond_n=6/6 | pos_med=1.5088 m | pos_p95=2.4471 m | rot_med=0.0361 rad | completion=1.000 | elapsed=58.7s
[scenario 2/3] CHIRP | 6 trajectories
[7/18] CHIRP seed=100042 done | reason=completed | sim_time=60.00s | eta=3m05.5s
[11/18] CHIRP seed=100046 done | reason=completed | sim_time=60.00s | eta=1m15.1s
[12/18] CHIRP seed=100047 done | reason=completed | sim_time=60.00s | eta=59.0s
[scenario done] CHIRP | completed=6/6 | gt_div=0 | model_fail=0 | H=60.0s cond_n=6/6 | pos_med=0.6325 m | pos_p95=1.0116 m | rot_med=0.0128 rad | completion=1.000 | elapsed=1m58.1s
[scenario 3/3] OU | 6 trajectories
[13/18] OU seed=200042 done | reason=completed | sim_time=60.00s | eta=1m08.2s
[17/18] OU seed=200046 done | reason=completed | sim_time=60.00s | eta=10.4s
[18/18] OU seed=200047 done | reason=completed | sim_time=60.00s | eta=0.0s
[scenario done] OU | completed=6/6 | gt_div=0 | model_fail=0 | H=60.0s cond_n=6/6 | pos_med=1.3809 m | pos_p95=2.7894 m | rot_med=0.0393 rad | completion=1.000 | elapsed=2m57.3s
Benchmark finished in 3m10.7s
Results written to /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_iid_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed44/rollout_benchmark/phase1a_iideval_traj6_seed42_20260425_155756/clean
Rollout Benchmark Summary
================================================================================
Checkpoint: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_iid_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed44/best_model.pt
Dataset: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_5/data/auv_oc_traj1000_blk150_s23_d0be9434.pkl
Model: pH NODE Full [main/core]
Canonical model type: phnode_full
Energy semantics: mechanical_energy
Device: cuda
Mode: resampled
Generation config source: checkpoint
Scenarios: PRBS, CHIRP, OU
Trajectories per scenario: 6
Horizons: 10.0, 30.0, 60.0

Overall
--------------------------------------------------------------------------------
Conditional error statistics use only trajectories that completed to the horizon.
Primary KPIs are observable-space fields: position, depth, rotation, and total velocity.
Model-space diagnostics use relative velocity; internal diagnostics cover energy and raw SO(3) quality.
Per-column field grouping is exported in metric_contract.csv.
H=10.0s | pos median=0.1153 m | pos p95=0.3434 m | rot median=0.0085 rad | total vel median=0.0090 m/s | rel vel median=0.0095 m/s | cond_n=18/18 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
H=30.0s | pos median=0.3727 m | pos p95=0.9360 m | rot median=0.0144 rad | total vel median=0.0095 m/s | rel vel median=0.0082 m/s | cond_n=18/18 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
H=60.0s | pos median=1.0332 m | pos p95=2.7100 m | rot median=0.0294 rad | total vel median=0.0226 m/s | rel vel median=0.0124 m/s | cond_n=18/18 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000

Rollout Outcomes To Max Horizon
--------------------------------------------------------------------------------
n=18 | completed=18 (1.000) | gt_divergence=0 (0.000) | pred_divergence=0 (0.000) | solver_failure=0 (0.000) | nan_or_inf=0 (0.000)

By Scenario
--------------------------------------------------------------------------------
PRBS
  n=6 | completed=6 (1.000) | gt_divergence=0 (0.000) | pred_divergence=0 (0.000) | solver_failure=0 (0.000) | nan_or_inf=0 (0.000)
  H=10.0s | pos median=0.1018 m | pos p95=0.3137 m | rot median=0.0092 rad | total vel median=0.0073 m/s | rel vel median=0.0086 m/s | cond_n=6/6 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
  H=30.0s | pos median=0.4324 m | pos p95=0.8810 m | rot median=0.0142 rad | total vel median=0.0108 m/s | rel vel median=0.0076 m/s | cond_n=6/6 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
  H=60.0s | pos median=1.5088 m | pos p95=2.4471 m | rot median=0.0361 rad | total vel median=0.0292 m/s | rel vel median=0.0120 m/s | cond_n=6/6 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000

CHIRP
  n=6 | completed=6 (1.000) | gt_divergence=0 (0.000) | pred_divergence=0 (0.000) | solver_failure=0 (0.000) | nan_or_inf=0 (0.000)
  H=10.0s | pos median=0.1002 m | pos p95=0.1313 m | rot median=0.0054 rad | total vel median=0.0085 m/s | rel vel median=0.0078 m/s | cond_n=6/6 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
  H=30.0s | pos median=0.2490 m | pos p95=0.4223 m | rot median=0.0094 rad | total vel median=0.0063 m/s | rel vel median=0.0070 m/s | cond_n=6/6 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
  H=60.0s | pos median=0.6325 m | pos p95=1.0116 m | rot median=0.0128 rad | total vel median=0.0078 m/s | rel vel median=0.0099 m/s | cond_n=6/6 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000

OU
  n=6 | completed=6 (1.000) | gt_divergence=0 (0.000) | pred_divergence=0 (0.000) | solver_failure=0 (0.000) | nan_or_inf=0 (0.000)
  H=10.0s | pos median=0.2156 m | pos p95=0.3319 m | rot median=0.0128 rad | total vel median=0.0166 m/s | rel vel median=0.0165 m/s | cond_n=6/6 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
  H=30.0s | pos median=0.4471 m | pos p95=0.9089 m | rot median=0.0199 rad | total vel median=0.0134 m/s | rel vel median=0.0142 m/s | cond_n=6/6 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
  H=60.0s | pos median=1.3809 m | pos p95=2.7894 m | rot median=0.0393 rad | total vel median=0.0323 m/s | rel vel median=0.0311 m/s | cond_n=6/6 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000

Diagnostic Cases To Max Horizon
--------------------------------------------------------------------------------
Largest completed terminal errors
  OU seed=200045 | reason=completed | sim_time=60.00s | pos=2.8225 m | rot=0.0538 rad | total_vel_violation=0
  OU seed=200043 | reason=completed | sim_time=60.00s | pos=2.6901 m | rot=0.0802 rad | total_vel_violation=0
  PRBS seed=42 | reason=completed | sim_time=60.00s | pos=2.6346 m | rot=0.0414 rad | total_vel_violation=0
  PRBS seed=43 | reason=completed | sim_time=60.00s | pos=1.8846 m | rot=0.0309 rad | total_vel_violation=0
  OU seed=200047 | reason=completed | sim_time=60.00s | pos=1.7884 m | rot=0.0301 rad | total_vel_violation=0

Diagnostic Plot Files
--------------------------------------------------------------------------------
OU seed=200045 | label=high_terminal_error | /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_iid_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed44/rollout_benchmark/phase1a_iideval_traj6_seed42_20260425_155756/clean/diagnostic_plots/high_terminal_error_OU_seed200045.png
OU seed=200043 | label=high_terminal_error | /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_iid_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed44/rollout_benchmark/phase1a_iideval_traj6_seed42_20260425_155756/clean/diagnostic_plots/high_terminal_error_OU_seed200043.png
Starting rollout benchmark | checkpoint=/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_iid_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed44/best_model.pt | device=cuda | mode=resampled | noise_profile=nominal_eval | noise_protocol=iid_noisy_ic | noise_budget=protocol=iid_noisy_ic | profile=nominal_eval | ref=remus100_dr | epoch_scale=1.000 | mix_ratio=0.500 | nu_r_lin_floor[u=0.0030, v=0.0030, w=0.0040] | nu_r_lin_ratio[u=0.0030, v=0.0030, w=0.0030] | nu_r_ang[p=0.0008, q=0.0008, r=0.0015] | rot[roll=0.0020, pitch=0.0020, yaw=0.0100] | scenarios=PRBS,CHIRP,OU | trajectories=18 | max_horizon=60.0s | output_dir=/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_iid_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed44/rollout_benchmark/phase1a_iideval_traj6_seed42_20260425_155756/nominal_eval
[scenario 1/3] PRBS | 6 trajectories
[1/18] PRBS seed=42 done | reason=completed | sim_time=60.00s | eta=5m28.8s
[5/18] PRBS seed=46 done | reason=completed | sim_time=60.00s | eta=50.3s
[6/18] PRBS seed=47 done | reason=completed | sim_time=60.00s | eta=38.7s
[scenario done] PRBS | completed=6/6 | gt_div=0 | model_fail=0 | H=60.0s cond_n=6/6 | pos_med=1.2364 m | pos_p95=2.7280 m | rot_med=0.0279 rad | completion=1.000 | elapsed=19.4s
[scenario 2/3] CHIRP | 6 trajectories
[7/18] CHIRP seed=100042 done | reason=completed | sim_time=60.00s | eta=1m00.9s
[11/18] CHIRP seed=100046 done | reason=completed | sim_time=60.00s | eta=24.7s
[12/18] CHIRP seed=100047 done | reason=completed | sim_time=60.00s | eta=19.4s
[scenario done] CHIRP | completed=6/6 | gt_div=0 | model_fail=0 | H=60.0s cond_n=6/6 | pos_med=0.6178 m | pos_p95=0.9868 m | rot_med=0.0118 rad | completion=1.000 | elapsed=38.8s
[scenario 3/3] OU | 6 trajectories
[13/18] OU seed=200042 done | reason=completed | sim_time=60.00s | eta=22.3s

In [ ]:
import shutil
from pathlib import Path

run_tag = "phase1a_oc_v4lite_cleanrun_v1"
proxy = Path("/content/_proxy_suites") / f"sweep_oc_phase1a_smoke3_proxy_{run_tag}"

if proxy.exists():
    shutil.rmtree(proxy)
    print("removed partial proxy:", proxy)
else:
    print("no partial proxy found")

no partial proxy found

In [ ]:
import os
os.environ["MODE"] = "smoke3_eval"
!bash scripts/run_phase1a_oc_v4lite.sh

[phase1a]
MODE=smoke3_eval
RUN_TAG=phase1a_oc_v4lite_cleanrun_v1
DATASET=/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/data/auv_oc_traj1000_blk150_s23_d0be9434.pkl
DEVICE=cuda
PHASE1A_MODELS=phnode_full ablate_no_mass_prior ablate_no_lift
SMOKE1_MODELS=phnode_full
SMOKE_SEEDS=42 44 46
DECISION_SEEDS=42 43 44 45 46
NOISE_REFERENCE=remus100_dr
PHASE1A_LOG_DIR=/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/phase1a_logs/phase1a_oc_v4lite_cleanrun_v1
PHASE1A_METADATA_DIR=/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/phase1a_metadata_phase1a_oc_v4lite_cleanrun_v1
[eval] suite=sweep_oc_phase1a_smoke3_clean_phase1a_oc_v4lite_cleanrun_v1 eval_protocol=iid_noisy_ic profiles=clean nominal_eval
Suite directory: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_clean_phase1a_oc_v4lite_cleanrun_v1
Manifest: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_clean_phase1a_oc_v4lite_cleanrun_v1/runs.tsv
Mode: resampled
[skip] main_phnode_full_seed42 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_clean_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed42/rollout_benchmark
[skip] main_phnode_full_seed44 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_clean_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed44/rollout_benchmark
[skip] main_phnode_full_seed46 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_clean_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed46/rollout_benchmark
[skip] ablation_ablate_no_mass_prior_seed42 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_clean_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_mass_prior_seed42/rollout_benchmark
[skip] ablation_ablate_no_mass_prior_seed44 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_clean_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_mass_prior_seed44/rollout_benchmark
[skip] ablation_ablate_no_mass_prior_seed46 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_clean_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_mass_prior_seed46/rollout_benchmark
[skip] ablation_ablate_no_lift_seed42 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_clean_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_lift_seed42/rollout_benchmark
[skip] ablation_ablate_no_lift_seed44 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_clean_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_lift_seed44/rollout_benchmark
[skip] ablation_ablate_no_lift_seed46 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_clean_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_lift_seed46/rollout_benchmark
Batch evaluation complete.
[eval] suite=sweep_oc_phase1a_smoke3_iid_phase1a_oc_v4lite_cleanrun_v1 eval_protocol=iid_noisy_ic profiles=clean nominal_eval
Suite directory: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_iid_phase1a_oc_v4lite_cleanrun_v1
Manifest: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_iid_phase1a_oc_v4lite_cleanrun_v1/runs.tsv
Mode: resampled
[skip] main_phnode_full_seed42 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_iid_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed42/rollout_benchmark
[skip] main_phnode_full_seed44 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_iid_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed44/rollout_benchmark
[skip] main_phnode_full_seed46 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_iid_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed46/rollout_benchmark
[skip] ablation_ablate_no_mass_prior_seed42 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_iid_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_mass_prior_seed42/rollout_benchmark
[skip] ablation_ablate_no_mass_prior_seed44 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_iid_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_mass_prior_seed44/rollout_benchmark
[skip] ablation_ablate_no_mass_prior_seed46 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_iid_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_mass_prior_seed46/rollout_benchmark
[skip] ablation_ablate_no_lift_seed42 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_iid_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_lift_seed42/rollout_benchmark
[skip] ablation_ablate_no_lift_seed44 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_iid_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_lift_seed44/rollout_benchmark
[skip] ablation_ablate_no_lift_seed46 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_iid_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_lift_seed46/rollout_benchmark
Batch evaluation complete.
[eval] suite=sweep_oc_phase1a_smoke3_v4lite_phase1a_oc_v4lite_cleanrun_v1 eval_protocol=iid_noisy_ic profiles=clean nominal_eval
Suite directory: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_v4lite_phase1a_oc_v4lite_cleanrun_v1
Manifest: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_v4lite_phase1a_oc_v4lite_cleanrun_v1/runs.tsv
Mode: resampled
[skip] main_phnode_full_seed42 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_v4lite_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed42/rollout_benchmark
[skip] main_phnode_full_seed44 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_v4lite_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed44/rollout_benchmark
[skip] main_phnode_full_seed46 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_v4lite_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed46/rollout_benchmark
[skip] ablation_ablate_no_mass_prior_seed42 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_v4lite_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_mass_prior_seed42/rollout_benchmark
[skip] ablation_ablate_no_mass_prior_seed44 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_v4lite_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_mass_prior_seed44/rollout_benchmark
[skip] ablation_ablate_no_mass_prior_seed46 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_v4lite_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_mass_prior_seed46/rollout_benchmark
[skip] ablation_ablate_no_lift_seed42 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_v4lite_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_lift_seed42/rollout_benchmark
[skip] ablation_ablate_no_lift_seed44 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_v4lite_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_lift_seed44/rollout_benchmark
[skip] ablation_ablate_no_lift_seed46 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_v4lite_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_lift_seed46/rollout_benchmark
Batch evaluation complete.
[eval] suite=sweep_oc_phase1a_smoke3_clean_phase1a_oc_v4lite_cleanrun_v1 eval_protocol=v4_lite profiles=nominal_eval
Suite directory: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_clean_phase1a_oc_v4lite_cleanrun_v1
Manifest: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_clean_phase1a_oc_v4lite_cleanrun_v1/runs.tsv
Mode: resampled
[skip] main_phnode_full_seed42 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_clean_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed42/rollout_benchmark
[skip] main_phnode_full_seed44 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_clean_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed44/rollout_benchmark
[skip] main_phnode_full_seed46 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_clean_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed46/rollout_benchmark
[skip] ablation_ablate_no_mass_prior_seed42 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_clean_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_mass_prior_seed42/rollout_benchmark
[skip] ablation_ablate_no_mass_prior_seed44 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_clean_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_mass_prior_seed44/rollout_benchmark
[skip] ablation_ablate_no_mass_prior_seed46 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_clean_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_mass_prior_seed46/rollout_benchmark
[skip] ablation_ablate_no_lift_seed42 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_clean_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_lift_seed42/rollout_benchmark
[skip] ablation_ablate_no_lift_seed44 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_clean_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_lift_seed44/rollout_benchmark
[skip] ablation_ablate_no_lift_seed46 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_clean_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_lift_seed46/rollout_benchmark
Batch evaluation complete.
[eval] suite=sweep_oc_phase1a_smoke3_iid_phase1a_oc_v4lite_cleanrun_v1 eval_protocol=v4_lite profiles=nominal_eval
Suite directory: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_iid_phase1a_oc_v4lite_cleanrun_v1
Manifest: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_iid_phase1a_oc_v4lite_cleanrun_v1/runs.tsv
Mode: resampled
[skip] main_phnode_full_seed42 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_iid_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed42/rollout_benchmark
[skip] main_phnode_full_seed44 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_iid_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed44/rollout_benchmark
[skip] main_phnode_full_seed46 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_iid_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed46/rollout_benchmark
[skip] ablation_ablate_no_mass_prior_seed42 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_iid_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_mass_prior_seed42/rollout_benchmark
[skip] ablation_ablate_no_mass_prior_seed44 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_iid_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_mass_prior_seed44/rollout_benchmark
[skip] ablation_ablate_no_mass_prior_seed46 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_iid_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_mass_prior_seed46/rollout_benchmark
[skip] ablation_ablate_no_lift_seed42 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_iid_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_lift_seed42/rollout_benchmark
[skip] ablation_ablate_no_lift_seed44 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_iid_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_lift_seed44/rollout_benchmark
[skip] ablation_ablate_no_lift_seed46 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_iid_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_lift_seed46/rollout_benchmark
Batch evaluation complete.
[eval] suite=sweep_oc_phase1a_smoke3_v4lite_phase1a_oc_v4lite_cleanrun_v1 eval_protocol=v4_lite profiles=nominal_eval
Suite directory: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_v4lite_phase1a_oc_v4lite_cleanrun_v1
Manifest: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_v4lite_phase1a_oc_v4lite_cleanrun_v1/runs.tsv
Mode: resampled
[skip] main_phnode_full_seed42 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_v4lite_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed42/rollout_benchmark
[skip] main_phnode_full_seed44 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_v4lite_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed44/rollout_benchmark
[skip] main_phnode_full_seed46 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_v4lite_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed46/rollout_benchmark
[skip] ablation_ablate_no_mass_prior_seed42 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_v4lite_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_mass_prior_seed42/rollout_benchmark
[skip] ablation_ablate_no_mass_prior_seed44 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_v4lite_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_mass_prior_seed44/rollout_benchmark
[skip] ablation_ablate_no_mass_prior_seed46 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_v4lite_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_mass_prior_seed46/rollout_benchmark
[skip] ablation_ablate_no_lift_seed42 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_v4lite_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_lift_seed42/rollout_benchmark
[skip] ablation_ablate_no_lift_seed44 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_v4lite_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_lift_seed44/rollout_benchmark
[skip] ablation_ablate_no_lift_seed46 already evaluated under /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_v4lite_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_lift_seed46/rollout_benchmark
Batch evaluation complete.

## 6. Decision train + protocol validation

正式 Phase-1A decision matrix：三模型 × seeds `42/43/44/45/46` × `clean/iid_noisy_ic/v4_lite`。

In [ ]:
os.environ["MODE"] = "decision_train"
!bash scripts/run_phase1a_oc_v4lite.sh

[phase1a]
MODE=decision_train
RUN_TAG=phase1a_oc_v4lite_cleanrun_v1
DATASET=/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/data/auv_oc_traj1000_blk150_s23_d0be9434.pkl
DEVICE=cuda
PHASE1A_MODELS=phnode_full ablate_no_mass_prior ablate_no_lift
SMOKE1_MODELS=phnode_full
SMOKE_SEEDS=42 44 46
DECISION_SEEDS=42 43 44 45 46
NOISE_REFERENCE=remus100_dr
PHASE1A_LOG_DIR=/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/phase1a_logs/phase1a_oc_v4lite_cleanrun_v1
PHASE1A_METADATA_DIR=/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/phase1a_metadata_phase1a_oc_v4lite_cleanrun_v1
[train] suite=sweep_oc_phase1a_decision_clean_phase1a_oc_v4lite_cleanrun_v1 models=phnode_full ablate_no_mass_prior ablate_no_lift seeds=42 43 44 45 46 protocol=auto
Training all models with profile-based noisy IC.
Dataset: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/data/auv_oc_traj1000_blk150_s23_d0be9434.pkl
Group: all
Explicit models: phnode_full ablate_no_mass_prior ablate_no_lift
Seeds: 42 43 44 45 46
Noise config: protocol=auto, profile=clean, scale=1.0, warmup=20, ramp=80, mix_ratio=0.5
Auto-eval profiles: block=[clean nominal_eval heading_biased_eval] heldout=[clean nominal_eval degraded_eval heading_biased_eval]
Suite directory: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_clean_phase1a_oc_v4lite_cleanrun_v1
Dataset: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/data/auv_oc_traj1000_blk150_s23_d0be9434.pkl
Models (3): phnode_full ablate_no_mass_prior ablate_no_lift
Seeds: 42 43 44 45 46
[train] main_phnode_full_seed42
Loading dataset...
Loaded: 83850 train, 21000 test, t_eval=[0.   0.05 0.1  0.15 0.2 ]
Dataset split: trajectory | train trajectories: 559 | test trajectories: 140
Dataset ID: d0be9434
Dataset path: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_5/data/auv_oc_traj1000_blk150_s23_d0be9434.pkl | velocity convention: body_total | state dim: 27
Position std: [0.1508, 0.1400, 0.0370]
Velocity std: u=0.4722, v=0.0898, w=0.0718, p=0.0248, q=0.0906, r=0.0526
Actuator std: a0=0.1543, a1=0.1555, a2=299.0037
Training noise budget: protocol=clean | profile=clean | ref=remus100_dr | epoch_scale=0.000 | mix_ratio=0.500 | nu_r_lin_floor[u=0.0000, v=0.0000, w=0.0000] | nu_r_lin_ratio[u=0.0000, v=0.0000, w=0.0000] | nu_r_ang[p=0.0000, q=0.0000, r=0.0000] | rot[roll=0.0000, pitch=0.0000, yaw=0.0000]
Model: pH NODE Full [main/core] | canonical type: phnode_full
Model parameters: 62,803
Training dataset: id=d0be9434 | path=/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_5/data/auv_oc_traj1000_blk150_s23_d0be9434.pkl
Mass matrix initialized from physics
Training: epochs<=300, target_steps=5000, warmup_steps=400, lr=6.00e-03 -> 1.00e-04, solver=rk4, so3_reg=1.00e-03
Train samples: 83850, Test samples: 21000
Epoch    1 | Step    20/ 5000 | Train 4.3508e+00 | Test 5.0458e+00 | SO3(train/test) 1.26e-07/1.27e-07 | Fail(train/test) 0/0 | LR 4.10e-04 | 6.4s
Epoch    2 | Step    40/ 5000 | Train 3.5849e+00 | Test 4.3046e+00 | SO3(train/test) 1.19e-07/1.20e-07 | Fail(train/test) 0/0 | LR 7.05e-04 | 5.9s
Epoch    3 | Step    60/ 5000 | Train 2.9504e+00 | Test 3.2210e+00 | SO3(train/test) 1.16e-07/1.16e-07 | Fail(train/test) 0/0 | LR 1.00e-03 | 5.8s
Epoch    4 | Step    80/ 5000 | Train 1.7819e+00 | Test 1.0436e+00 | SO3(train/test) 1.20e-07/1.49e-07 | Fail(train/test) 0/0 | LR 1.29e-03 | 5.9s
Epoch    5 | Step   100/ 5000 | Train 7.7154e-01 | Test 6.1857e-01 | SO3(train/test) 1.29e-07/1.15e-07 | Fail(train/test) 0/0 | LR 1.59e-03 | 5.9s
Epoch    6 | Step   120/ 5000 | Train 7.3271e-01 | Test 7.2985e-01 | SO3(train/test) 1.15e-07/1.16e-07 | Fail(train/test) 0/0 | LR 1.88e-03 | 5.9s
Epoch    7 | Step   140/ 5000 | Train 7.3189e-01 | Test 7.0204e-01 | SO3(train/test) 1.19e-07/1.23e-07 | Fail(train/test) 0/0 | LR 2.18e-03 | 5.9s
Epoch    8 | Step   160/ 5000 | Train 9.1646e-01 | Test 1.3657e+00 | SO3(train/test) 1.88e-07/4.19e-07 | Fail(train/test) 0/0 | LR 2.47e-03 | 6.0s
Epoch    9 | Step   180/ 5000 | Train 6.4671e-01 | Test 4.2992e-01 | SO3(train/test) 2.93e-07/1.80e-07 | Fail(train/test) 0/0 | LR 2.77e-03 | 6.1s
Epoch   10 | Step   200/ 5000 | Train 4.0102e-01 | Test 3.2272e-01 | SO3(train/test) 1.32e-07/1.17e-07 | Fail(train/test) 0/0 | LR 3.06e-03 | 5.9s

In [ ]:
# 只补训 43/45

!export RUN_TAG=phase1a_oc_v4lite_cleanrun_v1
!export DATASET=data/auv_oc_traj1000_blk150_s23_d0be9434.pkl
!export DEVICE=cuda
!export NOISE_REFERENCE=remus100_dr
!export PHASE1A_MODELS="phnode_full ablate_no_mass_prior ablate_no_lift"

!bash scripts/train_all_models_noise_profile.sh \
  --profile oc \
  --models "${PHASE1A_MODELS}" \
  --dataset "${DATASET}" \
  --seeds "43 45" \
  --suite-name "sweep_oc_phase1a_decision_extra43-45_clean_${RUN_TAG}" \
  --noise-profile clean \
  --noise-protocol auto \
  --noise-reference "${NOISE_REFERENCE}" \
  --block-eval-noise-profiles clean \
  --heldout-eval-noise-profiles clean \
  --device "${DEVICE}"

!bash scripts/train_all_models_noise_profile.sh \
  --profile oc \
  --models "${PHASE1A_MODELS}" \
  --dataset "${DATASET}" \
  --seeds "43 45" \
  --suite-name "sweep_oc_phase1a_decision_extra43-45_iid_${RUN_TAG}" \
  --noise-profile nominal_train \
  --noise-protocol iid_noisy_ic \
  --noise-reference "${NOISE_REFERENCE}" \
  --block-eval-noise-profiles clean \
  --heldout-eval-noise-profiles clean \
  --device "${DEVICE}"

!bash scripts/train_all_models_noise_profile.sh \
  --profile oc \
  --models "${PHASE1A_MODELS}" \
  --dataset "${DATASET}" \
  --seeds "43 45" \
  --suite-name "sweep_oc_phase1a_decision_extra43-45_v4lite_${RUN_TAG}" \
  --noise-profile nominal_train \
  --noise-protocol v4_lite \
  --noise-reference "${NOISE_REFERENCE}" \
  --block-eval-noise-profiles clean \
  --heldout-eval-noise-profiles clean \
  --device "${DEVICE}"

Training all models with profile-based noisy IC.
Dataset: data/auv_oc_traj1000_blk150_s23_d0be9434.pkl
Group: all
Explicit models: phnode_full ablate_no_mass_prior ablate_no_lift
Seeds: 43 45
Noise config: protocol=auto, profile=clean, scale=1.0, warmup=20, ramp=80, mix_ratio=0.5
Auto-eval profiles: block=[clean] heldout=[clean]
Suite directory: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_clean_phase1a_oc_v4lite_cleanrun_v1
Dataset: data/auv_oc_traj1000_blk150_s23_d0be9434.pkl
Models (3): phnode_full ablate_no_mass_prior ablate_no_lift
Seeds: 43 45
[skip] main_phnode_full_seed43 already exists at /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_clean_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed43/best_model.pt
[skip] main_phnode_full_seed45 already exists at /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_clean_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed45/best_model.pt
[skip] ablation_ablate_no_mass_prior_seed43 already exists at /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_clean_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_mass_prior_seed43/best_model.pt
[skip] ablation_ablate_no_mass_prior_seed45 already exists at /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_clean_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_mass_prior_seed45/best_model.pt
[skip] ablation_ablate_no_lift_seed43 already exists at /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_clean_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_lift_seed43/best_model.pt
[skip] ablation_ablate_no_lift_seed45 already exists at /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_clean_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_lift_seed45/best_model.pt
Training sweep complete.
Manifest: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_clean_phase1a_oc_v4lite_cleanrun_v1/runs.tsv
Next step:
  scripts/batch_eval_models.sh --suite-dir "/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_clean_phase1a_oc_v4lite_cleanrun_v1"

Training complete.
Suite directory: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_clean_phase1a_oc_v4lite_cleanrun_v1
Next step:
  bash scripts/eval_all_models_noise_profile.sh --suite-dir "/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_clean_phase1a_oc_v4lite_cleanrun_v1"
Training all models with profile-based noisy IC.
Dataset: data/auv_oc_traj1000_blk150_s23_d0be9434.pkl
Group: all
Explicit models: phnode_full ablate_no_mass_prior ablate_no_lift
Seeds: 43 45
Noise config: protocol=iid_noisy_ic, profile=nominal_train, scale=1.0, warmup=20, ramp=80, mix_ratio=0.5
Auto-eval profiles: block=[clean] heldout=[clean]
Suite directory: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_iid_phase1a_oc_v4lite_cleanrun_v1
Dataset: data/auv_oc_traj1000_blk150_s23_d0be9434.pkl
Models (3): phnode_full ablate_no_mass_prior ablate_no_lift
Seeds: 43 45
[skip] main_phnode_full_seed43 already exists at /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_iid_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed43/best_model.pt
[skip] main_phnode_full_seed45 already exists at /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_iid_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed45/best_model.pt
[skip] ablation_ablate_no_mass_prior_seed43 already exists at /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_iid_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_mass_prior_seed43/best_model.pt
[skip] ablation_ablate_no_mass_prior_seed45 already exists at /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_iid_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_mass_prior_seed45/best_model.pt
[skip] ablation_ablate_no_lift_seed43 already exists at /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_iid_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_lift_seed43/best_model.pt
[skip] ablation_ablate_no_lift_seed45 already exists at /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_iid_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_lift_seed45/best_model.pt
Training sweep complete.
Manifest: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_iid_phase1a_oc_v4lite_cleanrun_v1/runs.tsv
Next step:
  scripts/batch_eval_models.sh --suite-dir "/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_iid_phase1a_oc_v4lite_cleanrun_v1"

Training complete.
Suite directory: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_iid_phase1a_oc_v4lite_cleanrun_v1
Next step:
  bash scripts/eval_all_models_noise_profile.sh --suite-dir "/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_iid_phase1a_oc_v4lite_cleanrun_v1"
Training all models with profile-based noisy IC.
Dataset: data/auv_oc_traj1000_blk150_s23_d0be9434.pkl
Group: all
Explicit models: phnode_full ablate_no_mass_prior ablate_no_lift
Seeds: 43 45
Noise config: protocol=v4_lite, profile=nominal_train, scale=1.0, warmup=20, ramp=80, mix_ratio=0.5
Auto-eval profiles: block=[clean] heldout=[clean]
Suite directory: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_v4lite_phase1a_oc_v4lite_cleanrun_v1
Dataset: data/auv_oc_traj1000_blk150_s23_d0be9434.pkl
Models (3): phnode_full ablate_no_mass_prior ablate_no_lift
Seeds: 43 45
[skip] main_phnode_full_seed43 already exists at /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_v4lite_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed43/best_model.pt
[skip] main_phnode_full_seed45 already exists at /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_v4lite_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed45/best_model.pt
[skip] ablation_ablate_no_mass_prior_seed43 already exists at /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_v4lite_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_mass_prior_seed43/best_model.pt
[skip] ablation_ablate_no_mass_prior_seed45 already exists at /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_v4lite_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_mass_prior_seed45/best_model.pt
[skip] ablation_ablate_no_lift_seed43 already exists at /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_v4lite_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_lift_seed43/best_model.pt
[skip] ablation_ablate_no_lift_seed45 already exists at /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_v4lite_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_lift_seed45/best_model.pt
Training sweep complete.
Manifest: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_v4lite_phase1a_oc_v4lite_cleanrun_v1/runs.tsv
Next step:
  scripts/batch_eval_models.sh --suite-dir "/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_v4lite_phase1a_oc_v4lite_cleanrun_v1"

Training complete.
Suite directory: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_v4lite_phase1a_oc_v4lite_cleanrun_v1
Next step:
  bash scripts/eval_all_models_noise_profile.sh --suite-dir "/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_v4lite_phase1a_oc_v4lite_cleanrun_v1"

In [ ]:
# 注册五 seed decision suite

from pathlib import Path
import os
import pandas as pd

run_tag = os.environ.get("RUN_TAG", "phase1a_oc_v4lite_cleanrun_v1")
root = Path.cwd()
ckpt = root / "checkpoints"

models = {"phnode_full", "ablate_no_mass_prior", "ablate_no_lift"}
smoke_seeds = {42, 44, 46}
extra_seeds = {43, 45}
decision_seeds = {42, 43, 44, 45, 46}

def suite_path(phase, protocol):
    path = ckpt / f"sweep_oc_phase1a_{phase}_{protocol}_{run_tag}"
    if not path.is_dir():
        raise FileNotFoundError(f"Missing suite: {path}")
    if not (path / "runs.tsv").is_file():
        raise FileNotFoundError(f"Missing manifest: {path / 'runs.tsv'}")
    return path

def read_runs(suite_dir):
    runs = pd.read_csv(suite_dir / "runs.tsv", sep="\t")
    runs["seed"] = runs["seed"].astype(int)
    return runs

def validate_suite(suite_dir, expected_seeds):
    runs = read_runs(suite_dir)
    got_models = set(runs["model_type"])
    got_seeds = set(runs["seed"])
    if got_models != models:
        raise ValueError(f"{suite_dir.name}: model mismatch: {got_models}")
    if got_seeds != expected_seeds:
        raise ValueError(f"{suite_dir.name}: seed mismatch: {got_seeds}")
    expected_n = len(models) * len(expected_seeds)
    if len(runs) != expected_n:
        raise ValueError(f"{suite_dir.name}: expected {expected_n} runs, got {len(runs)}")
    missing_ckpt = [p for p in runs["checkpoint"] if not Path(p).is_file()]
    if missing_ckpt:
        raise FileNotFoundError(f"{suite_dir.name}: missing checkpoints: {missing_ckpt[:3]}")
    print(f"[ok] {suite_dir.name}: {len(runs)} runs")
    return runs

for protocol in ["clean", "iid", "v4lite"]:
    validate_suite(suite_path("smoke3", protocol), smoke_seeds)

for protocol in ["clean", "iid", "v4lite"]:
    validate_suite(suite_path("decision_extra43-45", protocol), extra_seeds)

for protocol in ["clean", "iid", "v4lite"]:
    smoke_suite = suite_path("smoke3", protocol)
    extra_suite = suite_path("decision_extra43-45", protocol)
    target_suite = ckpt / f"sweep_oc_phase1a_decision_{protocol}_{run_tag}"

    if target_suite.exists():
        raise FileExistsError(f"Refusing to overwrite existing suite: {target_suite}")

    rows = pd.concat([
        read_runs(smoke_suite).query("seed in @smoke_seeds"),
        read_runs(extra_suite).query("seed in @extra_seeds"),
    ], ignore_index=True)

    if set(rows["seed"]) != decision_seeds:
        raise ValueError(f"{protocol}: decision seed mismatch: {set(rows['seed'])}")

    target_suite.mkdir(parents=True)
    out_rows = []

    for _, row in rows.iterrows():
        source_run_dir = Path(row["run_dir"]).resolve()
        proxy_run_dir = target_suite / row["run_name"]
        proxy_run_dir.mkdir(parents=True)

        for child in source_run_dir.iterdir():
            if child.name == "rollout_benchmark":
                continue
            link = proxy_run_dir / child.name
            link.symlink_to(child.resolve(), target_is_directory=child.is_dir())

        out_rows.append({
            "group": row["group"],
            "model_type": row["model_type"],
            "seed": int(row["seed"]),
            "run_name": row["run_name"],
            "run_dir": str(proxy_run_dir),
            "checkpoint": str(proxy_run_dir / "best_model.pt"),
        })

    out = pd.DataFrame(out_rows).sort_values(["group", "model_type", "seed"])
    out.to_csv(target_suite / "runs.tsv", sep="\t", index=False)
    (target_suite / "suite_config.txt").write_text(
        f"Suite: {target_suite.name}\n"
        f"Type: decision proxy from smoke3 seeds 42/44/46 + extra seeds 43/45\n"
        f"Protocol: {protocol}\n",
        encoding="utf-8",
    )
    print(f"[registered] {target_suite.name}: {len(out)} runs")

[ok] sweep_oc_phase1a_smoke3_clean_phase1a_oc_v4lite_cleanrun_v1: 9 runs
[ok] sweep_oc_phase1a_smoke3_iid_phase1a_oc_v4lite_cleanrun_v1: 9 runs
[ok] sweep_oc_phase1a_smoke3_v4lite_phase1a_oc_v4lite_cleanrun_v1: 9 runs
[ok] sweep_oc_phase1a_decision_extra43-45_clean_phase1a_oc_v4lite_cleanrun_v1: 6 runs
[ok] sweep_oc_phase1a_decision_extra43-45_iid_phase1a_oc_v4lite_cleanrun_v1: 6 runs
[ok] sweep_oc_phase1a_decision_extra43-45_v4lite_phase1a_oc_v4lite_cleanrun_v1: 6 runs

OSError: [Errno 95] Operation not supported: '/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_clean_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed42/training.log' -> '/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_clean_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed42/training.log'

In [ ]:
from pathlib import Path
import pandas as pd

run_tag = "phase1a_oc_v4lite_cleanrun_v1"
ckpt = Path.cwd() / "checkpoints"

models = {"phnode_full", "ablate_no_mass_prior", "ablate_no_lift"}
decision_seeds = {42, 43, 44, 45, 46}

def inspect_decision_suite(protocol):
    suite = ckpt / f"sweep_oc_phase1a_decision_{protocol}_{run_tag}"
    if not suite.exists():
        return protocol, "missing", suite

    manifest = suite / "runs.tsv"
    if not manifest.exists():
        return protocol, "partial_missing_runs_tsv", suite

    runs = pd.read_csv(manifest, sep="\t")
    runs["seed"] = runs["seed"].astype(int)

    bad = []
    if set(runs["model_type"]) != models:
        bad.append(f"models={sorted(set(runs['model_type']))}")
    if set(runs["seed"]) != decision_seeds:
        bad.append(f"seeds={sorted(set(runs['seed']))}")
    if len(runs) != 15:
        bad.append(f"n_runs={len(runs)}")

    missing_ckpt = [p for p in runs["checkpoint"] if not Path(p).is_file()]
    if missing_ckpt:
        bad.append(f"missing_ckpt={len(missing_ckpt)}")

    if bad:
        return protocol, "partial_or_invalid: " + "; ".join(bad), suite
    return protocol, "ok", suite

statuses = [inspect_decision_suite(p) for p in ["clean", "iid", "v4lite"]]
for protocol, status, suite in statuses:
    print(f"[{status}] {protocol}: {suite}")

if all(status == "ok" for _, status, _ in statuses):
    print("\nAll decision suites are complete. Skip registration and continue to audit/eval.")
else:
    print("\nSome decision suites are missing or partial. Remove only the partial decision proxy suites, then rerun registration.")

[partial_or_invalid: models=[]; seeds=[]; n_runs=0] clean: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_clean_phase1a_oc_v4lite_cleanrun_v1
[missing] iid: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_iid_phase1a_oc_v4lite_cleanrun_v1
[missing] v4lite: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_v4lite_phase1a_oc_v4lite_cleanrun_v1

Some decision suites are missing or partial. Remove only the partial decision proxy suites, then rerun registration.

In [ ]:
import shutil
from pathlib import Path

run_tag = "phase1a_oc_v4lite_cleanrun_v1"
ckpt = Path.cwd() / "checkpoints"

# Only set protocols listed as partial_or_invalid or partial_missing_runs_tsv.
protocols_to_remove = ["clean"]  # edit this list based on the inspection output

for protocol in protocols_to_remove:
    suite = ckpt / f"sweep_oc_phase1a_decision_{protocol}_{run_tag}"
    if suite.exists():
        shutil.rmtree(suite)
        print("removed:", suite)

removed: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_clean_phase1a_oc_v4lite_cleanrun_v1

In [ ]:
from pathlib import Path
import shutil
import pandas as pd

run_tag = "phase1a_oc_v4lite_cleanrun_v1"
ckpt = Path.cwd() / "checkpoints"

models = {"phnode_full", "ablate_no_mass_prior", "ablate_no_lift"}
smoke_seeds = {42, 44, 46}
extra_seeds = {43, 45}
decision_seeds = {42, 43, 44, 45, 46}

def suite_path(phase, protocol):
    path = ckpt / f"sweep_oc_phase1a_{phase}_{protocol}_{run_tag}"
    if not path.is_dir():
        raise FileNotFoundError(f"Missing suite: {path}")
    if not (path / "runs.tsv").is_file():
        raise FileNotFoundError(f"Missing manifest: {path / 'runs.tsv'}")
    return path

def read_runs(suite_dir):
    runs = pd.read_csv(suite_dir / "runs.tsv", sep="\t")
    runs["seed"] = runs["seed"].astype(int)
    return runs

def validate_suite(suite_dir, expected_seeds):
    runs = read_runs(suite_dir)
    got_models = set(runs["model_type"])
    got_seeds = set(runs["seed"])

    if got_models != models:
        raise ValueError(f"{suite_dir.name}: model mismatch: {got_models}")
    if got_seeds != expected_seeds:
        raise ValueError(f"{suite_dir.name}: seed mismatch: {got_seeds}")

    expected_n = len(models) * len(expected_seeds)
    if len(runs) != expected_n:
        raise ValueError(f"{suite_dir.name}: expected {expected_n} runs, got {len(runs)}")

    missing = []
    for _, row in runs.iterrows():
        run_dir = Path(row["run_dir"])
        checkpoint = Path(row["checkpoint"])
        if not run_dir.is_dir():
            missing.append(f"run_dir: {run_dir}")
        if not checkpoint.is_file():
            missing.append(f"checkpoint: {checkpoint}")
    if missing:
        raise FileNotFoundError(f"{suite_dir.name}: missing paths:\n" + "\n".join(missing[:10]))

    print(f"[ok] {suite_dir.name}: {len(runs)} runs")
    return runs

for protocol in ["clean", "iid", "v4lite"]:
    validate_suite(suite_path("smoke3", protocol), smoke_seeds)

for protocol in ["clean", "iid", "v4lite"]:
    validate_suite(suite_path("decision_extra43-45", protocol), extra_seeds)

for protocol in ["clean", "iid", "v4lite"]:
    smoke_suite = suite_path("smoke3", protocol)
    extra_suite = suite_path("decision_extra43-45", protocol)
    target_suite = ckpt / f"sweep_oc_phase1a_decision_{protocol}_{run_tag}"

    # Safe to remove only this manifest-only/proxy target. Do not remove source suites.
    if target_suite.exists():
        shutil.rmtree(target_suite)

    rows = pd.concat([
        read_runs(smoke_suite).query("seed in @smoke_seeds"),
        read_runs(extra_suite).query("seed in @extra_seeds"),
    ], ignore_index=True)

    if set(rows["seed"]) != decision_seeds:
        raise ValueError(f"{protocol}: decision seed mismatch: {set(rows['seed'])}")
    if len(rows) != len(models) * len(decision_seeds):
        raise ValueError(f"{protocol}: expected 15 rows, got {len(rows)}")

    rows = rows.sort_values(["group", "model_type", "seed"]).copy()

    # Keep absolute pointers to the real run dirs/checkpoints. No symlinks.
    rows["run_dir"] = rows["run_dir"].map(lambda p: str(Path(p).resolve()))
    rows["checkpoint"] = rows["checkpoint"].map(lambda p: str(Path(p).resolve()))

    target_suite.mkdir(parents=True)
    rows.to_csv(target_suite / "runs.tsv", sep="\t", index=False)
    (target_suite / "suite_config.txt").write_text(
        f"Suite: {target_suite.name}\n"
        f"Type: manifest-only decision suite; no symlinks\n"
        f"Sources: smoke3 seeds 42/44/46 + decision_extra43-45 seeds 43/45\n"
        f"Protocol: {protocol}\n",
        encoding="utf-8",
    )

    print(f"[registered] {target_suite.name}: {len(rows)} runs")

[ok] sweep_oc_phase1a_smoke3_clean_phase1a_oc_v4lite_cleanrun_v1: 9 runs
[ok] sweep_oc_phase1a_smoke3_iid_phase1a_oc_v4lite_cleanrun_v1: 9 runs
[ok] sweep_oc_phase1a_smoke3_v4lite_phase1a_oc_v4lite_cleanrun_v1: 9 runs
[ok] sweep_oc_phase1a_decision_extra43-45_clean_phase1a_oc_v4lite_cleanrun_v1: 6 runs
[ok] sweep_oc_phase1a_decision_extra43-45_iid_phase1a_oc_v4lite_cleanrun_v1: 6 runs
[ok] sweep_oc_phase1a_decision_extra43-45_v4lite_phase1a_oc_v4lite_cleanrun_v1: 6 runs
[registered] sweep_oc_phase1a_decision_clean_phase1a_oc_v4lite_cleanrun_v1: 15 runs
[registered] sweep_oc_phase1a_decision_iid_phase1a_oc_v4lite_cleanrun_v1: 15 runs
[registered] sweep_oc_phase1a_decision_v4lite_phase1a_oc_v4lite_cleanrun_v1: 15 runs

In [ ]:
for protocol in ["clean", "iid", "v4lite"]:
    suite = ckpt / f"sweep_oc_phase1a_decision_{protocol}_{run_tag}"
    runs = pd.read_csv(suite / "runs.tsv", sep="\t")
    print(protocol, len(runs), sorted(runs["seed"].unique()))
    print(runs[["model_type", "seed", "run_dir"]].head())

clean 15 [np.int64(42), np.int64(43), np.int64(44), np.int64(45), np.int64(46)]
       model_type  seed                                            run_dir
0  ablate_no_lift    42  /content/drive/MyDrive/Colab Notebooks/auvhamn...
1  ablate_no_lift    43  /content/drive/MyDrive/Colab Notebooks/auvhamn...
2  ablate_no_lift    44  /content/drive/MyDrive/Colab Notebooks/auvhamn...
3  ablate_no_lift    45  /content/drive/MyDrive/Colab Notebooks/auvhamn...
4  ablate_no_lift    46  /content/drive/MyDrive/Colab Notebooks/auvhamn...
iid 15 [np.int64(42), np.int64(43), np.int64(44), np.int64(45), np.int64(46)]
       model_type  seed                                            run_dir
0  ablate_no_lift    42  /content/drive/MyDrive/Colab Notebooks/auvhamn...
1  ablate_no_lift    43  /content/drive/MyDrive/Colab Notebooks/auvhamn...
2  ablate_no_lift    44  /content/drive/MyDrive/Colab Notebooks/auvhamn...
3  ablate_no_lift    45  /content/drive/MyDrive/Colab Notebooks/auvhamn...
4  ablate_no_lift    46  /content/drive/MyDrive/Colab Notebooks/auvhamn...
v4lite 15 [np.int64(42), np.int64(43), np.int64(44), np.int64(45), np.int64(46)]
       model_type  seed                                            run_dir
0  ablate_no_lift    42  /content/drive/MyDrive/Colab Notebooks/auvhamn...
1  ablate_no_lift    43  /content/drive/MyDrive/Colab Notebooks/auvhamn...
2  ablate_no_lift    44  /content/drive/MyDrive/Colab Notebooks/auvhamn...
3  ablate_no_lift    45  /content/drive/MyDrive/Colab Notebooks/auvhamn...
4  ablate_no_lift    46  /content/drive/MyDrive/Colab Notebooks/auvhamn...

In [ ]:
python scripts/phase1a_oc_v4lite_utils.py \
  --checkpoint-root checkpoints \
  audit \
  --suite-name "sweep_oc_phase1a_decision_clean_phase1a_oc_v4lite_cleanrun_v1" \
  --suite-name "sweep_oc_phase1a_decision_iid_phase1a_oc_v4lite_cleanrun_v1" \
  --suite-name "sweep_oc_phase1a_decision_v4lite_phase1a_oc_v4lite_cleanrun_v1" \
  --strict-zero-noise \
  --soft-min-epoch-scale 0.05

In [ ]:
# 审计并验证新增 v4-lite

!python scripts/phase1a_oc_v4lite_utils.py \
  --checkpoint-root checkpoints \
  audit \
  --suite-name "sweep_oc_phase1a_decision_clean_${RUN_TAG}" \
  --suite-name "sweep_oc_phase1a_decision_iid_${RUN_TAG}" \
  --suite-name "sweep_oc_phase1a_decision_v4lite_${RUN_TAG}" \
  --strict-zero-noise \
  --soft-min-epoch-scale 0.05

!python scripts/phase1a_oc_v4lite_utils.py \
  --checkpoint-root checkpoints \
  validate \
  --suite-name "sweep_oc_phase1a_decision_v4lite_${RUN_TAG}"

[audit] /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_clean_phase1a_oc_v4lite_cleanrun_v1
[audit] /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_iid_phase1a_oc_v4lite_cleanrun_v1
[audit] /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_v4lite_phase1a_oc_v4lite_cleanrun_v1
                                                    suite_name    group           model_type  seed train_noise_protocol  best_epoch  best_loss  noise_warmup_epochs  noise_ramp_epochs  noise_mix_ratio  epoch_scale_at_best  is_effectively_clean_at_best
 sweep_oc_phase1a_decision_clean_phase1a_oc_v4lite_cleanrun_v1 ablation       ablate_no_lift    42                clean         249   0.004077                   20                 80              0.5                  0.0                          True
 sweep_oc_phase1a_decision_clean_phase1a_oc_v4lite_cleanrun_v1 ablation       ablate_no_lift    43                clean          19   0.216895                   20                 80              0.5                  0.0                          True
 sweep_oc_phase1a_decision_clean_phase1a_oc_v4lite_cleanrun_v1 ablation       ablate_no_lift    44                clean         249   0.004109                   20                 80              0.5                  0.0                          True
 sweep_oc_phase1a_decision_clean_phase1a_oc_v4lite_cleanrun_v1 ablation       ablate_no_lift    45                clean         248   0.004005                   20                 80              0.5                  0.0                          True
 sweep_oc_phase1a_decision_clean_phase1a_oc_v4lite_cleanrun_v1 ablation       ablate_no_lift    46                clean         250   0.004621                   20                 80              0.5                  0.0                          True
   sweep_oc_phase1a_decision_iid_phase1a_oc_v4lite_cleanrun_v1 ablation       ablate_no_lift    42         iid_noisy_ic         240   0.006710                   20                 80              0.5                  1.0                         False
   sweep_oc_phase1a_decision_iid_phase1a_oc_v4lite_cleanrun_v1 ablation       ablate_no_lift    43         iid_noisy_ic         237   0.006294                   20                 80              0.5                  1.0                         False
   sweep_oc_phase1a_decision_iid_phase1a_oc_v4lite_cleanrun_v1 ablation       ablate_no_lift    44         iid_noisy_ic         248   0.006263                   20                 80              0.5                  1.0                         False
   sweep_oc_phase1a_decision_iid_phase1a_oc_v4lite_cleanrun_v1 ablation       ablate_no_lift    45         iid_noisy_ic         237   0.006254                   20                 80              0.5                  1.0                         False
   sweep_oc_phase1a_decision_iid_phase1a_oc_v4lite_cleanrun_v1 ablation       ablate_no_lift    46         iid_noisy_ic         245   0.006636                   20                 80              0.5                  1.0                         False
sweep_oc_phase1a_decision_v4lite_phase1a_oc_v4lite_cleanrun_v1 ablation       ablate_no_lift    42              v4_lite         231   0.006538                   20                 80              0.5                  1.0                         False
sweep_oc_phase1a_decision_v4lite_phase1a_oc_v4lite_cleanrun_v1 ablation       ablate_no_lift    43              v4_lite         245   0.006332                   20                 80              0.5                  1.0                         False
sweep_oc_phase1a_decision_v4lite_phase1a_oc_v4lite_cleanrun_v1 ablation       ablate_no_lift    44              v4_lite         248   0.006335                   20                 80              0.5                  1.0                         False
sweep_oc_phase1a_decision_v4lite_phase1a_oc_v4lite_cleanrun_v1 ablation       ablate_no_lift    45              v4_lite         242   0.006288                   20                 80              0.5                  1.0                         False
sweep_oc_phase1a_decision_v4lite_phase1a_oc_v4lite_cleanrun_v1 ablation       ablate_no_lift    46              v4_lite         248   0.007332                   20                 80              0.5                  1.0                         False
 sweep_oc_phase1a_decision_clean_phase1a_oc_v4lite_cleanrun_v1 ablation ablate_no_mass_prior    42                clean         250   0.004923                   20                 80              0.5                  0.0                          True
 sweep_oc_phase1a_decision_clean_phase1a_oc_v4lite_cleanrun_v1 ablation ablate_no_mass_prior    43                clean         249   0.005489                   20                 80              0.5                  0.0                          True
 sweep_oc_phase1a_decision_clean_phase1a_oc_v4lite_cleanrun_v1 ablation ablate_no_mass_prior    44                clean         248   0.005630                   20                 80              0.5                  0.0                          True
 sweep_oc_phase1a_decision_clean_phase1a_oc_v4lite_cleanrun_v1 ablation ablate_no_mass_prior    45                clean         249   0.004713                   20                 80              0.5                  0.0                          True
 sweep_oc_phase1a_decision_clean_phase1a_oc_v4lite_cleanrun_v1 ablation ablate_no_mass_prior    46                clean         249   0.004738                   20                 80              0.5                  0.0                          True
   sweep_oc_phase1a_decision_iid_phase1a_oc_v4lite_cleanrun_v1 ablation ablate_no_mass_prior    42         iid_noisy_ic         249   0.006579                   20                 80              0.5                  1.0                         False
   sweep_oc_phase1a_decision_iid_phase1a_oc_v4lite_cleanrun_v1 ablation ablate_no_mass_prior    43         iid_noisy_ic         248   0.007758                   20                 80              0.5                  1.0                         False
   sweep_oc_phase1a_decision_iid_phase1a_oc_v4lite_cleanrun_v1 ablation ablate_no_mass_prior    44         iid_noisy_ic         244   0.007265                   20                 80              0.5                  1.0                         False
   sweep_oc_phase1a_decision_iid_phase1a_oc_v4lite_cleanrun_v1 ablation ablate_no_mass_prior    45         iid_noisy_ic         249   0.006893                   20                 80              0.5                  1.0                         False
   sweep_oc_phase1a_decision_iid_phase1a_oc_v4lite_cleanrun_v1 ablation ablate_no_mass_prior    46         iid_noisy_ic         245   0.006658                   20                 80              0.5                  1.0                         False
sweep_oc_phase1a_decision_v4lite_phase1a_oc_v4lite_cleanrun_v1 ablation ablate_no_mass_prior    42              v4_lite         239   0.006673                   20                 80              0.5                  1.0                         False
sweep_oc_phase1a_decision_v4lite_phase1a_oc_v4lite_cleanrun_v1 ablation ablate_no_mass_prior    43              v4_lite         245   0.007099                   20                 80              0.5                  1.0                         False
sweep_oc_phase1a_decision_v4lite_phase1a_oc_v4lite_cleanrun_v1 ablation ablate_no_mass_prior    44              v4_lite         239   0.007446                   20                 80              0.5                  1.0                         False
sweep_oc_phase1a_decision_v4lite_phase1a_oc_v4lite_cleanrun_v1 ablation ablate_no_mass_prior    45              v4_lite         242   0.006988                   20                 80              0.5                  1.0                         False
sweep_oc_phase1a_decision_v4lite_phase1a_oc_v4lite_cleanrun_v1 ablation ablate_no_mass_prior    46              v4_lite         247   0.006770                   20                 80              0.5                  1.0                         False
 sweep_oc_phase1a_decision_clean_phase1a_oc_v4lite_cleanrun_v1     main          phnode_full    42                clean         249   0.004021                   20                 80              0.5                  0.0                          True
 sweep_oc_phase1a_decision_clean_phase1a_oc_v4lite_cleanrun_v1     main          phnode_full    43                clean         247   0.004155                   20                 80              0.5                  0.0                          True
 sweep_oc_phase1a_decision_clean_phase1a_oc_v4lite_cleanrun_v1     main          phnode_full    44                clean         242   0.004207                   20                 80              0.5                  0.0                          True
 sweep_oc_phase1a_decision_clean_phase1a_oc_v4lite_cleanrun_v1     main          phnode_full    45                clean         247   0.004025                   20                 80              0.5                  0.0                          True
 sweep_oc_phase1a_decision_clean_phase1a_oc_v4lite_cleanrun_v1     main          phnode_full    46                clean         250   0.004047                   20                 80              0.5                  0.0                          True
   sweep_oc_phase1a_decision_iid_phase1a_oc_v4lite_cleanrun_v1     main          phnode_full    42         iid_noisy_ic         245   0.006216                   20                 80              0.5                  1.0                         False
   sweep_oc_phase1a_decision_iid_phase1a_oc_v4lite_cleanrun_v1     main          phnode_full    43         iid_noisy_ic         234   0.006302                   20                 80              0.5                  1.0                         False
   sweep_oc_phase1a_decision_iid_phase1a_oc_v4lite_cleanrun_v1     main          phnode_full    44         iid_noisy_ic         248   0.006581                   20                 80              0.5                  1.0                         False
   sweep_oc_phase1a_decision_iid_phase1a_oc_v4lite_cleanrun_v1     main          phnode_full    45         iid_noisy_ic         238   0.006221                   20                 80              0.5                  1.0                         False
   sweep_oc_phase1a_decision_iid_phase1a_oc_v4lite_cleanrun_v1     main          phnode_full    46         iid_noisy_ic         250   0.006382                   20                 80              0.5                  1.0                         False
sweep_oc_phase1a_decision_v4lite_phase1a_oc_v4lite_cleanrun_v1     main          phnode_full    42              v4_lite         204   0.006297                   20                 80              0.5                  1.0                         False
sweep_oc_phase1a_decision_v4lite_phase1a_oc_v4lite_cleanrun_v1     main          phnode_full    43              v4_lite         248   0.006239                   20                 80              0.5                  1.0                         False
sweep_oc_phase1a_decision_v4lite_phase1a_oc_v4lite_cleanrun_v1     main          phnode_full    44              v4_lite         245   0.006270                   20                 80              0.5                  1.0                         False
sweep_oc_phase1a_decision_v4lite_phase1a_oc_v4lite_cleanrun_v1     main          phnode_full    45              v4_lite         247   0.006427                   20                 80              0.5                  1.0                         False
sweep_oc_phase1a_decision_v4lite_phase1a_oc_v4lite_cleanrun_v1     main          phnode_full    46              v4_lite         234   0.006341                   20                 80              0.5                  1.0                         False
+ /usr/bin/python3 /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/scripts/validate_v4_lite_protocol.py --run-dir /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_v4lite_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_lift_seed42
v4_lite protocol validation saved to: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_v4lite_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_lift_seed42/v4_lite_protocol_validation.json
overall_passed=True
same_epoch_stability: passed=True
epoch_resampling: passed=True
heading_bias_overlay: passed=True
[validate] /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_v4lite_phase1a_oc_v4lite_cleanrun_v1/ablation_ablate_no_lift_seed42/v4_lite_protocol_validation.json

## 7. Decision rollout eval

默认只跑 Phase-1A 必需评估：

- `clean`
- `iid_noisy_ic / nominal_eval`
- `v4_lite / nominal_eval`

`degraded_eval` 和 `heading_biased_eval` 不在默认 gate 内。

In [ ]:
os.environ["MODE"] = "decision_eval"
!bash scripts/run_phase1a_oc_v4lite.sh

Streaming output truncated to the last 5000 lines.
  H=10.0s | pos median=0.0872 m | pos p95=0.2832 m | rot median=0.0056 rad | total vel median=0.0136 m/s | rel vel median=0.0126 m/s | cond_n=30/30 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
  H=30.0s | pos median=0.4055 m | pos p95=0.6294 m | rot median=0.0110 rad | total vel median=0.0153 m/s | rel vel median=0.0159 m/s | cond_n=30/30 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
  H=60.0s | pos median=1.1320 m | pos p95=2.5938 m | rot median=0.0288 rad | total vel median=0.0164 m/s | rel vel median=0.0148 m/s | cond_n=30/30 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000

CHIRP
  n=30 | completed=30 (1.000) | gt_divergence=0 (0.000) | pred_divergence=0 (0.000) | solver_failure=0 (0.000) | nan_or_inf=0 (0.000)
  H=10.0s | pos median=0.0944 m | pos p95=0.1610 m | rot median=0.0096 rad | total vel median=0.0071 m/s | rel vel median=0.0059 m/s | cond_n=30/30 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
  H=30.0s | pos median=0.2515 m | pos p95=0.9168 m | rot median=0.0107 rad | total vel median=0.0067 m/s | rel vel median=0.0059 m/s | cond_n=30/30 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
  H=60.0s | pos median=0.8871 m | pos p95=2.5138 m | rot median=0.0316 rad | total vel median=0.0101 m/s | rel vel median=0.0087 m/s | cond_n=30/30 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000

OU
  n=30 | completed=28 (0.933) | gt_divergence=0 (0.000) | pred_divergence=2 (0.067) | solver_failure=0 (0.000) | nan_or_inf=0 (0.000)
  H=10.0s | pos median=0.1180 m | pos p95=0.2144 m | rot median=0.0085 rad | total vel median=0.0152 m/s | rel vel median=0.0152 m/s | cond_n=30/30 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
  H=30.0s | pos median=0.3899 m | pos p95=1.1617 m | rot median=0.0175 rad | total vel median=0.0165 m/s | rel vel median=0.0155 m/s | cond_n=30/30 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
  H=60.0s | pos median=1.3389 m | pos p95=3.0755 m | rot median=0.0284 rad | total vel median=0.0144 m/s | rel vel median=0.0173 m/s | cond_n=28/30 | completion=0.933 | gt_fail_by_h=0.000 | model_fail_by_h=0.067

Diagnostic Cases To Max Horizon
--------------------------------------------------------------------------------
Earliest rollout failures
  OU seed=200051 | reason=pred_divergence | sim_time=42.75s | pos=nan m | rot=nan rad | total_vel_violation=0
  OU seed=200066 | reason=pred_divergence | sim_time=58.35s | pos=nan m | rot=nan rad | total_vel_violation=0

Largest completed terminal errors
  OU seed=200058 | reason=completed | sim_time=60.00s | pos=4.1615 m | rot=0.0993 rad | total_vel_violation=0
  OU seed=200070 | reason=completed | sim_time=60.00s | pos=3.4784 m | rot=0.0523 rad | total_vel_violation=0
  PRBS seed=61 | reason=completed | sim_time=60.00s | pos=3.4328 m | rot=0.0468 rad | total_vel_violation=0
  PRBS seed=49 | reason=completed | sim_time=60.00s | pos=2.7110 m | rot=0.0456 rad | total_vel_violation=0
  CHIRP seed=100057 | reason=completed | sim_time=60.00s | pos=2.6734 m | rot=0.0510 rad | total_vel_violation=0

Completed rollouts with velocity violations
  OU seed=200061 | reason=completed | sim_time=60.00s | pos=2.0519 m | rot=0.0261 rad | total_vel_violation=1
  OU seed=200055 | reason=completed | sim_time=60.00s | pos=0.4216 m | rot=0.0072 rad | total_vel_violation=1

Diagnostic Plot Files
--------------------------------------------------------------------------------
OU seed=200051 | label=rollout_failure | /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_v4lite_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed45/rollout_benchmark/phase1a_iideval_traj30_seed42_20260426_120306/clean/diagnostic_plots/rollout_failure_OU_seed200051.png
OU seed=200066 | label=rollout_failure | /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_v4lite_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed45/rollout_benchmark/phase1a_iideval_traj30_seed42_20260426_120306/clean/diagnostic_plots/rollout_failure_OU_seed200066.png
OU seed=200061 | label=velocity_violation | /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_v4lite_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed45/rollout_benchmark/phase1a_iideval_traj30_seed42_20260426_120306/clean/diagnostic_plots/velocity_violation_OU_seed200061.png
OU seed=200055 | label=velocity_violation | /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_v4lite_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed45/rollout_benchmark/phase1a_iideval_traj30_seed42_20260426_120306/clean/diagnostic_plots/velocity_violation_OU_seed200055.png
OU seed=200058 | label=high_terminal_error | /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_v4lite_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed45/rollout_benchmark/phase1a_iideval_traj30_seed42_20260426_120306/clean/diagnostic_plots/high_terminal_error_OU_seed200058.png
OU seed=200070 | label=high_terminal_error | /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_v4lite_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed45/rollout_benchmark/phase1a_iideval_traj30_seed42_20260426_120306/clean/diagnostic_plots/high_terminal_error_OU_seed200070.png
Starting rollout benchmark | checkpoint=/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_v4lite_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed45/best_model.pt | device=cuda | mode=resampled | noise_profile=nominal_eval | noise_protocol=iid_noisy_ic | noise_budget=protocol=iid_noisy_ic | profile=nominal_eval | ref=remus100_dr | epoch_scale=1.000 | mix_ratio=0.500 | nu_r_lin_floor[u=0.0030, v=0.0030, w=0.0040] | nu_r_lin_ratio[u=0.0030, v=0.0030, w=0.0030] | nu_r_ang[p=0.0008, q=0.0008, r=0.0015] | rot[roll=0.0020, pitch=0.0020, yaw=0.0100] | scenarios=PRBS,CHIRP,OU | trajectories=90 | max_horizon=60.0s | output_dir=/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_v4lite_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed45/rollout_benchmark/phase1a_iideval_traj30_seed42_20260426_120306/nominal_eval
[scenario 1/3] PRBS | 30 trajectories
[1/90] PRBS seed=42 done | reason=completed | sim_time=60.00s | eta=31m00.5s
[5/90] PRBS seed=46 done | reason=completed | sim_time=60.00s | eta=5m55.6s
[10/90] PRBS seed=51 done | reason=completed | sim_time=60.00s | eta=2m47.5s
[15/90] PRBS seed=56 done | reason=completed | sim_time=60.00s | eta=1m44.7s
[20/90] PRBS seed=61 done | reason=completed | sim_time=60.00s | eta=1m13.4s
[25/90] PRBS seed=66 done | reason=completed | sim_time=60.00s | eta=54.5s
[30/90] PRBS seed=71 done | reason=completed | sim_time=60.00s | eta=42.0s
[scenario done] PRBS | completed=30/30 | gt_div=0 | model_fail=0 | H=60.0s cond_n=30/30 | pos_med=1.4973 m | pos_p95=3.0122 m | rot_med=0.0352 rad | completion=1.000 | elapsed=21.0s
[scenario 2/3] CHIRP | 30 trajectories
[31/90] CHIRP seed=100042 done | reason=completed | sim_time=60.00s | eta=1m19.8s
[35/90] CHIRP seed=100046 done | reason=completed | sim_time=60.00s | eta=1m05.9s
[40/90] CHIRP seed=100051 done | reason=completed | sim_time=60.00s | eta=52.5s
[45/90] CHIRP seed=100056 done | reason=completed | sim_time=60.00s | eta=42.0s
[50/90] CHIRP seed=100061 done | reason=completed | sim_time=60.00s | eta=33.6s
[55/90] CHIRP seed=100066 done | reason=completed | sim_time=60.00s | eta=26.7s
[60/90] CHIRP seed=100071 done | reason=completed | sim_time=60.00s | eta=21.0s
[scenario done] CHIRP | completed=30/30 | gt_div=0 | model_fail=0 | H=60.0s cond_n=30/30 | pos_med=1.1909 m | pos_p95=2.7245 m | rot_med=0.0341 rad | completion=1.000 | elapsed=42.1s
[scenario 3/3] OU | 30 trajectories
[61/90] OU seed=200042 done | reason=completed | sim_time=60.00s | eta=30.0s
[65/90] OU seed=200046 done | reason=completed | sim_time=60.00s | eta=24.3s
[70/90] OU seed=200051 done | reason=pred_divergence | sim_time=42.75s | eta=18.0s
[75/90] OU seed=200056 done | reason=completed | sim_time=60.00s | eta=12.6s
[80/90] OU seed=200061 done | reason=completed | sim_time=60.00s | eta=7.9s
[85/90] OU seed=200066 done | reason=pred_divergence | sim_time=58.35s | eta=3.7s
[90/90] OU seed=200071 done | reason=completed | sim_time=60.00s | eta=0.0s
[scenario done] OU | completed=28/30 | gt_div=0 | model_fail=2 | H=60.0s cond_n=28/30 | pos_med=1.4312 m | pos_p95=3.8335 m | rot_med=0.0312 rad | completion=0.933 | elapsed=1m03.2s
Benchmark finished in 1m21.5s
Results written to /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_v4lite_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed45/rollout_benchmark/phase1a_iideval_traj30_seed42_20260426_120306/nominal_eval
Rollout Benchmark Summary
================================================================================
Checkpoint: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_v4lite_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed45/best_model.pt
Dataset: /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_5/data/auv_oc_traj1000_blk150_s23_d0be9434.pkl
Model: pH NODE Full [main/core]
Canonical model type: phnode_full
Energy semantics: mechanical_energy
Device: cuda
Mode: resampled
Generation config source: checkpoint
Scenarios: PRBS, CHIRP, OU
Trajectories per scenario: 30
Horizons: 10.0, 30.0, 60.0

Overall
--------------------------------------------------------------------------------
Conditional error statistics use only trajectories that completed to the horizon.
Primary KPIs are observable-space fields: position, depth, rotation, and total velocity.
Model-space diagnostics use relative velocity; internal diagnostics cover energy and raw SO(3) quality.
Per-column field grouping is exported in metric_contract.csv.
H=10.0s | pos median=0.1707 m | pos p95=0.4352 m | rot median=0.0092 rad | total vel median=0.0108 m/s | rel vel median=0.0086 m/s | cond_n=90/90 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
H=30.0s | pos median=0.4665 m | pos p95=1.3868 m | rot median=0.0176 rad | total vel median=0.0114 m/s | rel vel median=0.0100 m/s | cond_n=90/90 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
H=60.0s | pos median=1.3948 m | pos p95=3.3436 m | rot median=0.0334 rad | total vel median=0.0138 m/s | rel vel median=0.0127 m/s | cond_n=88/90 | completion=0.978 | gt_fail_by_h=0.000 | model_fail_by_h=0.022

Rollout Outcomes To Max Horizon
--------------------------------------------------------------------------------
n=90 | completed=88 (0.978) | gt_divergence=0 (0.000) | pred_divergence=2 (0.022) | solver_failure=0 (0.000) | nan_or_inf=0 (0.000)

By Scenario
--------------------------------------------------------------------------------
PRBS
  n=30 | completed=30 (1.000) | gt_divergence=0 (0.000) | pred_divergence=0 (0.000) | solver_failure=0 (0.000) | nan_or_inf=0 (0.000)
  H=10.0s | pos median=0.1646 m | pos p95=0.4239 m | rot median=0.0067 rad | total vel median=0.0148 m/s | rel vel median=0.0124 m/s | cond_n=30/30 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
  H=30.0s | pos median=0.4434 m | pos p95=1.2057 m | rot median=0.0174 rad | total vel median=0.0157 m/s | rel vel median=0.0157 m/s | cond_n=30/30 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
  H=60.0s | pos median=1.4973 m | pos p95=3.0122 m | rot median=0.0352 rad | total vel median=0.0163 m/s | rel vel median=0.0149 m/s | cond_n=30/30 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000

CHIRP
  n=30 | completed=30 (1.000) | gt_divergence=0 (0.000) | pred_divergence=0 (0.000) | solver_failure=0 (0.000) | nan_or_inf=0 (0.000)
  H=10.0s | pos median=0.1137 m | pos p95=0.3639 m | rot median=0.0099 rad | total vel median=0.0070 m/s | rel vel median=0.0059 m/s | cond_n=30/30 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
  H=30.0s | pos median=0.4230 m | pos p95=1.1084 m | rot median=0.0140 rad | total vel median=0.0068 m/s | rel vel median=0.0059 m/s | cond_n=30/30 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
  H=60.0s | pos median=1.1909 m | pos p95=2.7245 m | rot median=0.0341 rad | total vel median=0.0120 m/s | rel vel median=0.0087 m/s | cond_n=30/30 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000

OU
  n=30 | completed=28 (0.933) | gt_divergence=0 (0.000) | pred_divergence=2 (0.067) | solver_failure=0 (0.000) | nan_or_inf=0 (0.000)
  H=10.0s | pos median=0.1899 m | pos p95=0.4426 m | rot median=0.0109 rad | total vel median=0.0153 m/s | rel vel median=0.0153 m/s | cond_n=30/30 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
  H=30.0s | pos median=0.5346 m | pos p95=1.5097 m | rot median=0.0271 rad | total vel median=0.0167 m/s | rel vel median=0.0155 m/s | cond_n=30/30 | completion=1.000 | gt_fail_by_h=0.000 | model_fail_by_h=0.000
  H=60.0s | pos median=1.4312 m | pos p95=3.8335 m | rot median=0.0312 rad | total vel median=0.0154 m/s | rel vel median=0.0173 m/s | cond_n=28/30 | completion=0.933 | gt_fail_by_h=0.000 | model_fail_by_h=0.067

Diagnostic Cases To Max Horizon
--------------------------------------------------------------------------------
Earliest rollout failures
  OU seed=200051 | reason=pred_divergence | sim_time=42.75s | pos=nan m | rot=nan rad | total_vel_violation=0
  OU seed=200066 | reason=pred_divergence | sim_time=58.35s | pos=nan m | rot=nan rad | total_vel_violation=0

Largest completed terminal errors
  PRBS seed=62 | reason=completed | sim_time=60.00s | pos=4.6138 m | rot=0.0398 rad | total_vel_violation=0
  OU seed=200056 | reason=completed | sim_time=60.00s | pos=3.9162 m | rot=0.0919 rad | total_vel_violation=0
  OU seed=200058 | reason=completed | sim_time=60.00s | pos=3.8992 m | rot=0.0953 rad | total_vel_violation=0
  OU seed=200059 | reason=completed | sim_time=60.00s | pos=3.7113 m | rot=0.0658 rad | total_vel_violation=0
  OU seed=200071 | reason=completed | sim_time=60.00s | pos=3.5138 m | rot=0.0491 rad | total_vel_violation=0

Completed rollouts with velocity violations
  OU seed=200061 | reason=completed | sim_time=60.00s | pos=2.4824 m | rot=0.0308 rad | total_vel_violation=1
  OU seed=200055 | reason=completed | sim_time=60.00s | pos=1.4087 m | rot=0.0090 rad | total_vel_violation=1

Diagnostic Plot Files
--------------------------------------------------------------------------------
OU seed=200051 | label=rollout_failure | /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_v4lite_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed45/rollout_benchmark/phase1a_iideval_traj30_seed42_20260426_120306/nominal_eval/diagnostic_plots/rollout_failure_OU_seed200051.png
OU seed=200066 | label=rollout_failure | /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_v4lite_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed45/rollout_benchmark/phase1a_iideval_traj30_seed42_20260426_120306/nominal_eval/diagnostic_plots/rollout_failure_OU_seed200066.png
OU seed=200061 | label=velocity_violation | /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_v4lite_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed45/rollout_benchmark/phase1a_iideval_traj30_seed42_20260426_120306/nominal_eval/diagnostic_plots/velocity_violation_OU_seed200061.png
OU seed=200055 | label=velocity_violation | /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_v4lite_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed45/rollout_benchmark/phase1a_iideval_traj30_seed42_20260426_120306/nominal_eval/diagnostic_plots/velocity_violation_OU_seed200055.png
PRBS seed=62 | label=high_terminal_error | /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_v4lite_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed45/rollout_benchmark/phase1a_iideval_traj30_seed42_20260426_120306/nominal_eval/diagnostic_plots/high_terminal_error_PRBS_seed62.png
OU seed=200056 | label=high_terminal_error | /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_extra43-45_v4lite_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed45/rollout_benchmark/phase1a_iideval_traj30_seed42_20260426_120306/nominal_eval/diagnostic_plots/high_terminal_error_OU_seed200056.png
[eval] main_phnode_full_seed46
Starting rollout benchmark | checkpoint=/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_v4lite_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed46/best_model.pt | device=cuda | mode=resampled | noise_profile=clean | noise_protocol=clean | noise_budget=protocol=clean | profile=clean | ref=remus100_dr | epoch_scale=0.000 | mix_ratio=0.000 | nu_r_lin_floor[u=0.0000, v=0.0000, w=0.0000] | nu_r_lin_ratio[u=0.0000, v=0.0000, w=0.0000] | nu_r_ang[p=0.0000, q=0.0000, r=0.0000] | rot[roll=0.0000, pitch=0.0000, yaw=0.0000] | scenarios=PRBS,CHIRP,OU | trajectories=90 | max_horizon=60.0s | output_dir=/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_smoke3_v4lite_phase1a_oc_v4lite_cleanrun_v1/main_phnode_full_seed46/rollout_benchmark/phase1a_iideval_traj30_seed42_20260426_121547/clean
[scenario 1/3] PRBS | 30 trajectories
[1/90] PRBS seed=42 done | reason=completed | sim_time=60.00s | eta=4h32m42.0s
[5/90] PRBS seed=46 done | reason=completed | sim_time=60.00s | eta=52m05.5s
[10/90] PRBS seed=51 done | reason=completed | sim_time=60.00s | eta=24m31.0s
[15/90] PRBS seed=56 done | reason=completed | sim_time=60.00s | eta=15m19.4s
[20/90] PRBS seed=61 done | reason=completed | sim_time=60.00s | eta=10m43.7s
[25/90] PRBS seed=66 done | reason=completed | sim_time=60.00s | eta=7m58.2s
[30/90] PRBS seed=71 done | reason=completed | sim_time=60.00s | eta=6m07.9s
[scenario done] PRBS | completed=30/30 | gt_div=0 | model_fail=0 | H=60.0s cond_n=30/30 | pos_med=1.2517 m | pos_p95=2.1600 m | rot_med=0.0265 rad | completion=1.000 | elapsed=3m04.0s
[scenario 2/3] CHIRP | 30 trajectories
[31/90] CHIRP seed=100042 done | reason=completed | sim_time=60.00s | eta=11m40.4s
[35/90] CHIRP seed=100046 done | reason=completed | sim_time=60.00s | eta=9m38.3s
[40/90] CHIRP seed=100051 done | reason=completed | sim_time=60.00s | eta=7m40.0s
[45/90] CHIRP seed=100056 done | reason=completed | sim_time=60.00s | eta=6m08.0s
[50/90] CHIRP seed=100061 done | reason=completed | sim_time=60.00s | eta=4m54.4s
[55/90] CHIRP seed=100066 done | reason=completed | sim_time=60.00s | eta=3m54.2s
[60/90] CHIRP seed=100071 done | reason=completed | sim_time=60.00s | eta=3m04.0s
[scenario done] CHIRP | completed=30/30 | gt_div=0 | model_fail=0 | H=60.0s cond_n=30/30 | pos_med=1.2029 m | pos_p95=1.9270 m | rot_med=0.0255 rad | completion=1.000 | elapsed=6m08.1s
[scenario 3/3] OU | 30 trajectories
[61/90] OU seed=200042 done | reason=completed | sim_time=60.00s | eta=4m22.7s
[65/90] OU seed=200046 done | reason=completed | sim_time=60.00s | eta=3m32.5s
[70/90] OU seed=200051 done | reason=pred_divergence | sim_time=42.95s | eta=2m37.9s
[75/90] OU seed=200056 done | reason=completed | sim_time=60.00s | eta=1m50.5s
[80/90] OU seed=200061 done | reason=completed | sim_time=60.00s | eta=1m09.1s
[85/90] OU seed=200066 done | reason=pred_divergence | sim_time=58.35s | eta=32.5s
[90/90] OU seed=200071 done | reason=completed | sim_time=60.00s | eta=0.0s

## 8. Decision summarize + export

注册 decision proxy suite，生成并导出 `phase1a_*` 正式产物。

In [ ]:
# unused
"""
os.environ["MODE"] = "decision_summarize"
!bash scripts/run_phase1a_oc_v4lite.sh
"""

In [9]:
from pathlib import Path
import os
import shutil
import pandas as pd

run_tag = os.environ.get("RUN_TAG", "phase1a_oc_v4lite_cleanrun_v1")
ckpt = Path.cwd() / "checkpoints"
target = ckpt / f"sweep_oc_phase1a_decision_proxy_{run_tag}"

if target.exists():
    shutil.rmtree(target)

rows = []
for protocol in ["clean", "iid", "v4lite"]:
    suite = ckpt / f"sweep_oc_phase1a_decision_{protocol}_{run_tag}"
    df = pd.read_csv(suite / "runs.tsv", sep="\t")
    df["seed"] = df["seed"].astype(int)

    if len(df) != 15 or set(df["seed"]) != {42, 43, 44, 45, 46}:
        raise ValueError(f"Invalid decision suite: {suite}")

    for _, row in df.iterrows():
        rows.append({
            "group": row["group"],
            "model_type": row["model_type"],
            "seed": int(row["seed"]),
            "run_name": f"{protocol}__{row['run_name']}",
            "run_dir": str(Path(row["run_dir"]).resolve()),
            "checkpoint": str(Path(row["checkpoint"]).resolve()),
        })

target.mkdir(parents=True)
out = pd.DataFrame(rows).sort_values(["group", "model_type", "seed", "run_name"])
out.to_csv(target / "runs.tsv", sep="\t", index=False)
(target / "suite_config.txt").write_text(
    f"Suite: {target.name}\n"
    "Type: manifest-only combined decision suite; no symlinks\n"
    "Sources: decision_clean + decision_iid + decision_v4lite\n",
    encoding="utf-8",
)

print(target)
print(len(out))

/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_proxy_phase1a_oc_v4lite_cleanrun_v1
45

In [10]:
!python scripts/phase1a_oc_v4lite_utils.py \
  --checkpoint-root checkpoints \
  audit \
  --suite-name "sweep_oc_phase1a_decision_clean_phase1a_oc_v4lite_cleanrun_v1" \
  --suite-name "sweep_oc_phase1a_decision_iid_phase1a_oc_v4lite_cleanrun_v1" \
  --suite-name "sweep_oc_phase1a_decision_v4lite_phase1a_oc_v4lite_cleanrun_v1" \
  --output "checkpoints/sweep_oc_phase1a_decision_proxy_phase1a_oc_v4lite_cleanrun_v1/phase1a_train_audit.csv" \
  --strict-zero-noise \
  --soft-min-epoch-scale 0.05

!python scripts/summarize_sweep.py \
  --suite-dir "checkpoints/sweep_oc_phase1a_decision_proxy_phase1a_oc_v4lite_cleanrun_v1"

!python scripts/build_experiment_report.py \
  --suite-dir "checkpoints/sweep_oc_phase1a_decision_proxy_phase1a_oc_v4lite_cleanrun_v1"

[audit] /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_clean_phase1a_oc_v4lite_cleanrun_v1
[audit] /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_iid_phase1a_oc_v4lite_cleanrun_v1
[audit] /content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_v4lite_phase1a_oc_v4lite_cleanrun_v1
                                                    suite_name    group           model_type  seed train_noise_protocol  best_epoch  best_loss  noise_warmup_epochs  noise_ramp_epochs  noise_mix_ratio  epoch_scale_at_best  is_effectively_clean_at_best
 sweep_oc_phase1a_decision_clean_phase1a_oc_v4lite_cleanrun_v1 ablation       ablate_no_lift    42                clean         249   0.004077                   20                 80              0.5                  0.0                          True
 sweep_oc_phase1a_decision_clean_phase1a_oc_v4lite_cleanrun_v1 ablation       ablate_no_lift    43                clean          19   0.216895                   20                 80              0.5                  0.0                          True
 sweep_oc_phase1a_decision_clean_phase1a_oc_v4lite_cleanrun_v1 ablation       ablate_no_lift    44                clean         249   0.004109                   20                 80              0.5                  0.0                          True
 sweep_oc_phase1a_decision_clean_phase1a_oc_v4lite_cleanrun_v1 ablation       ablate_no_lift    45                clean         248   0.004005                   20                 80              0.5                  0.0                          True
 sweep_oc_phase1a_decision_clean_phase1a_oc_v4lite_cleanrun_v1 ablation       ablate_no_lift    46                clean         250   0.004621                   20                 80              0.5                  0.0                          True
   sweep_oc_phase1a_decision_iid_phase1a_oc_v4lite_cleanrun_v1 ablation       ablate_no_lift    42         iid_noisy_ic         240   0.006710                   20                 80              0.5                  1.0                         False
   sweep_oc_phase1a_decision_iid_phase1a_oc_v4lite_cleanrun_v1 ablation       ablate_no_lift    43         iid_noisy_ic         237   0.006294                   20                 80              0.5                  1.0                         False
   sweep_oc_phase1a_decision_iid_phase1a_oc_v4lite_cleanrun_v1 ablation       ablate_no_lift    44         iid_noisy_ic         248   0.006263                   20                 80              0.5                  1.0                         False
   sweep_oc_phase1a_decision_iid_phase1a_oc_v4lite_cleanrun_v1 ablation       ablate_no_lift    45         iid_noisy_ic         237   0.006254                   20                 80              0.5                  1.0                         False
   sweep_oc_phase1a_decision_iid_phase1a_oc_v4lite_cleanrun_v1 ablation       ablate_no_lift    46         iid_noisy_ic         245   0.006636                   20                 80              0.5                  1.0                         False
sweep_oc_phase1a_decision_v4lite_phase1a_oc_v4lite_cleanrun_v1 ablation       ablate_no_lift    42              v4_lite         231   0.006538                   20                 80              0.5                  1.0                         False
sweep_oc_phase1a_decision_v4lite_phase1a_oc_v4lite_cleanrun_v1 ablation       ablate_no_lift    43              v4_lite         245   0.006332                   20                 80              0.5                  1.0                         False
sweep_oc_phase1a_decision_v4lite_phase1a_oc_v4lite_cleanrun_v1 ablation       ablate_no_lift    44              v4_lite         248   0.006335                   20                 80              0.5                  1.0                         False
sweep_oc_phase1a_decision_v4lite_phase1a_oc_v4lite_cleanrun_v1 ablation       ablate_no_lift    45              v4_lite         242   0.006288                   20                 80              0.5                  1.0                         False
sweep_oc_phase1a_decision_v4lite_phase1a_oc_v4lite_cleanrun_v1 ablation       ablate_no_lift    46              v4_lite         248   0.007332                   20                 80              0.5                  1.0                         False
 sweep_oc_phase1a_decision_clean_phase1a_oc_v4lite_cleanrun_v1 ablation ablate_no_mass_prior    42                clean         250   0.004923                   20                 80              0.5                  0.0                          True
 sweep_oc_phase1a_decision_clean_phase1a_oc_v4lite_cleanrun_v1 ablation ablate_no_mass_prior    43                clean         249   0.005489                   20                 80              0.5                  0.0                          True
 sweep_oc_phase1a_decision_clean_phase1a_oc_v4lite_cleanrun_v1 ablation ablate_no_mass_prior    44                clean         248   0.005630                   20                 80              0.5                  0.0                          True
 sweep_oc_phase1a_decision_clean_phase1a_oc_v4lite_cleanrun_v1 ablation ablate_no_mass_prior    45                clean         249   0.004713                   20                 80              0.5                  0.0                          True
 sweep_oc_phase1a_decision_clean_phase1a_oc_v4lite_cleanrun_v1 ablation ablate_no_mass_prior    46                clean         249   0.004738                   20                 80              0.5                  0.0                          True
   sweep_oc_phase1a_decision_iid_phase1a_oc_v4lite_cleanrun_v1 ablation ablate_no_mass_prior    42         iid_noisy_ic         249   0.006579                   20                 80              0.5                  1.0                         False
   sweep_oc_phase1a_decision_iid_phase1a_oc_v4lite_cleanrun_v1 ablation ablate_no_mass_prior    43         iid_noisy_ic         248   0.007758                   20                 80              0.5                  1.0                         False
   sweep_oc_phase1a_decision_iid_phase1a_oc_v4lite_cleanrun_v1 ablation ablate_no_mass_prior    44         iid_noisy_ic         244   0.007265                   20                 80              0.5                  1.0                         False
   sweep_oc_phase1a_decision_iid_phase1a_oc_v4lite_cleanrun_v1 ablation ablate_no_mass_prior    45         iid_noisy_ic         249   0.006893                   20                 80              0.5                  1.0                         False
   sweep_oc_phase1a_decision_iid_phase1a_oc_v4lite_cleanrun_v1 ablation ablate_no_mass_prior    46         iid_noisy_ic         245   0.006658                   20                 80              0.5                  1.0                         False
sweep_oc_phase1a_decision_v4lite_phase1a_oc_v4lite_cleanrun_v1 ablation ablate_no_mass_prior    42              v4_lite         239   0.006673                   20                 80              0.5                  1.0                         False
sweep_oc_phase1a_decision_v4lite_phase1a_oc_v4lite_cleanrun_v1 ablation ablate_no_mass_prior    43              v4_lite         245   0.007099                   20                 80              0.5                  1.0                         False
sweep_oc_phase1a_decision_v4lite_phase1a_oc_v4lite_cleanrun_v1 ablation ablate_no_mass_prior    44              v4_lite         239   0.007446                   20                 80              0.5                  1.0                         False
sweep_oc_phase1a_decision_v4lite_phase1a_oc_v4lite_cleanrun_v1 ablation ablate_no_mass_prior    45              v4_lite         242   0.006988                   20                 80              0.5                  1.0                         False
sweep_oc_phase1a_decision_v4lite_phase1a_oc_v4lite_cleanrun_v1 ablation ablate_no_mass_prior    46              v4_lite         247   0.006770                   20                 80              0.5                  1.0                         False
 sweep_oc_phase1a_decision_clean_phase1a_oc_v4lite_cleanrun_v1     main          phnode_full    42                clean         249   0.004021                   20                 80              0.5                  0.0                          True
 sweep_oc_phase1a_decision_clean_phase1a_oc_v4lite_cleanrun_v1     main          phnode_full    43                clean         247   0.004155                   20                 80              0.5                  0.0                          True
 sweep_oc_phase1a_decision_clean_phase1a_oc_v4lite_cleanrun_v1     main          phnode_full    44                clean         242   0.004207                   20                 80              0.5                  0.0                          True
 sweep_oc_phase1a_decision_clean_phase1a_oc_v4lite_cleanrun_v1     main          phnode_full    45                clean         247   0.004025                   20                 80              0.5                  0.0                          True
 sweep_oc_phase1a_decision_clean_phase1a_oc_v4lite_cleanrun_v1     main          phnode_full    46                clean         250   0.004047                   20                 80              0.5                  0.0                          True
   sweep_oc_phase1a_decision_iid_phase1a_oc_v4lite_cleanrun_v1     main          phnode_full    42         iid_noisy_ic         245   0.006216                   20                 80              0.5                  1.0                         False
   sweep_oc_phase1a_decision_iid_phase1a_oc_v4lite_cleanrun_v1     main          phnode_full    43         iid_noisy_ic         234   0.006302                   20                 80              0.5                  1.0                         False
   sweep_oc_phase1a_decision_iid_phase1a_oc_v4lite_cleanrun_v1     main          phnode_full    44         iid_noisy_ic         248   0.006581                   20                 80              0.5                  1.0                         False
   sweep_oc_phase1a_decision_iid_phase1a_oc_v4lite_cleanrun_v1     main          phnode_full    45         iid_noisy_ic         238   0.006221                   20                 80              0.5                  1.0                         False
   sweep_oc_phase1a_decision_iid_phase1a_oc_v4lite_cleanrun_v1     main          phnode_full    46         iid_noisy_ic         250   0.006382                   20                 80              0.5                  1.0                         False
sweep_oc_phase1a_decision_v4lite_phase1a_oc_v4lite_cleanrun_v1     main          phnode_full    42              v4_lite         204   0.006297                   20                 80              0.5                  1.0                         False
sweep_oc_phase1a_decision_v4lite_phase1a_oc_v4lite_cleanrun_v1     main          phnode_full    43              v4_lite         248   0.006239                   20                 80              0.5                  1.0                         False
sweep_oc_phase1a_decision_v4lite_phase1a_oc_v4lite_cleanrun_v1     main          phnode_full    44              v4_lite         245   0.006270                   20                 80              0.5                  1.0                         False
sweep_oc_phase1a_decision_v4lite_phase1a_oc_v4lite_cleanrun_v1     main          phnode_full    45              v4_lite         247   0.006427                   20                 80              0.5                  1.0                         False
sweep_oc_phase1a_decision_v4lite_phase1a_oc_v4lite_cleanrun_v1     main          phnode_full    46              v4_lite         234   0.006341                   20                 80              0.5                  1.0                         False
[audit] combined CSV: checkpoints/sweep_oc_phase1a_decision_proxy_phase1a_oc_v4lite_cleanrun_v1/phase1a_train_audit.csv
/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_proxy_phase1a_oc_v4lite_cleanrun_v1/phase1a_decision_brief.md

In [ ]:
checkpoints/sweep_oc_phase1a_decision_proxy_phase1a_oc_v4lite_cleanrun_v1/phase1a_summary.csv
checkpoints/sweep_oc_phase1a_decision_proxy_phase1a_oc_v4lite_cleanrun_v1/phase1a_decision_brief.md

## 9. Inspect Phase-1A artifacts

先看 model-level summary，再回到 by-seed / degradation 检查收益是否主要来自单个坏 seed。

In [11]:
from pathlib import Path
import os
import pandas as pd
from IPython.display import Markdown, display

out = Path("checkpoints") / f"sweep_oc_phase1a_decision_proxy_{os.environ['RUN_TAG']}"
print(out)

summary = pd.read_csv(out / "phase1a_summary.csv")
by_seed = pd.read_csv(out / "phase1a_by_seed.csv")
by_horizon = pd.read_csv(out / "phase1a_by_horizon.csv")
degradation = pd.read_csv(out / "phase1a_degradation.csv")
protocol_delta = pd.read_csv(out / "phase1a_protocol_delta.csv")

display(summary.head(20))
display(by_seed.head(20))
display(by_horizon.head(20))
display(degradation.head(20))
display(protocol_delta.head(20))

checkpoints/sweep_oc_phase1a_decision_proxy_phase1a_oc_v4lite_cleanrun_v1

,group,model_type,train_noise_profile,train_noise_protocol,train_protocol_label,source,eval_profile,eval_protocol,eval_protocol_label,horizon_s,...,rollout_final_position_error_p95_min,rollout_final_position_error_p95_max,rollout_final_rotation_geodesic_median_mean,rollout_final_rotation_geodesic_median_std,rollout_final_rotation_geodesic_median_min,rollout_final_rotation_geodesic_median_max,rollout_final_total_linear_velocity_error_median_mean,rollout_final_total_linear_velocity_error_median_std,rollout_final_total_linear_velocity_error_median_min,rollout_final_total_linear_velocity_error_median_max
0,ablation,ablate_no_lift,clean,clean,clean,block,clean,clean,clean,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ablation,ablate_no_lift,clean,clean,clean,block,heading_biased_eval,iid_noisy_ic,iid_noisy_ic,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ablation,ablate_no_lift,clean,clean,clean,block,nominal_eval,iid_noisy_ic,iid_noisy_ic,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ablation,ablate_no_lift,clean,clean,clean,heldout,clean,clean,clean,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ablation,ablate_no_lift,clean,clean,clean,heldout,degraded_eval,iid_noisy_ic,iid_noisy_ic,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,ablation,ablate_no_lift,clean,clean,clean,heldout,heading_biased_eval,iid_noisy_ic,iid_noisy_ic,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,ablation,ablate_no_lift,clean,clean,clean,heldout,nominal_eval,iid_noisy_ic,iid_noisy_ic,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,ablation,ablate_no_lift,clean,clean,clean,rollout,clean,clean,clean,10.0,...,0.123407,7.654650,0.033426,0.054038,0.004809,0.141427,0.090195,0.161193,0.006004,0.412504
8,ablation,ablate_no_lift,clean,clean,clean,rollout,clean,clean,clean,30.0,...,0.527066,29.829862,0.047738,0.072286,0.007539,0.192001,0.173345,0.326877,0.007235,0.827079
9,ablation,ablate_no_lift,clean,clean,clean,rollout,clean,clean,clean,60.0,...,1.278867,74.984107,0.076565,0.114820,0.010432,0.305216,0.248273,0.473799,0.007363,1.195837
10,ablation,ablate_no_lift,clean,clean,clean,rollout,nominal_eval,iid_noisy_ic,iid_noisy_ic,10.0,...,0.383336,7.609423,0.037581,0.053312,0.010063,0.144193,0.090658,0.161449,0.006797,0.413492
11,ablation,ablate_no_lift,clean,clean,clean,rollout,nominal_eval,iid_noisy_ic,iid_noisy_ic,30.0,...,1.108152,29.952598,0.048844,0.070459,0.010541,0.189577,0.174337,0.327715,0.007871,0.829750
12,ablation,ablate_no_lift,clean,clean,clean,rollout,nominal_eval,iid_noisy_ic,iid_noisy_ic,60.0,...,2.578486,74.656600,0.077385,0.112828,0.014169,0.302244,0.248870,0.474046,0.007893,1.196932
13,ablation,ablate_no_lift,clean,clean,clean,rollout,nominal_eval,v4_lite,v4_lite,10.0,...,0.273539,7.657920,0.037364,0.055756,0.007680,0.148804,0.090199,0.161038,0.006683,0.412219
14,ablation,ablate_no_lift,clean,clean,clean,rollout,nominal_eval,v4_lite,v4_lite,30.0,...,0.932726,29.951731,0.049981,0.072459,0.008976,0.194615,0.173923,0.327585,0.007765,0.829077
15,ablation,ablate_no_lift,clean,clean,clean,rollout,nominal_eval,v4_lite,v4_lite,60.0,...,2.039898,74.782526,0.077244,0.114881,0.012035,0.306215,0.248444,0.473345,0.007252,1.195102
16,ablation,ablate_no_lift,nominal_train,iid_noisy_ic,iid_noisy_ic,block,clean,clean,clean,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,ablation,ablate_no_lift,nominal_train,iid_noisy_ic,iid_noisy_ic,block,heading_biased_eval,iid_noisy_ic,iid_noisy_ic,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,ablation,ablate_no_lift,nominal_train,iid_noisy_ic,iid_noisy_ic,block,nominal_eval,iid_noisy_ic,iid_noisy_ic,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,ablation,ablate_no_lift,nominal_train,iid_noisy_ic,iid_noisy_ic,heldout,clean,clean,clean,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,suite_name,group,model_type,seed,run_name,run_dir,dataset_path,dataset_id,noise_reference,best_epoch,...,rollout_final_position_error_median,rollout_final_position_error_p95,rollout_final_rotation_geodesic_median,rollout_final_total_linear_velocity_error_median,source,eval_profile,eval_protocol,eval_protocol_label,horizon_s,summary_path
0,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,clean__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,d0be9434,remus100_dr,249.0,...,NaN,NaN,NaN,NaN,block,clean,clean,clean,NaN,/content/drive/MyDrive/Colab Notebooks/auvhamn...
1,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,clean__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,d0be9434,remus100_dr,249.0,...,NaN,NaN,NaN,NaN,block,heading_biased_eval,iid_noisy_ic,iid_noisy_ic,NaN,/content/drive/MyDrive/Colab Notebooks/auvhamn...
2,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,clean__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,d0be9434,remus100_dr,249.0,...,NaN,NaN,NaN,NaN,block,nominal_eval,iid_noisy_ic,iid_noisy_ic,NaN,/content/drive/MyDrive/Colab Notebooks/auvhamn...
3,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,clean__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,d0be9434,remus100_dr,249.0,...,NaN,NaN,NaN,NaN,heldout,clean,clean,clean,NaN,/content/drive/MyDrive/Colab Notebooks/auvhamn...
4,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,clean__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,d0be9434,remus100_dr,249.0,...,NaN,NaN,NaN,NaN,heldout,degraded_eval,iid_noisy_ic,iid_noisy_ic,NaN,/content/drive/MyDrive/Colab Notebooks/auvhamn...
5,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,clean__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,d0be9434,remus100_dr,249.0,...,NaN,NaN,NaN,NaN,heldout,heading_biased_eval,iid_noisy_ic,iid_noisy_ic,NaN,/content/drive/MyDrive/Colab Notebooks/auvhamn...
6,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,clean__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,d0be9434,remus100_dr,249.0,...,NaN,NaN,NaN,NaN,heldout,nominal_eval,iid_noisy_ic,iid_noisy_ic,NaN,/content/drive/MyDrive/Colab Notebooks/auvhamn...
7,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,clean__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,d0be9434,remus100_dr,249.0,...,0.052122,0.123407,0.004883,0.006004,rollout,clean,clean,clean,10.0,/content/drive/MyDrive/Colab Notebooks/auvhamn...
8,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,clean__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,d0be9434,remus100_dr,249.0,...,0.183027,0.587181,0.007631,0.007574,rollout,clean,clean,clean,30.0,/content/drive/MyDrive/Colab Notebooks/auvhamn...
9,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,clean__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,d0be9434,remus100_dr,249.0,...,0.526213,1.278867,0.010432,0.007363,rollout,clean,clean,clean,60.0,/content/drive/MyDrive/Colab Notebooks/auvhamn...
10,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,clean__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,d0be9434,remus100_dr,249.0,...,0.129634,0.385438,0.010063,0.007456,rollout,nominal_eval,iid_noisy_ic,iid_noisy_ic,10.0,/content/drive/MyDrive/Colab Notebooks/auvhamn...
11,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,clean__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,d0be9434,remus100_dr,249.0,...,0.104402,0.273539,0.007866,0.006683,rollout,nominal_eval,v4_lite,v4_lite,10.0,/content/drive/MyDrive/Colab Notebooks/auvhamn...
12,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,clean__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,d0be9434,remus100_dr,249.0,...,0.379677,1.108152,0.010748,0.008169,rollout,nominal_eval,iid_noisy_ic,iid_noisy_ic,30.0,/content/drive/MyDrive/Colab Notebooks/auvhamn...
13,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,clean__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,d0be9434,remus100_dr,249.0,...,0.301280,0.932726,0.010642,0.007765,rollout,nominal_eval,v4_lite,v4_lite,30.0,/content/drive/MyDrive/Colab Notebooks/auvhamn...
14,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,clean__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,d0be9434,remus100_dr,249.0,...,0.811416,2.583290,0.014169,0.007893,rollout,nominal_eval,iid_noisy_ic,iid_noisy_ic,60.0,/content/drive/MyDrive/Colab Notebooks/auvhamn...
15,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,clean__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,d0be9434,remus100_dr,249.0,...,0.732413,2.039898,0.012035,0.009001,rollout,nominal_eval,v4_lite,v4_lite,60.0,/content/drive/MyDrive/Colab Notebooks/auvhamn...
16,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,43,clean__ablation_ablate_no_lift_seed43,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,d0be9434,remus100_dr,19.0,...,NaN,NaN,NaN,NaN,block,clean,clean,clean,NaN,/content/drive/MyDrive/Colab Notebooks/auvhamn...
17,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,43,clean__ablation_ablate_no_lift_seed43,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,d0be9434,remus100_dr,19.0,...,NaN,NaN,NaN,NaN,heldout,clean,clean,clean,NaN,/content/drive/MyDrive/Colab Notebooks/auvhamn...
18,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,43,clean__ablation_ablate_no_lift_seed43,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,d0be9434,remus100_dr,19.0,...,3.216109,7.654650,0.141427,0.412504,rollout,clean,clean,clean,10.0,/content/drive/MyDrive/Colab Notebooks/auvhamn...
19,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,43,clean__ablation_ablate_no_lift_seed43,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,d0be9434,remus100_dr,19.0,...,14.788132,29.829862,0.192001,0.827079,rollout,clean,clean,clean,30.0,/content/drive/MyDrive/Colab Notebooks/auvhamn...

,group,model_type,train_noise_profile,train_noise_protocol,train_protocol_label,source,eval_profile,eval_protocol,eval_protocol_label,horizon_s,...,rollout_final_position_error_p95_min,rollout_final_position_error_p95_max,rollout_final_rotation_geodesic_median_mean,rollout_final_rotation_geodesic_median_std,rollout_final_rotation_geodesic_median_min,rollout_final_rotation_geodesic_median_max,rollout_final_total_linear_velocity_error_median_mean,rollout_final_total_linear_velocity_error_median_std,rollout_final_total_linear_velocity_error_median_min,rollout_final_total_linear_velocity_error_median_max
0,ablation,ablate_no_lift,clean,clean,clean,rollout,clean,clean,clean,10.0,...,0.123407,7.654650,0.033426,0.054038,0.004809,0.141427,0.090195,0.161193,0.006004,0.412504
1,ablation,ablate_no_lift,clean,clean,clean,rollout,clean,clean,clean,30.0,...,0.527066,29.829862,0.047738,0.072286,0.007539,0.192001,0.173345,0.326877,0.007235,0.827079
2,ablation,ablate_no_lift,clean,clean,clean,rollout,clean,clean,clean,60.0,...,1.278867,74.984107,0.076565,0.114820,0.010432,0.305216,0.248273,0.473799,0.007363,1.195837
3,ablation,ablate_no_lift,clean,clean,clean,rollout,nominal_eval,iid_noisy_ic,iid_noisy_ic,10.0,...,0.383336,7.609423,0.037581,0.053312,0.010063,0.144193,0.090658,0.161449,0.006797,0.413492
4,ablation,ablate_no_lift,clean,clean,clean,rollout,nominal_eval,iid_noisy_ic,iid_noisy_ic,30.0,...,1.108152,29.952598,0.048844,0.070459,0.010541,0.189577,0.174337,0.327715,0.007871,0.829750
5,ablation,ablate_no_lift,clean,clean,clean,rollout,nominal_eval,iid_noisy_ic,iid_noisy_ic,60.0,...,2.578486,74.656600,0.077385,0.112828,0.014169,0.302244,0.248870,0.474046,0.007893,1.196932
6,ablation,ablate_no_lift,clean,clean,clean,rollout,nominal_eval,v4_lite,v4_lite,10.0,...,0.273539,7.657920,0.037364,0.055756,0.007680,0.148804,0.090199,0.161038,0.006683,0.412219
7,ablation,ablate_no_lift,clean,clean,clean,rollout,nominal_eval,v4_lite,v4_lite,30.0,...,0.932726,29.951731,0.049981,0.072459,0.008976,0.194615,0.173923,0.327585,0.007765,0.829077
8,ablation,ablate_no_lift,clean,clean,clean,rollout,nominal_eval,v4_lite,v4_lite,60.0,...,2.039898,74.782526,0.077244,0.114881,0.012035,0.306215,0.248444,0.473345,0.007252,1.195102
9,ablation,ablate_no_lift,nominal_train,iid_noisy_ic,iid_noisy_ic,rollout,clean,clean,clean,10.0,...,0.215688,0.289163,0.008126,0.002170,0.005610,0.012094,0.012166,0.001644,0.009586,0.013829
10,ablation,ablate_no_lift,nominal_train,iid_noisy_ic,iid_noisy_ic,rollout,clean,clean,clean,30.0,...,0.547644,1.031821,0.011014,0.002210,0.007626,0.014189,0.012098,0.001493,0.009906,0.014549
11,ablation,ablate_no_lift,nominal_train,iid_noisy_ic,iid_noisy_ic,rollout,clean,clean,clean,60.0,...,1.954489,3.580324,0.015299,0.001712,0.013260,0.017738,0.012551,0.001215,0.010814,0.014502
12,ablation,ablate_no_lift,nominal_train,iid_noisy_ic,iid_noisy_ic,rollout,nominal_eval,iid_noisy_ic,iid_noisy_ic,10.0,...,0.402435,0.466386,0.011296,0.002521,0.009122,0.016160,0.012736,0.001649,0.010487,0.014549
13,ablation,ablate_no_lift,nominal_train,iid_noisy_ic,iid_noisy_ic,rollout,nominal_eval,iid_noisy_ic,iid_noisy_ic,30.0,...,1.280497,1.481445,0.013750,0.002434,0.010692,0.017780,0.012173,0.001406,0.009965,0.014394
14,ablation,ablate_no_lift,nominal_train,iid_noisy_ic,iid_noisy_ic,rollout,nominal_eval,iid_noisy_ic,iid_noisy_ic,60.0,...,3.032554,4.251268,0.017247,0.002046,0.015506,0.021023,0.013366,0.001268,0.011186,0.014884
15,ablation,ablate_no_lift,nominal_train,iid_noisy_ic,iid_noisy_ic,rollout,nominal_eval,v4_lite,v4_lite,10.0,...,0.305016,0.403039,0.011014,0.001276,0.009094,0.013096,0.012406,0.001672,0.009994,0.014377
16,ablation,ablate_no_lift,nominal_train,iid_noisy_ic,iid_noisy_ic,rollout,nominal_eval,v4_lite,v4_lite,30.0,...,1.079749,1.345154,0.013789,0.002124,0.010873,0.017177,0.012531,0.001614,0.010097,0.015051
17,ablation,ablate_no_lift,nominal_train,iid_noisy_ic,iid_noisy_ic,rollout,nominal_eval,v4_lite,v4_lite,60.0,...,2.578771,3.458116,0.018255,0.001965,0.015852,0.021583,0.013067,0.000974,0.011777,0.014568
18,ablation,ablate_no_lift,nominal_train,v4_lite,v4_lite,rollout,clean,clean,clean,10.0,...,0.194638,0.366258,0.009436,0.003299,0.005736,0.015617,0.013234,0.003016,0.010477,0.018960
19,ablation,ablate_no_lift,nominal_train,v4_lite,v4_lite,rollout,clean,clean,clean,30.0,...,0.793250,1.667035,0.016963,0.007642,0.009105,0.031472,0.013387,0.003305,0.009744,0.019607

,comparison_kind,suite_name,group,model_type,seed,run_name,run_dir,source,metric_name,horizon_s,...,baseline_train_protocol_label,eval_profile,baseline_eval_profile,eval_protocol,baseline_eval_protocol,value,clean_value,absolute_delta,ratio_to_clean,degradation_pct
0,clean_replay_cost,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,iid__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,block,block_angular_rmse_mean,NaN,...,clean,clean,clean,clean,clean,0.001124,0.000602,0.000522,1.866737,86.673683
1,clean_replay_cost,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,iid__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,block,block_position_rmse_mean,NaN,...,clean,clean,clean,clean,clean,0.000155,0.000090,0.000065,1.730366,73.036574
2,clean_replay_cost,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,iid__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,block,block_rotation_geodesic_mean,NaN,...,clean,clean,clean,clean,clean,0.000493,0.000489,0.000004,1.008295,0.829501
3,clean_replay_cost,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,iid__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,block,block_velocity_rmse_mean,NaN,...,clean,clean,clean,clean,clean,0.001803,0.001072,0.000731,1.681408,68.140819
4,clean_replay_cost,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,iid__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,heldout,heldout_angular_rmse_mean,NaN,...,clean,clean,clean,clean,clean,0.000951,0.000512,0.000439,1.856780,85.677999
5,clean_replay_cost,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,iid__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,heldout,heldout_position_rmse_mean,NaN,...,clean,clean,clean,clean,clean,0.000126,0.000071,0.000055,1.779302,77.930172
6,clean_replay_cost,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,iid__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,heldout,heldout_rotation_geodesic_mean,NaN,...,clean,clean,clean,clean,clean,0.000491,0.000489,0.000002,1.005086,0.508550
7,clean_replay_cost,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,iid__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,heldout,heldout_success_rate,NaN,...,clean,clean,clean,clean,clean,1.000000,1.000000,0.000000,1.000000,0.000000
8,clean_replay_cost,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,iid__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,heldout,heldout_velocity_rmse_mean,NaN,...,clean,clean,clean,clean,clean,0.001457,0.000839,0.000617,1.735873,73.587295
9,clean_replay_cost,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,iid__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,rollout,rollout_completion_rate,10.0,...,clean,clean,clean,clean,clean,1.000000,1.000000,0.000000,1.000000,0.000000
10,clean_replay_cost,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,iid__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,rollout,rollout_completion_rate,30.0,...,clean,clean,clean,clean,clean,1.000000,1.000000,0.000000,1.000000,0.000000
11,clean_replay_cost,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,iid__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,rollout,rollout_completion_rate,60.0,...,clean,clean,clean,clean,clean,0.977778,0.977778,0.000000,1.000000,0.000000
12,clean_replay_cost,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,iid__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,rollout,rollout_final_position_error_median,10.0,...,clean,clean,clean,clean,clean,0.124091,0.052122,0.071968,2.380760,138.075994
13,clean_replay_cost,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,iid__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,rollout,rollout_final_position_error_median,30.0,...,clean,clean,clean,clean,clean,0.397276,0.183027,0.214249,2.170589,117.058852
14,clean_replay_cost,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,iid__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,rollout,rollout_final_position_error_median,60.0,...,clean,clean,clean,clean,clean,0.889952,0.526213,0.363739,1.691240,69.123963
15,clean_replay_cost,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,iid__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,rollout,rollout_final_position_error_p95,10.0,...,clean,clean,clean,clean,clean,0.285610,0.123407,0.162203,2.314377,131.437677
16,clean_replay_cost,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,iid__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,rollout,rollout_final_position_error_p95,30.0,...,clean,clean,clean,clean,clean,0.942936,0.587181,0.355755,1.605869,60.586876
17,clean_replay_cost,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,iid__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,rollout,rollout_final_position_error_p95,60.0,...,clean,clean,clean,clean,clean,3.580324,1.278867,2.301457,2.799607,179.960684
18,clean_replay_cost,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,iid__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,rollout,rollout_final_rotation_geodesic_median,10.0,...,clean,clean,clean,clean,clean,0.008343,0.004883,0.003461,1.708799,70.879930
19,clean_replay_cost,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,iid__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,rollout,rollout_final_rotation_geodesic_median,30.0,...,clean,clean,clean,clean,clean,0.012319,0.007631,0.004688,1.614389,61.438936

,comparison_kind,table_scope,suite_name,group,model_type,seed,run_name,baseline_run_name,run_dir,baseline_run_dir,...,baseline_eval_protocol_label,summary_path,baseline_summary_path,metric_name,value,baseline_value,absolute_delta,ratio_to_baseline,degradation_pct,improvement_pct
0,eval_protocol_v4_lite_vs_iid_noisy_ic,by_scenario,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,clean__ablation_ablate_no_lift_seed42,clean__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,...,iid_noisy_ic,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,rollout_completion_rate,1.000000,1.000000,0.000000,1.000000,0.000000,-0.000000
1,eval_protocol_v4_lite_vs_iid_noisy_ic,by_scenario,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,clean__ablation_ablate_no_lift_seed42,clean__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,...,iid_noisy_ic,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,rollout_completion_rate,1.000000,1.000000,0.000000,1.000000,0.000000,-0.000000
2,eval_protocol_v4_lite_vs_iid_noisy_ic,by_scenario,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,clean__ablation_ablate_no_lift_seed42,clean__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,...,iid_noisy_ic,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,rollout_completion_rate,1.000000,1.000000,0.000000,1.000000,0.000000,-0.000000
3,eval_protocol_v4_lite_vs_iid_noisy_ic,by_scenario,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,clean__ablation_ablate_no_lift_seed42,clean__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,...,iid_noisy_ic,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,rollout_final_position_error_median,0.103742,0.125072,-0.021330,0.829460,-17.053991,17.053991
4,eval_protocol_v4_lite_vs_iid_noisy_ic,by_scenario,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,clean__ablation_ablate_no_lift_seed42,clean__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,...,iid_noisy_ic,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,rollout_final_position_error_median,0.353640,0.383184,-0.029544,0.922899,-7.710114,7.710114
5,eval_protocol_v4_lite_vs_iid_noisy_ic,by_scenario,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,clean__ablation_ablate_no_lift_seed42,clean__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,...,iid_noisy_ic,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,rollout_final_position_error_median,0.697540,0.777395,-0.079855,0.897278,-10.272184,10.272184
6,eval_protocol_v4_lite_vs_iid_noisy_ic,by_scenario,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,clean__ablation_ablate_no_lift_seed42,clean__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,...,iid_noisy_ic,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,rollout_final_position_error_p95,0.278621,0.326892,-0.048272,0.852331,-14.766881,14.766881
7,eval_protocol_v4_lite_vs_iid_noisy_ic,by_scenario,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,clean__ablation_ablate_no_lift_seed42,clean__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,...,iid_noisy_ic,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,rollout_final_position_error_p95,0.946802,0.963046,-0.016244,0.983133,-1.686721,1.686721
8,eval_protocol_v4_lite_vs_iid_noisy_ic,by_scenario,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,clean__ablation_ablate_no_lift_seed42,clean__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,...,iid_noisy_ic,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,rollout_final_position_error_p95,1.968843,2.004337,-0.035494,0.982291,-1.770863,1.770863
9,eval_protocol_v4_lite_vs_iid_noisy_ic,by_scenario,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,clean__ablation_ablate_no_lift_seed42,clean__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,...,iid_noisy_ic,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,rollout_final_rotation_geodesic_median,0.008355,0.009775,-0.001420,0.854734,-14.526562,14.526562
10,eval_protocol_v4_lite_vs_iid_noisy_ic,by_scenario,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,clean__ablation_ablate_no_lift_seed42,clean__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,...,iid_noisy_ic,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,rollout_final_rotation_geodesic_median,0.008434,0.009710,-0.001276,0.868594,-13.140603,13.140603
11,eval_protocol_v4_lite_vs_iid_noisy_ic,by_scenario,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,clean__ablation_ablate_no_lift_seed42,clean__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,...,iid_noisy_ic,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,rollout_final_rotation_geodesic_median,0.010888,0.007638,0.003250,1.425496,42.549576,-42.549576
12,eval_protocol_v4_lite_vs_iid_noisy_ic,by_scenario,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,clean__ablation_ablate_no_lift_seed42,clean__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,...,iid_noisy_ic,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,rollout_final_total_linear_velocity_error_median,0.005275,0.005624,-0.000349,0.937909,-6.209139,6.209139
13,eval_protocol_v4_lite_vs_iid_noisy_ic,by_scenario,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,clean__ablation_ablate_no_lift_seed42,clean__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,...,iid_noisy_ic,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,rollout_final_total_linear_velocity_error_median,0.006049,0.005775,0.000274,1.047456,4.745551,-4.745551
14,eval_protocol_v4_lite_vs_iid_noisy_ic,by_scenario,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,clean__ablation_ablate_no_lift_seed42,clean__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,...,iid_noisy_ic,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,rollout_final_total_linear_velocity_error_median,0.005852,0.005897,-0.000045,0.992400,-0.760035,0.760035
15,eval_protocol_v4_lite_vs_iid_noisy_ic,by_scenario,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,clean__ablation_ablate_no_lift_seed42,clean__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,...,iid_noisy_ic,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,rollout_gt_failed_rate,0.000000,0.000000,0.000000,1.000000,0.000000,-0.000000
16,eval_protocol_v4_lite_vs_iid_noisy_ic,by_scenario,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,clean__ablation_ablate_no_lift_seed42,clean__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,...,iid_noisy_ic,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,rollout_gt_failed_rate,0.000000,0.000000,0.000000,1.000000,0.000000,-0.000000
17,eval_protocol_v4_lite_vs_iid_noisy_ic,by_scenario,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,clean__ablation_ablate_no_lift_seed42,clean__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,...,iid_noisy_ic,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,rollout_gt_failed_rate,0.000000,0.000000,0.000000,1.000000,0.000000,-0.000000
18,eval_protocol_v4_lite_vs_iid_noisy_ic,by_scenario,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,clean__ablation_ablate_no_lift_seed42,clean__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,...,iid_noisy_ic,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,rollout_model_failed_rate,0.000000,0.000000,0.000000,1.000000,0.000000,-0.000000
19,eval_protocol_v4_lite_vs_iid_noisy_ic,by_scenario,sweep_oc_phase1a_decision_proxy_phase1a_oc_v4l...,ablation,ablate_no_lift,42,clean__ablation_ablate_no_lift_seed42,clean__ablation_ablate_no_lift_seed42,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,...,iid_noisy_ic,/content/drive/MyDrive/Colab Notebooks/auvhamn...,/content/drive/MyDrive/Colab Notebooks/auvhamn...,rollout_model_failed_rate,0.000000,0.000000,0.000000,1.000000,0.000000,-0.000000

In [12]:
brief = Path("checkpoints") / f"sweep_oc_phase1a_decision_proxy_{os.environ['RUN_TAG']}" / "phase1a_decision_brief.md"
display(Markdown(brief.read_text()))

# Phase-1A Decision Brief

- Suite: `/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_7/checkpoints/sweep_oc_phase1a_decision_proxy_phase1a_oc_v4lite_cleanrun_v1`
- Generated: `2026-04-26 15:54:03`
- Runs: `45`
- Horizons: `10s, 30s, 60s`
- Primary rollout profile: `nominal_eval`
- Primary heldout profile: `nominal_eval`
- Dataset: `/content/drive/MyDrive/Colab Notebooks/auvhamnode/g3_5_5/data/auv_oc_traj1000_blk150_s23_d0be9434.pkl`

## Key Findings

- Best rollout aggregate at `60s` / `nominal_eval` is `main/phnode_full` under train protocol `clean` and eval protocol `v4_lite`, with `pos median=0.8439 m` and `completion=99.1%`.
- `phnode_full` still shows seed sensitivity at `60s`: position-median range across matching rows is `0.7852 m`.
- Clean replay cost rows are available for `6` non-clean training groups, so the report can distinguish robustness gains from clean-performance regressions.

## Scope

- Scope: this Phase-1A decision brief covers the OC known-current surrogate tier only, which is the intended Phase-1A data layer.

## Rollout Summary @60s / nominal_eval

| Model | Train | Eval | Seeds | Pos Median | Pos P95 | Completion | Model Fail |
| --- | --- | --- | --- | --- | --- | --- | --- |
| main/phnode_full | clean | v4_lite | 42,43,44,45,46 | 0.8439 | 2.1544 | 99.1% | 0.9% |
| main/phnode_full | clean | iid_noisy_ic | 42,43,44,45,46 | 0.9604 | 2.8640 | 99.1% | 0.9% |
| ablation/ablate_no_lift | iid_noisy_ic/nominal_train | iid_noisy_ic | 42,43,44,45,46 | 1.0043 | 3.4515 | 98.2% | 1.8% |
| main/phnode_full | iid_noisy_ic/nominal_train | v4_lite | 42,43,44,45,46 | 1.0317 | 2.9404 | 98.4% | 1.6% |
| ablation/ablate_no_lift | iid_noisy_ic/nominal_train | v4_lite | 42,43,44,45,46 | 1.0551 | 3.0847 | 98.2% | 1.8% |
| main/phnode_full | iid_noisy_ic/nominal_train | iid_noisy_ic | 42,43,44,45,46 | 1.0934 | 3.2639 | 98.2% | 1.8% |
| main/phnode_full | v4_lite/nominal_train | iid_noisy_ic | 42,43,44,45,46 | 1.1116 | 3.3398 | 98.2% | 1.8% |
| main/phnode_full | v4_lite/nominal_train | v4_lite | 42,43,44,45,46 | 1.1148 | 2.9198 | 98.2% | 1.8% |
| ablation/ablate_no_lift | v4_lite/nominal_train | iid_noisy_ic | 42,43,44,45,46 | 1.2696 | 3.6817 | 98.4% | 1.6% |
| ablation/ablate_no_lift | v4_lite/nominal_train | v4_lite | 42,43,44,45,46 | 1.3078 | 3.5389 | 98.4% | 1.6% |
| ablation/ablate_no_mass_prior | v4_lite/nominal_train | iid_noisy_ic | 42,43,44,45,46 | 1.4021 | 4.5957 | 98.2% | 1.8% |
| ablation/ablate_no_mass_prior | v4_lite/nominal_train | v4_lite | 42,43,44,45,46 | 1.4075 | 4.0668 | 98.4% | 1.6% |
| ablation/ablate_no_mass_prior | clean | iid_noisy_ic | 42,43,44,45,46 | 1.4163 | 4.6889 | 98.7% | 1.3% |
| ablation/ablate_no_mass_prior | iid_noisy_ic/nominal_train | iid_noisy_ic | 42,43,44,45,46 | 1.4613 | 4.3018 | 98.2% | 1.8% |
| ablation/ablate_no_mass_prior | clean | v4_lite | 42,43,44,45,46 | 1.4622 | 4.2905 | 98.7% | 1.3% |
| ablation/ablate_no_mass_prior | iid_noisy_ic/nominal_train | v4_lite | 42,43,44,45,46 | 1.5156 | 3.8697 | 98.2% | 1.8% |
| ablation/ablate_no_lift | clean | v4_lite | 42,43,44,45,46 | 9.6808 | 17.1002 | 98.9% | 1.1% |
| ablation/ablate_no_lift | clean | iid_noisy_ic | 42,43,44,45,46 | 9.7397 | 17.4667 | 98.9% | 1.1% |

## Heldout Summary / nominal_eval

| Model | Train | Seeds | Pos RMSE Mean | Rot Geo Mean | Success |
| --- | --- | --- | --- | --- | --- |
| main/phnode_full | clean | 42,44,46 | 0.00111 | 0.00860 | 100.0% |
| ablation/ablate_no_lift | clean | 42,44,46 | 0.00111 | 0.00861 | 100.0% |
| ablation/ablate_no_lift | iid_noisy_ic/nominal_train | 42,44,46 | 0.00111 | 0.00862 | 100.0% |
| main/phnode_full | iid_noisy_ic/nominal_train | 42,44,46 | 0.00111 | 0.00862 | 100.0% |
| ablation/ablate_no_mass_prior | iid_noisy_ic/nominal_train | 42,44,46 | 0.00111 | 0.00862 | 100.0% |
| ablation/ablate_no_mass_prior | clean | 42,44,46 | 0.00111 | 0.00861 | 100.0% |
| ablation/ablate_no_mass_prior | v4_lite/nominal_train | 42,44,46 | 0.00111 | 0.00869 | 100.0% |
| main/phnode_full | v4_lite/nominal_train | 42,44,46 | 0.00111 | 0.00869 | 100.0% |
| ablation/ablate_no_lift | v4_lite/nominal_train | 42,44,46 | 0.00112 | 0.00869 | 100.0% |

## Rollout By Horizon / nominal_eval

| Model | Train | Eval | Pos @10s | Pos @30s | Pos @60s | Completion @60s |
| --- | --- | --- | --- | --- | --- | --- |
| main/phnode_full | clean | v4_lite | 0.1348 | 0.3824 | 0.8439 | 99.1% |
| main/phnode_full | clean | iid_noisy_ic | 0.1568 | 0.4188 | 0.9604 | 99.1% |
| ablation/ablate_no_lift | iid_noisy_ic/nominal_train | iid_noisy_ic | 0.1669 | 0.4582 | 1.0043 | 98.2% |
| main/phnode_full | iid_noisy_ic/nominal_train | v4_lite | 0.1474 | 0.4492 | 1.0317 | 98.4% |
| ablation/ablate_no_lift | iid_noisy_ic/nominal_train | v4_lite | 0.1620 | 0.4538 | 1.0551 | 98.2% |
| main/phnode_full | iid_noisy_ic/nominal_train | iid_noisy_ic | 0.1697 | 0.4716 | 1.0934 | 98.2% |
| main/phnode_full | v4_lite/nominal_train | iid_noisy_ic | 0.1620 | 0.4521 | 1.1116 | 98.2% |
| main/phnode_full | v4_lite/nominal_train | v4_lite | 0.1520 | 0.4604 | 1.1148 | 98.2% |
| ablation/ablate_no_lift | v4_lite/nominal_train | iid_noisy_ic | 0.1703 | 0.4929 | 1.2696 | 98.4% |
| ablation/ablate_no_lift | v4_lite/nominal_train | v4_lite | 0.1632 | 0.4875 | 1.3078 | 98.4% |
| ablation/ablate_no_mass_prior | v4_lite/nominal_train | iid_noisy_ic | 0.1900 | 0.6120 | 1.4021 | 98.2% |
| ablation/ablate_no_mass_prior | v4_lite/nominal_train | v4_lite | 0.1779 | 0.6009 | 1.4075 | 98.4% |
| ablation/ablate_no_mass_prior | clean | iid_noisy_ic | 0.1954 | 0.6255 | 1.4163 | 98.7% |
| ablation/ablate_no_mass_prior | iid_noisy_ic/nominal_train | iid_noisy_ic | 0.1872 | 0.5760 | 1.4613 | 98.2% |
| ablation/ablate_no_mass_prior | clean | v4_lite | 0.1874 | 0.6525 | 1.4622 | 98.7% |
| ablation/ablate_no_mass_prior | iid_noisy_ic/nominal_train | v4_lite | 0.1781 | 0.5886 | 1.5156 | 98.2% |
| ablation/ablate_no_lift | clean | v4_lite | 0.7506 | 3.2548 | 9.6808 | 98.9% |
| ablation/ablate_no_lift | clean | iid_noisy_ic | 0.7881 | 3.3884 | 9.7397 | 98.9% |

## Rollout By Scenario @60s / nominal_eval

| Model | Train | Eval | Scenario | Completion | Model Fail | Pos Median | Pos P95 | Rot Median |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| ablation/ablate_no_lift | clean | iid_noisy_ic | CHIRP | 100.0% | 0.0% | 9.7736 | 12.1483 | 0.0590 |
| ablation/ablate_no_lift | clean | iid_noisy_ic | OU | 96.7% | 3.3% | 10.3707 | 17.3041 | 0.1854 |
| ablation/ablate_no_lift | clean | iid_noisy_ic | PRBS | 100.0% | 0.0% | 8.8025 | 18.9399 | 0.0594 |
| ablation/ablate_no_lift | clean | v4_lite | CHIRP | 100.0% | 0.0% | 9.8137 | 12.4841 | 0.0583 |
| ablation/ablate_no_lift | clean | v4_lite | OU | 96.7% | 3.3% | 10.1888 | 16.5584 | 0.1820 |
| ablation/ablate_no_lift | clean | v4_lite | PRBS | 100.0% | 0.0% | 8.6724 | 18.2717 | 0.0587 |
| ablation/ablate_no_lift | iid_noisy_ic/nominal_train | iid_noisy_ic | CHIRP | 100.0% | 0.0% | 0.8016 | 2.3218 | 0.0128 |
| ablation/ablate_no_lift | iid_noisy_ic/nominal_train | iid_noisy_ic | OU | 94.7% | 5.3% | 1.4331 | 4.2132 | 0.0330 |
| ablation/ablate_no_lift | iid_noisy_ic/nominal_train | iid_noisy_ic | PRBS | 100.0% | 0.0% | 0.8955 | 2.9182 | 0.0154 |
| ablation/ablate_no_lift | iid_noisy_ic/nominal_train | v4_lite | CHIRP | 100.0% | 0.0% | 0.9594 | 2.3745 | 0.0125 |
| ablation/ablate_no_lift | iid_noisy_ic/nominal_train | v4_lite | OU | 94.7% | 5.3% | 1.2316 | 3.8106 | 0.0308 |
| ablation/ablate_no_lift | iid_noisy_ic/nominal_train | v4_lite | PRBS | 100.0% | 0.0% | 0.8889 | 2.7336 | 0.0180 |
| ablation/ablate_no_lift | v4_lite/nominal_train | iid_noisy_ic | CHIRP | 100.0% | 0.0% | 1.4289 | 2.8832 | 0.0326 |
| ablation/ablate_no_lift | v4_lite/nominal_train | iid_noisy_ic | OU | 95.3% | 4.7% | 1.4524 | 3.8966 | 0.0343 |
| ablation/ablate_no_lift | v4_lite/nominal_train | iid_noisy_ic | PRBS | 100.0% | 0.0% | 1.0962 | 3.2329 | 0.0235 |
| ablation/ablate_no_lift | v4_lite/nominal_train | v4_lite | CHIRP | 100.0% | 0.0% | 1.4273 | 3.0853 | 0.0335 |
| ablation/ablate_no_lift | v4_lite/nominal_train | v4_lite | OU | 95.3% | 4.7% | 1.2267 | 3.7117 | 0.0299 |
| ablation/ablate_no_lift | v4_lite/nominal_train | v4_lite | PRBS | 100.0% | 0.0% | 1.2443 | 3.0464 | 0.0257 |
| ablation/ablate_no_mass_prior | clean | iid_noisy_ic | CHIRP | 100.0% | 0.0% | 1.2412 | 3.0954 | 0.0214 |
| ablation/ablate_no_mass_prior | clean | iid_noisy_ic | OU | 96.0% | 4.0% | 2.0360 | 5.4938 | 0.0502 |
| ablation/ablate_no_mass_prior | clean | iid_noisy_ic | PRBS | 100.0% | 0.0% | 1.3624 | 4.4595 | 0.0280 |
| ablation/ablate_no_mass_prior | clean | v4_lite | CHIRP | 100.0% | 0.0% | 1.1182 | 3.2445 | 0.0205 |
| ablation/ablate_no_mass_prior | clean | v4_lite | OU | 96.0% | 4.0% | 2.0406 | 4.7608 | 0.0514 |
| ablation/ablate_no_mass_prior | clean | v4_lite | PRBS | 100.0% | 0.0% | 1.5260 | 4.0805 | 0.0309 |
| ablation/ablate_no_mass_prior | iid_noisy_ic/nominal_train | iid_noisy_ic | CHIRP | 100.0% | 0.0% | 1.2244 | 3.0779 | 0.0263 |
| ablation/ablate_no_mass_prior | iid_noisy_ic/nominal_train | iid_noisy_ic | OU | 94.7% | 5.3% | 1.6851 | 4.3770 | 0.0359 |
| ablation/ablate_no_mass_prior | iid_noisy_ic/nominal_train | iid_noisy_ic | PRBS | 100.0% | 0.0% | 1.6672 | 4.4856 | 0.0315 |
| ablation/ablate_no_mass_prior | iid_noisy_ic/nominal_train | v4_lite | CHIRP | 100.0% | 0.0% | 1.3528 | 3.0622 | 0.0271 |
| ablation/ablate_no_mass_prior | iid_noisy_ic/nominal_train | v4_lite | OU | 94.7% | 5.3% | 1.5726 | 3.8334 | 0.0356 |
| ablation/ablate_no_mass_prior | iid_noisy_ic/nominal_train | v4_lite | PRBS | 100.0% | 0.0% | 1.5924 | 3.8341 | 0.0336 |
| ablation/ablate_no_mass_prior | v4_lite/nominal_train | iid_noisy_ic | CHIRP | 100.0% | 0.0% | 1.0343 | 2.7278 | 0.0229 |
| ablation/ablate_no_mass_prior | v4_lite/nominal_train | iid_noisy_ic | OU | 94.7% | 5.3% | 1.9713 | 5.9156 | 0.0498 |
| ablation/ablate_no_mass_prior | v4_lite/nominal_train | iid_noisy_ic | PRBS | 100.0% | 0.0% | 1.3482 | 3.5786 | 0.0267 |
| ablation/ablate_no_mass_prior | v4_lite/nominal_train | v4_lite | CHIRP | 100.0% | 0.0% | 1.0807 | 2.8002 | 0.0185 |
| ablation/ablate_no_mass_prior | v4_lite/nominal_train | v4_lite | OU | 95.3% | 4.7% | 2.0894 | 5.0300 | 0.0497 |
| ablation/ablate_no_mass_prior | v4_lite/nominal_train | v4_lite | PRBS | 100.0% | 0.0% | 1.3557 | 3.0738 | 0.0281 |
| main/phnode_full | clean | iid_noisy_ic | CHIRP | 100.0% | 0.0% | 0.8862 | 2.0746 | 0.0139 |
| main/phnode_full | clean | iid_noisy_ic | OU | 97.3% | 2.7% | 1.0076 | 3.2972 | 0.0269 |
| main/phnode_full | clean | iid_noisy_ic | PRBS | 100.0% | 0.0% | 0.9578 | 2.8805 | 0.0157 |
| main/phnode_full | clean | v4_lite | CHIRP | 100.0% | 0.0% | 0.8158 | 2.1192 | 0.0148 |
| main/phnode_full | clean | v4_lite | OU | 97.3% | 2.7% | 0.9017 | 2.5277 | 0.0186 |
| main/phnode_full | clean | v4_lite | PRBS | 100.0% | 0.0% | 0.7771 | 1.8566 | 0.0135 |
| main/phnode_full | iid_noisy_ic/nominal_train | iid_noisy_ic | CHIRP | 100.0% | 0.0% | 0.9667 | 2.3579 | 0.0172 |
| main/phnode_full | iid_noisy_ic/nominal_train | iid_noisy_ic | OU | 94.7% | 5.3% | 1.2296 | 3.5567 | 0.0300 |
| main/phnode_full | iid_noisy_ic/nominal_train | iid_noisy_ic | PRBS | 100.0% | 0.0% | 1.1550 | 3.3646 | 0.0227 |
| main/phnode_full | iid_noisy_ic/nominal_train | v4_lite | CHIRP | 100.0% | 0.0% | 0.9606 | 2.4210 | 0.0163 |
| main/phnode_full | iid_noisy_ic/nominal_train | v4_lite | OU | 95.3% | 4.7% | 1.1224 | 3.3352 | 0.0251 |
| main/phnode_full | iid_noisy_ic/nominal_train | v4_lite | PRBS | 100.0% | 0.0% | 1.0682 | 2.5191 | 0.0220 |
| main/phnode_full | v4_lite/nominal_train | iid_noisy_ic | CHIRP | 100.0% | 0.0% | 1.0175 | 2.7701 | 0.0222 |
| main/phnode_full | v4_lite/nominal_train | iid_noisy_ic | OU | 94.7% | 5.3% | 1.2898 | 3.8120 | 0.0316 |
| main/phnode_full | v4_lite/nominal_train | iid_noisy_ic | PRBS | 100.0% | 0.0% | 1.0187 | 2.8829 | 0.0201 |
| main/phnode_full | v4_lite/nominal_train | v4_lite | CHIRP | 100.0% | 0.0% | 1.1222 | 2.5319 | 0.0225 |
| main/phnode_full | v4_lite/nominal_train | v4_lite | OU | 94.7% | 5.3% | 1.1165 | 3.0737 | 0.0283 |
| main/phnode_full | v4_lite/nominal_train | v4_lite | PRBS | 100.0% | 0.0% | 1.0535 | 2.4751 | 0.0188 |

## Seed-Level Rollout @60s / nominal_eval

| Run | Model | Train | Eval | Seed | Pos Median | Pos P95 | Completion | Model Fail |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| clean__main_phnode_full_seed46 | main/phnode_full | clean | v4_lite | 46 | 0.6618 | 1.8690 | 100.0% | 0.0% |
| clean__main_phnode_full_seed45 | main/phnode_full | clean | v4_lite | 45 | 0.6721 | 1.8533 | 100.0% | 0.0% |
| clean__main_phnode_full_seed43 | main/phnode_full | clean | v4_lite | 43 | 0.6888 | 1.9741 | 100.0% | 0.0% |
| clean__ablation_ablate_no_lift_seed42 | ablation/ablate_no_lift | clean | v4_lite | 42 | 0.7324 | 2.0399 | 97.8% | 2.2% |
| clean__ablation_ablate_no_lift_seed45 | ablation/ablate_no_lift | clean | v4_lite | 45 | 0.7747 | 2.2748 | 98.9% | 1.1% |
| clean__main_phnode_full_seed42 | main/phnode_full | clean | iid_noisy_ic | 42 | 0.8095 | 2.6315 | 97.8% | 2.2% |
| clean__main_phnode_full_seed45 | main/phnode_full | clean | iid_noisy_ic | 45 | 0.8109 | 2.6622 | 100.0% | 0.0% |
| clean__ablation_ablate_no_lift_seed42 | ablation/ablate_no_lift | clean | iid_noisy_ic | 42 | 0.8114 | 2.5833 | 97.8% | 2.2% |
| iid__main_phnode_full_seed45 | main/phnode_full | iid_noisy_ic/nominal_train | v4_lite | 45 | 0.8194 | 2.2673 | 98.9% | 1.1% |
| clean__main_phnode_full_seed46 | main/phnode_full | clean | iid_noisy_ic | 46 | 0.8203 | 2.5168 | 100.0% | 0.0% |
| iid__ablation_ablate_no_lift_seed44 | ablation/ablate_no_lift | iid_noisy_ic/nominal_train | iid_noisy_ic | 44 | 0.8266 | 3.0526 | 97.8% | 2.2% |
| clean__ablation_ablate_no_lift_seed45 | ablation/ablate_no_lift | clean | iid_noisy_ic | 45 | 0.8609 | 2.5785 | 98.9% | 1.1% |
| v4lite__ablation_ablate_no_lift_seed45 | ablation/ablate_no_lift | v4_lite/nominal_train | v4_lite | 45 | 0.8664 | 2.8093 | 97.8% | 2.2% |
| clean__main_phnode_full_seed42 | main/phnode_full | clean | v4_lite | 42 | 0.8684 | 1.9885 | 97.8% | 2.2% |
| v4lite__ablation_ablate_no_mass_prior_seed42 | ablation/ablate_no_mass_prior | v4_lite/nominal_train | iid_noisy_ic | 42 | 0.8923 | 3.2552 | 98.9% | 1.1% |
| v4lite__ablation_ablate_no_lift_seed45 | ablation/ablate_no_lift | v4_lite/nominal_train | iid_noisy_ic | 45 | 0.8990 | 3.2726 | 97.8% | 2.2% |
| clean__main_phnode_full_seed43 | main/phnode_full | clean | iid_noisy_ic | 43 | 0.9145 | 2.7506 | 100.0% | 0.0% |
| v4lite__ablation_ablate_no_lift_seed44 | ablation/ablate_no_lift | v4_lite/nominal_train | v4_lite | 44 | 0.9273 | 3.0737 | 98.9% | 1.1% |
| v4lite__main_phnode_full_seed43 | main/phnode_full | v4_lite/nominal_train | v4_lite | 43 | 0.9436 | 2.3235 | 97.8% | 2.2% |
| iid__main_phnode_full_seed46 | main/phnode_full | iid_noisy_ic/nominal_train | v4_lite | 46 | 0.9469 | 2.9624 | 97.8% | 2.2% |
| v4lite__ablation_ablate_no_mass_prior_seed42 | ablation/ablate_no_mass_prior | v4_lite/nominal_train | v4_lite | 42 | 0.9540 | 2.7648 | 98.9% | 1.1% |
| iid__main_phnode_full_seed43 | main/phnode_full | iid_noisy_ic/nominal_train | iid_noisy_ic | 43 | 0.9545 | 3.2740 | 97.8% | 2.2% |
| v4lite__ablation_ablate_no_lift_seed42 | ablation/ablate_no_lift | v4_lite/nominal_train | iid_noisy_ic | 42 | 0.9641 | 3.4543 | 97.8% | 2.2% |
| iid__main_phnode_full_seed43 | main/phnode_full | iid_noisy_ic/nominal_train | v4_lite | 43 | 0.9797 | 2.7632 | 97.8% | 2.2% |
| v4lite__main_phnode_full_seed43 | main/phnode_full | v4_lite/nominal_train | iid_noisy_ic | 43 | 0.9868 | 2.6973 | 97.8% | 2.2% |
| iid__ablation_ablate_no_lift_seed43 | ablation/ablate_no_lift | iid_noisy_ic/nominal_train | iid_noisy_ic | 43 | 0.9870 | 3.0326 | 97.8% | 2.2% |
| iid__ablation_ablate_no_lift_seed44 | ablation/ablate_no_lift | iid_noisy_ic/nominal_train | v4_lite | 44 | 0.9885 | 2.5788 | 97.8% | 2.2% |
| iid__ablation_ablate_no_mass_prior_seed42 | ablation/ablate_no_mass_prior | iid_noisy_ic/nominal_train | iid_noisy_ic | 42 | 0.9981 | 3.2458 | 98.9% | 1.1% |
| v4lite__main_phnode_full_seed42 | main/phnode_full | v4_lite/nominal_train | iid_noisy_ic | 42 | 1.0064 | 3.3526 | 98.9% | 1.1% |
| iid__main_phnode_full_seed42 | main/phnode_full | iid_noisy_ic/nominal_train | iid_noisy_ic | 42 | 1.0081 | 4.2947 | 98.9% | 1.1% |
| iid__ablation_ablate_no_lift_seed45 | ablation/ablate_no_lift | iid_noisy_ic/nominal_train | iid_noisy_ic | 45 | 1.0093 | 3.1251 | 97.8% | 2.2% |
| clean__ablation_ablate_no_lift_seed44 | ablation/ablate_no_lift | clean | v4_lite | 44 | 1.0118 | 2.6263 | 98.9% | 1.1% |
| v4lite__main_phnode_full_seed42 | main/phnode_full | v4_lite/nominal_train | v4_lite | 42 | 1.0205 | 2.9773 | 98.9% | 1.1% |
| clean__ablation_ablate_no_lift_seed44 | ablation/ablate_no_lift | clean | iid_noisy_ic | 44 | 1.0208 | 2.8858 | 98.9% | 1.1% |
| iid__ablation_ablate_no_mass_prior_seed42 | ablation/ablate_no_mass_prior | iid_noisy_ic/nominal_train | v4_lite | 42 | 1.0270 | 3.0243 | 98.9% | 1.1% |
| v4lite__ablation_ablate_no_lift_seed43 | ablation/ablate_no_lift | v4_lite/nominal_train | iid_noisy_ic | 43 | 1.0314 | 3.3823 | 98.9% | 1.1% |
| iid__ablation_ablate_no_lift_seed42 | ablation/ablate_no_lift | iid_noisy_ic/nominal_train | v4_lite | 42 | 1.0353 | 3.4581 | 97.8% | 2.2% |
| iid__ablation_ablate_no_lift_seed43 | ablation/ablate_no_lift | iid_noisy_ic/nominal_train | v4_lite | 43 | 1.0417 | 2.6931 | 97.8% | 2.2% |
| iid__main_phnode_full_seed45 | main/phnode_full | iid_noisy_ic/nominal_train | iid_noisy_ic | 45 | 1.0639 | 2.5984 | 97.8% | 2.2% |
| iid__main_phnode_full_seed44 | main/phnode_full | iid_noisy_ic/nominal_train | v4_lite | 44 | 1.0656 | 3.2083 | 98.9% | 1.1% |
| iid__ablation_ablate_no_lift_seed45 | ablation/ablate_no_lift | iid_noisy_ic/nominal_train | v4_lite | 45 | 1.0756 | 3.2832 | 97.8% | 2.2% |
| clean__ablation_ablate_no_mass_prior_seed42 | ablation/ablate_no_mass_prior | clean | v4_lite | 42 | 1.0782 | 3.5954 | 100.0% | 0.0% |
| v4lite__main_phnode_full_seed44 | main/phnode_full | v4_lite/nominal_train | iid_noisy_ic | 44 | 1.0800 | 3.7178 | 98.9% | 1.1% |
| clean__ablation_ablate_no_mass_prior_seed46 | ablation/ablate_no_mass_prior | clean | iid_noisy_ic | 46 | 1.0838 | 3.3977 | 97.8% | 2.2% |
| v4lite__main_phnode_full_seed44 | main/phnode_full | v4_lite/nominal_train | v4_lite | 44 | 1.0878 | 3.4630 | 98.9% | 1.1% |
| v4lite__main_phnode_full_seed46 | main/phnode_full | v4_lite/nominal_train | iid_noisy_ic | 46 | 1.0899 | 3.5875 | 97.8% | 2.2% |
| iid__ablation_ablate_no_lift_seed42 | ablation/ablate_no_lift | iid_noisy_ic/nominal_train | iid_noisy_ic | 42 | 1.0938 | 3.7961 | 97.8% | 2.2% |
| iid__ablation_ablate_no_lift_seed46 | ablation/ablate_no_lift | iid_noisy_ic/nominal_train | iid_noisy_ic | 46 | 1.1047 | 4.2513 | 100.0% | 0.0% |
| clean__ablation_ablate_no_mass_prior_seed42 | ablation/ablate_no_mass_prior | clean | iid_noisy_ic | 42 | 1.1083 | 3.4585 | 100.0% | 0.0% |
| v4lite__ablation_ablate_no_lift_seed44 | ablation/ablate_no_lift | v4_lite/nominal_train | iid_noisy_ic | 44 | 1.1309 | 2.8564 | 98.9% | 1.1% |
| clean__ablation_ablate_no_mass_prior_seed46 | ablation/ablate_no_mass_prior | clean | v4_lite | 46 | 1.1333 | 2.9964 | 97.8% | 2.2% |
| iid__ablation_ablate_no_lift_seed46 | ablation/ablate_no_lift | iid_noisy_ic/nominal_train | v4_lite | 46 | 1.1342 | 3.4102 | 100.0% | 0.0% |
| v4lite__ablation_ablate_no_lift_seed43 | ablation/ablate_no_lift | v4_lite/nominal_train | v4_lite | 43 | 1.1581 | 2.7323 | 98.9% | 1.1% |
| iid__main_phnode_full_seed44 | main/phnode_full | iid_noisy_ic/nominal_train | iid_noisy_ic | 44 | 1.1830 | 3.3477 | 98.9% | 1.1% |
| iid__ablation_ablate_no_mass_prior_seed46 | ablation/ablate_no_mass_prior | iid_noisy_ic/nominal_train | v4_lite | 46 | 1.1831 | 2.9045 | 97.8% | 2.2% |
| v4lite__ablation_ablate_no_lift_seed42 | ablation/ablate_no_lift | v4_lite/nominal_train | v4_lite | 42 | 1.1887 | 3.3797 | 97.8% | 2.2% |

## 10. Optional diagnostics

`degraded_eval` 和 `heading_biased_eval` 仅作为后续诊断或 Phase-1B 条件扩展，不在本 notebook 的默认 clean run 中执行。